### ISSUE TITLE
One ReferenceError or TypeError breaks $(document).ready and prevents it from ever firing again

### ISSUE THREAD

**Issue by jdahobbs** [jquery/jquery#2262] opened 2015-05-05 04:08 UTC
jsFiddle for reproduction: http://jsfiddle.net/n093b4pg/3/

If a single exception is thrown inside a `$(document).ready` callee, the `ready` event will never fire again and will become entirely unresponsive to new attempts to call it.

Similar is other event bindings, like click: after one callee in the list throws an exception, later callees won't be called ([example](http://jsfiddle.net/xvza6ddq/)). However, the event doesn't shut down and become totally unresponsive for all time.

**Expected behaviour:** Each `$(document).ready` callee should be handled in isolation. If one breaks and throws an exception, it does not break every later `$(document).ready` call for all time.

(Alternately, the expected behaviour could be exactly how it's working now? I don't think it is documented. This just left us hunting for a few hours today.)

**Comment by markelog** [comment] 2015-05-05 13:49
I think we should support at least ` $(document).ready` case, it easy enough to fix, since we now follow the Promises standart.

For "other" events i'd say its open for discussion.

**Comment by gibson042** [comment] 2015-05-05 14:40
Duplicate of gh-1823, and see also gh-1778 for related changes.

**Closed by gibson042** 2015-05-05 14:40 UTC
Labels: Core, Feature

**Comment by markelog** [comment] 2015-05-05 15:19
@gibson042 #1823 is relevant i agree, but this discussion is also about event handlers execution

**Comment by gibson042** [comment] 2015-05-05 16:22
I read that part as an incidental, with the primary content of this issue regarding `.ready` and duplicating gh-1823. A standalone issue for event handlers throwing exceptions (remember, `.ready` aliases `jQuery.ready.promise().done` rather than `.on`/`.trigger`) might be warranted, though.

**Comment by markelog** [comment] 2015-05-05 16:36
> (remember, .ready aliases jQuery.ready.promise().done rather than .on/.trigger

Yeah, i do, since i wrote - 

> it easy enough to fix, since we now follow the Promises standart.

But `ready` could be also represented as

```js
$( document ).on( "ready", function() {
  ...
});
```
which above mentioned fix (at least the one i have in mind) would not apply, i think we should discuss exceptions in event handlers too.

**Comment by dmethvin** [comment] 2015-05-05 17:20
The `ready` event is deprecated though, so if it breaks it's not particularly a problem. 

Since we multiplex all `.on()` events under a single handler, you're right that an error in one prevents the others from running. It would take a significant redesign in the event subsystem to avoid that and I'm not sure it's been a big problem.

**Comment by markelog** [comment] 2015-05-05 17:39
> The ready event is deprecated though

Correct, we probably should remove it?

**Comment by gibson042** [comment] 2015-05-05 17:43
> we probably should remove it?

Yes: https://github.com/jquery/jquery/issues/1778#issuecomment-72764833

**Comment by jdahobbs** [comment] 2015-05-06 03:01
Yes, the mention of other events was incidental and only used for comparison: future clicks still call their event chain even if one callee throws an exception. (The chain will just break at that point each time.) Document.ready just gives up and stops forever.

> The ready event is deprecated though, so if it breaks it's not particularly a problem. 

The `$(document).ready` event is deprecated? [The documentation](http://api.jquery.com/ready/) doesn't seem to suggest anything of the sort. It only says it about one form:

> There is also `$(document).on( "ready", handler ),` deprecated as of jQuery 1.8.

... but offers using these:

> * `$( document ).ready( handler )`
> * `$().ready( handler )` (this is not recommended)
> * `$( handler )`

**Comment by timmywil** [comment] 2015-05-06 04:51
@jdahobbs `$(document).ready` and the others don't use the ready event, which could be defined as a custom jQuery event that is fired on the document ready event. When you add a ready handler using one of the other methods, that custom jQuery event is not involved.
