### ISSUE TITLE
jQuery 2.2.2 Unrecognized Expression when Matching Multiple Attributes

### ISSUE THREAD

**Issue by TwentyOneSolutions** [jquery/jquery#3038] opened 2016-04-04 16:43 UTC
This is working fine with jQuery 2.1.4 so I'm not sure at what point it breaks, but it's after 2.1.4;  The stack trace below is from jQuery 2.2.2

The error I see in the console is:

	Uncaught Error: Syntax error, unrecognized expression: 
		[data-toggle=collapse][data-target=#table-wrapper-01]

	Sizzle.error 				@ jquery-2.2.2.js:1468
	Sizzle.tokenize 			@ jquery-2.2.2.js:2125
	Sizzle 						@ jquery-2.2.2.js:838
	jQuery.fn.extend.find 		@ jquery-2.2.2.js:2792
	(anonymous function) 		@ code.js:442               // see below
	jQuery.extend.each 			@ jquery-2.2.2.js:365
	jQuery.fn.jQuery.each 		@ jquery-2.2.2.js:137
	(anonymous function) 		@ code.js:437
	fire 						@ jquery-2.2.2.js:3187
	self.fireWith 				@ jquery-2.2.2.js:3317
	jQuery.extend.ready 		@ jquery-2.2.2.js:3536
	completed 					@ jquery-2.2.2.js:3552

The code that I have at code.js:442 is
	
	L441	var trigger = $el.parents(".collapsible-panel")
	L442		.find("[data-toggle=collapse][data-target=#" + id + "]");	// match multiple attributes

Reverting to jQuery 2.1.4 fixes the issue.

**Comment by mgol** [comment] 2016-04-04 17:09
A duplicate of #2824. You need to quote the selector:
```
[data-toggle=collapse][data-target="#table-wrapper-01"]
```

**Closed by mgol** 2016-04-04 17:09 UTC

**Comment by TwentyOneSolutions** [comment] 2016-04-04 17:16
Got it, thanks!
