### ISSUE TITLE
Case-insensitive selector does not work in some case.

### ISSUE THREAD

**Issue by M-Tony** [jquery/jquery#5110] opened 2022-09-06 13:48 UTC
### Description ###

I was happy to see that case-insensitive selectors work with jQuery, but I ran into an issue while updating my code:

This works fine:
`var a = $("input[name='myfield' i]");`

This also works fine:
`var b = $("input[name='myfield']", "#myform");`

But, this does not work:
`var c = $("input[name='myfield' i]", "#myform");`

I got the following error message:
`Uncaught Error: Syntax error, unrecognized expression: input[name='myfield' i]`

The form element has id="myform" and the input field has name="myfield".

Tested with jQuery v.3.6.1.

**Comment by dmethvin** [comment] 2022-09-07 01:44
> `var a = $("input[name='myfield' i]")`

What is the role of `i` in that selector? How does it affect the result?

**Comment by mgol** [comment] 2022-09-07 05:30
A duplicate of #4841.

**Closed by mgol** 2022-09-07 05:30 UTC

**Comment by M-Tony** [comment] 2022-09-07 08:33
> > `var a = $("input[name='myfield' i]")`
> 
> What is the role of `i` in that selector? How does it affect the result?

This is to make case-insensitive search, so it will match "myfield", "MyField",...
But, as I mentioned before, this `var a = $("input[name='myfield' i]")` works fine.

But, this does not work:
var c = $("input[name='myfield' i]", "#myform");

And, I think this is not a duplicate, as indicated.
I read [#4841](https://github.com/jquery/jquery/issues/4841) before, but it is about `on('click',..)` method. Here I do not use `on('click',...)`.

**Comment by mgol** [comment] 2022-09-07 09:42
OK, I created a more generic #5111, let's track it there.

**Comment by mgol** [comment] 2022-09-07 09:44
I updated the title of #4841 to be more generic as the root cause is identical. Also, I created a bigger issue to evaluate CSS Selectors Level 4 support: #5111.

**Comment by M-Tony** [comment] 2022-09-07 13:49
Thanks @mgol !
