### ISSUE TITLE
hasClass not working on svg

### ISSUE THREAD

**Issue by nodegin** [jquery/jquery#2628] opened 2015-10-03 18:15 UTC
```html
<svg id="apple" class="clickable" viewBox="0 0 24 24">
    <path fill="#000" d="M18.71,19.5C17.88,20.74 17,21.95 15.66,21.97C14.32,22 13.89,21.18 12.37,21.18C10.84,21.18 10.37,21.95 9.1,22C7.79,22.05 6.8,20.68 5.96,19.47C4.25,17 2.94,12.45 4.7,9.39C5.57,7.87 7.13,6.91 8.82,6.88C10.1,6.86 11.32,7.75 12.11,7.75C12.89,7.75 14.37,6.68 15.92,6.84C16.57,6.87 18.39,7.1 19.56,8.82C19.47,8.88 17.39,10.1 17.41,12.63C17.44,15.65 20.06,16.66 20.09,16.67C20.06,16.74 19.67,18.11 18.71,19.5M13,3.5C13.73,2.67 14.94,2.04 15.94,2C16.07,3.17 15.6,4.35 14.9,5.19C14.21,6.04 13.07,6.7 11.95,6.61C11.8,5.46 12.36,4.26 13,3.5Z">
</svg>
```

```js
$('#apple').click(function(){
      console.log($(this).hasClass('clickable')); // result in false
      console.log($(this).is('.clickable')); // result in true
});
```

also ```removeClass``` and ```addClass``` does not work too

but ```removeAttr``` works

**Comment by mzgol** [comment] 2015-10-03 18:23
Duplicate of #2199. This is fixed on `master` (http://jsfiddle.net/eac1fcea/) and in jQuery 3.0.0-alpha1 (http://jsfiddle.net/eac1fcea/1/). Please always check if the bug exists in the latest development version (i.e. https://code.jquery.com/jquery-git.js) before reporting.

Note, though, that jQuery doesn't generally support SVG, we've only added class support since so many people asked about it: https://contribute.jquery.org/wont-fix/#svg-vml-or-namespaced-elements-bugs.

**Closed by mzgol** 2015-10-03 18:23 UTC

**Comment by dwghihanw** [comment] 2017-10-13 02:58
This functions not working of before versions of jquery 3

try this : 

This is a hack for addClass, removeClass, hasClass jquery methods for before jquery 3.x.x versions.

    $.fn.extend({
        addSVGClass: function (cls) {
            return this.each(function () {
                var classList = $(this).attr('class');
                if (classList) {
                    var classListArr = classList.split(" ");
                    if (classListArr.indexOf(cls) === -1) {
                        classListArr.push(cls);
                        classList = classListArr.join(" ").trim();
                        $(this).attr('class', classList);
                    }
                } else {
                    $(this).attr('class', cls);
                }
            });
        },
        removeSVGClass: function (cls) {
            return this.each(function () {
                var classList = $(this).attr('class');
                if (classList) {
                    var classListArr = classList.split(" ");
                    if (classListArr.indexOf(cls) !== -1) {
                        delete classListArr[classListArr.indexOf(cls)];
                        classList = classListArr.join(" ").trim();
                        $(this).attr('class', classList);
                    }
                }
    
            });
        },
        hasSVGClass: function (cls) {
            var el = this[0];
            var classList = $(el).attr('class');
            if (classList) {
                var classListArr = classList.split(" ");
                if (classListArr.indexOf(cls) !== -1) {
                    return true;
    
                } else {
                    return false;
                }
            }
            return false;
        }
    });

usage : 
` $('.svg-element').addSVGClass('selected');`
