### ISSUE TITLE
Unable to load jquery from cdn due to bad ssl cert (all browsers)

### ISSUE THREAD

**Issue by niemyjski** [jquery/jquery#3359] opened 2016-10-13 18:05 UTC
![screen shot 2016-10-13 at 1 03 55 pm](https://cloud.githubusercontent.com/assets/1020579/19360817/b261abd6-9145-11e6-8247-6ae34c197052.png)

**Comment by dmethvin** [comment] 2016-10-13 18:25
Yes, we're aware although not sure whether the problem is something we can fix on our side.

I'll leave this ticket open since people seem to be creating new ones regularly.

**Comment by dmethvin** [comment] 2016-10-13 18:43
https://twitter.com/globalsign/status/786617201788723200

**Comment by fuwaneko** [comment] 2016-10-14 08:58
@dmethvin clearing the cache on client side is not enough, you have to follow https://twitter.com/globalsign/status/786739289736347650 and apply the fix on server side too.

**Comment by timmywil** [comment] 2016-10-24 16:24
This should be fixed now.

**Closed by timmywil** 2016-10-24 16:24 UTC
