### ISSUE TITLE
jQuery.event.props

### ISSUE THREAD

**Issue by silverwind** [jquery/jquery#3112] opened 2016-05-10 20:02 UTC
https://github.com/jquery/jquery/commit/e61fccb9d736235b4b011f89cba6866bc0b8997d removed `jQuery.event.props` which is still mentioned in this [docs snippet](https://api.jquery.com/category/events/event-object/):

````js
// add the dataTransfer property for use with the native `drop` event
// to capture information about files dropped into the browser window
jQuery.event.props.push( "dataTransfer" );
````

If this change is intended to be breaking, I suggest pointing users to `event.originalEvent`.

**Comment by mgol** [comment] 2016-05-10 20:10
This is an API site request so I'm closing it as a duplicate of https://github.com/jquery/api.jquery.com/issues/405. That issue is quite old, though so it's good you reminded us about the change now being more needed than before; thanks!

**Closed by mgol** 2016-05-10 20:10 UTC

**Comment by snowygman** [comment] 2017-03-24 08:28
Hey,
I'm using `var files = e.originalEvent.dataTransfer.files` at the start of my drop function.  The code was designed to read the file properties and keep adding it to a tabular list under the target area where the files are dropped.   but it doesn't seem to hold all the files dropped unto the target area of my html page. 
I replaced `jQuery.event.props.push( "dataTransfer" );` with the code above, but it only seems to store the current file details in the File variable.  
**What I'm wondering is whether `e.originalEvent.dataTransfer.files` can stack my file details as a filelist, if I drop several files unto the target?** I loop through the file variable and print a table of the file details, but I'm only able to retrieve the last file dropped. 
```
$table = $('#fileInfo'), //grabs a DOM element in Jquery
            i = 0;
    $table.html('<thead><tr><th>Name</th><th>Type</th><th>Size</th></tr></thead>');
for (i = 0; i < files.length; i++) {
            $('<tr><td>'
            + files[i].name + '</td><td>'
            + files[i].type + '</td><td>'
            + files[i].size + '</td></tr>'). appendTo($table);
        }
        preventDefault(e);
```
Am I using the originalevent properly and what adjustments do I need to make to get my file variable to store multiple file details while the page is active? 
Thanks for any assistance.
