### ISSUE TITLE
npmignore

### ISSUE THREAD

**Issue by TrySound** [jquery/jquery#2527] opened 2015-08-04 10:31 UTC
Hi! Add please src/sizzle/test to npm ignore. node packages should be small as it possible too.

**Comment by mzgol** [comment] 2015-08-04 11:04
Duplicate of https://github.com/jquery/jquery/issues/1817. Thanks for the report but this has been discussed at length, some people need the source files so they need to be published. We're not going to split that into separate packages, that's too much maintenance burden.

**Comment by mzgol** [comment] 2015-08-04 11:04
Btw, the test folder is already not published.

**Closed by mzgol** 2015-08-04 11:04 UTC

**Comment by TrySound** [comment] 2015-08-04 12:00
@mzgol I don't talk about sources. In my `node_modules` there is a 350kb directory `src/sizzle/test`, but I don't see it in the repo

**Comment by mzgol** [comment] 2015-08-04 13:08
Which version? I think I remember something but it was removed so jQuery 3.0.0 won't contain src/sizzle/test. You can check `npm install jquery@beta` to see how 3.0.0-alpha1 looks like.

**Comment by TrySound** [comment] 2015-08-04 13:14
@mzgol By default npm loads `2.1.4`

**Comment by TrySound** [comment] 2015-08-04 13:14
Okay. Waiting for stable 3

**Comment by mzgol** [comment] 2015-08-04 13:25
Yeah, publishing `src/sizzle/test` was a mistake, we can't reverse it now. It will be fine in 3.0.0.

If you see sth wrong in the jQuery 3.0.0 alpha/beta packages, please report so that we can fix it in time for 3.0.0. :)
