### ISSUE TITLE
before() and after() functions cause improper DOM redraw in Chromium when used with multivalue select

### ISSUE THREAD

**Issue by caseif** [jquery/jquery#4692] opened 2020-04-28 19:13 UTC
### Description ###

When the `before()` and `after()` functions are used on `option` elements within a multivalue `select` element (as in the case of sorting buttons), the manipulated element temporarily disappears (and re-appears once the `select` element is clicked). This issue occurs only with the Chromium engine and does not affect Firefox or Old Edge. It appears to occur with the latest nightly build of the Chromium browser.

This behavior does not occur when using vanilla JavaScript to manipulate the DOM in a similar way, e.g. `element.previousElementSibling.insertAdjacentElement("beforebegin", element)`. I am unfamiliar with the code path used by jQuery so I am unable to further investigate the discrepancy at this time.

### Link to test case ###

https://gist.github.com/caseif/137102e76634fd34470af0ffad23891f

**Comment by mgol** [comment] 2020-04-28 20:39
Thanks for the report. Can you provide a test case on [JS Bin](https://jsbin.com/qawicop/edit?html,css,js,output) as the issue template requested? Thanks!

**Comment by mgol** [comment] 2020-04-28 20:40
Oh, actually, this looks like a duplicate of #4679.

**Closed by mgol** 2020-04-28 20:40 UTC

**Comment by caseif** [comment] 2020-04-28 22:06
Sorry about that! I wrote the issue up in a bit of a hurry and somehow completely overlooked the one it duplicates.
