### ISSUE TITLE
Cannot read property 'toUpperCase' of undefined

### ISSUE THREAD

**Issue by ghego1** [jquery/jquery#3307] opened 2016-08-31 11:23 UTC
jQuery v. 2.2.2
  *  What do you expect to happen? Nothing
  *  What acually happens? Error thrown: angular.js:13424 TypeError: Cannot read property 'toUpperCase' of undefined at vendorPropName (jquery.js:5890)
  *  Which browsers are affected? All

### Description ###
When launching my AngularJS (v.1.5.x) app, the error is thrown.

To solve the issue is appears to be enough to add a simple condition at line 5890, like so:

    // Check for vendor prefixed names
    if(name[ 0 ]) var capName = name[ 0 ].toUpperCase() + name.slice( 1 ), i = cssPrefixes.length;

**Comment by mgol** [comment] 2016-08-31 11:56
We need more details; in particular, a test case at jsfiddle or jsbin. Most likely it's a bug in your code but it's impossible to tell from just the error message.

**Comment by ktajpuri** [comment] 2016-09-15 14:41
```
// Check for vendor prefixed names
if(name[ 0 ]) var capName = name[ 0 ].toUpperCase() + name.slice( 1 ), i = cssPrefixes.length;
```
It appears ```name[ 0 ]``` is not defined. Probalble causes i can think of is that name variable is not defined. Try doing an ```console.log(name);``` just before the error is being thrown.

**Comment by magician03** [comment] 2016-09-16 17:56
@ghego1 Are you still facing the issue, if yes, please reproduce the bug at jsfiddle or jsbin for further proceedings regarding the issue.

**Comment by ghego1** [comment] 2016-09-16 18:11
@ktajpuri yes I had already tested that and the problem is that name is undefined.

@magician03 Yes I'm still experiencing it unfortunately. I am unable to reproduce it though, as it is not "my" code that is causing it. I am quite sure that it is caused by some third party library, but since it's a very large project  (angularjs + angular material + a dozen of minor other libs) I have no idea of how to trace down what is causing the problem. Do you have any idea on how I could reproduce it in a jsfiddle?

**Comment by magician03** [comment] 2016-09-16 18:23
@ghego1 Reproducing a minor bug from such a large issue might be difficult, but give it a try, include all the major libraries in the External Resources panel of jsfiddle and include the code that revolves( invoking the err, what should be the possible result if not err is reported and other related things.) the bug in the fiddle with some sample data.

**Comment by dmethvin** [comment] 2016-09-16 18:24
Since this isn't a jQuery bug I'll close it. You're welcome to continue to debug on StackOverflow or the jQuery Forum.

**Closed by dmethvin** 2016-09-16 18:24 UTC
Labels: Needs info
