### ISSUE TITLE
Jquery .load ajax reported depreciated incorrectly

### ISSUE THREAD

**Issue by geofili** [jquery/jquery#2942] opened 2016-02-23 22:41 UTC
The jquery .load event was depreciated as of version 1.8 (See: https://api.jquery.com/load-event/)

But the jquery .load ajax modal has not been deprecated (See: https://api.jquery.com/load/)

When I try and use the ajax load command like so:

```
$('#divcontent').load('page.url #divcontainer', function (response, status, xhr) {
    alert('loaded content');
});
```

the JQMIGRATE incorrectly reports that jQuery.fn.load() is deprecated.

I believe this to be a bug in JQMIGRATE

**Comment by dmethvin** [comment] 2016-02-23 22:43
This is a duplicate of https://github.com/jquery/jquery-migrate/issues/138 and will be fixed in the next release of jquery-migrate later this week.

**Closed by dmethvin** 2016-02-23 22:43 UTC

**Comment by geofili** [comment] 2016-02-23 22:47
Thanks. Wasted couple of hours trying to figure out why it was reporting as depreciated while updating some legacy code.
