### ISSUE TITLE
Minified version of jQuery include unexpect block scoped function

### ISSUE THREAD

**Issue by concavelenz** [jquery/jquery#3153] opened 2016-06-08 20:28 UTC
### Description ###

The minified version of jQuery 2.x has been transformed in a way that includes a block scoped functions.  The original source is roughly:

	if ( !div.style ) {
	  return;
	}

	...

	function computeStyleTests() {
	  ...
	}

This gets transformed (without renaming for clarity) into:

	if ( div.style ) {
	  ...
	  function computeStyleTests() {
	    ...
	  }
	}

This code is invalid in strict mode in older browsers (non-ES6 supporting browsers).  The function should either be transformed into "var i = function() { ...}" or hoisted above the if block.

This is primarily a concern for jquery bundled in strict mode but I ran into this when trying to make block scoped functions an ES6+ only feature in the Closure Compiler and ran into some code pulling the minified jQuery into its build.

**Comment by mgol** [comment] 2016-06-08 20:33
This was fixed in UglifyJS and jQuery 3.x should be fine but we didn't upgrade `grunt-contrib-uglify` on the `1.12-stable` & `2.2-stable` branches.

Is this a real issue in 1.x/2.x, though? In ES6 it is allowed in non-strict mode and none of our supported browsers choke on this code. If you change the jQuery source into strict mode when it wasn't released in this mode you're changing semantics of what we released, we can't support such modifications.

jQuery will rely on strict mode only from 3.0.0 onwards.

**Comment by concavelenz** [comment] 2016-06-08 20:49
If you already have a fix, is it really problematic to deploy it?  It would solve the problems I have.

**Comment by concavelenz** [comment] 2016-06-08 21:06
Also do you have a link to an uglify issue to reference?

**Comment by mgol** [comment] 2016-06-08 21:32
The issue is https://github.com/mishoo/UglifyJS2/issues/1052.

Releasing a new version has its costs; our [release process](https://github.com/jquery/jquery/wiki/Release-process) is multi-step, we'd have to release 2 versions simultaneously, there's always a danger that a new release will break something etc. Moreover, we're preparing to release jQuery 3.0.0 and the 1.x/2.x lines will only receive critical fixes from now on.

I'd like to reiterate what I said, though - if you're changing the execution mode of the libraries you use, you're asking for problems as strict mode changes semantics. You can by all means put your own code in strict mode but you can't do that for libraries without taking the burden of suffering the consequences. There's no bug in jQuery for us to fix here and fixing an issue that appeared because of incorrect use of the library doesn't warrant releasing new versions.

You can also minify jQuery by yourself. There are lots of things you can do that don't require us to release new 2.2/1.12 versions.

I'm going to close this issue now since I don't think there's anything actionable on our part but feel free to continue the discussion.

**Closed by mgol** 2016-06-08 21:32 UTC

**Comment by concavelenz** [comment] 2016-06-08 21:37
I'm not necessarily asking for a release just for this, but if it is part of the next version of the 1.x/2.x branches, I think that would be sufficient for my purposes (I make a temporary local change, with the confidence that I don't have to maintain a fork forever).

**Comment by mgol** [comment] 2016-06-08 22:31
That's a reasonable request. I commited the `grunt-contrib-uglify` version bump to both 1.x & 2.x branches so if we ever cut new versions the fixed UglifyJS will be used.

Could you check whether https://code.jquery.com/jquery-2.x-git.min.js is free of this problem? That's the tip of the branch so don't use it anywhere but it's good to verify the issue is, indeed, fixed.

Thanks!

**Comment by shicks** [comment] 2016-06-09 01:45
This does appear to still be broken:
```
$ egrep -o 'if\(\w\.style\)\{[^}]*function\s\w\(' /tmp/jquery-2.x-git.min.js

if(h.style){h.style.backgroundClip="content-box",h.cloneNode(!0).style.backgroundClip="",l.clearCloneStyle="content-box"===h.style.backgroundClip,g.style.cssText="border:0;width:8px;height:0;top:0;left:-9999px;padding:0;margin-top:1px;position:absolute",g.appendChild(h);function i(
```

**Comment by dmethvin** [comment] 2016-06-09 10:34
Not sure why that didn't fix the problem, it's the version of Uglify that we're using on master. I'd echo the concerns that we don't support strict mode in 1.x/2.x and in fact [specifically avoid it](https://github.com/jquery/jquery/blob/b14ce54334a568eaaa107be4c441660a57c3db24/src/intro.js#L41-44) due to compat issues.
