### ISSUE TITLE
Map method is flattening arrays

### ISSUE THREAD

**Issue by pensierinmusica** [jquery/jquery#2743] opened 2015-11-26 15:48 UTC
Hi,

I'm using `jQuery.map()`, but I'm a little confused about the output.

```js
jQuery.map([1,2,3], function (el) {
  return ['x', el];
})
```

I would expect the function above to return this array of arrays:

```js
[['x', 1], ['x', 2], ['x', 3]]
```

And instead it returns a flat array:

```js
['x',1,'x',2,'x',3]
```

In my understanding this is a bug, and it differs from the beahvior I get from [native JS](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map), [Underscore](http://underscorejs.org/), or [Lodash](http://underscorejs.org/), where all return the expected array of arrays.

For example:

```js
[1,2,3].map(function (el) {
  return ['x', el];
});

// -> [['x', 1], ['x', 2], ['x', 3]]
```

Is this jQuery deviation from standards intentional, or should be fixed? Thanks!

p.s. It looks like this issue was referred here too:
http://stackoverflow.com/questions/703355/is-there-a-jquery-map-utility-that-doesnt-automically-flatten

**Comment by mzgol** [comment] 2015-11-26 15:56
Duplicate of #2652.

**Comment by pensierinmusica** [comment] 2015-11-26 15:57
Mmm, looks like a few years ago the issue was raised and then discarded:
http://bugs.jquery.com/ticket/10541

Would this be time to reconsider?

**Closed by mzgol** 2015-11-26 15:56 UTC

**Comment by dmethvin** [comment] 2015-11-27 15:05
This behavior has been documented for nearly a decade in jQuery, and is used internally. If you require other behavior the best thing to do would be to create a plugin.
