### ISSUE TITLE
Upgrade from 1.11.3 to 1.12.0 breaks smooth scrolling page jumps

### ISSUE THREAD

**Issue by darkwolffe** [jquery/jquery#2884] opened 2016-01-29 15:43 UTC
Using the following code:

`$('a[href*=#]:not([href=#])').click(function() {
    if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') 
        || location.hostname == this.hostname) {
        var target = $(this.hash);
        target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
           if (target.length) {
             $('html,body').animate({
                 scrollTop: target.offset().top
            }, 1000);
            return false;
        }
    }
});`

... one can create a smooth scrolling page jump using jQuery. In version 1.11.3 this works fine, but upon upgrading to version 1.12.0, the following error is shown in the JavaScript console:

`Uncaught Error: Syntax error, unrecognized expression: a[href*=#]:not([href=#])`

**Comment by timmywil** [comment] 2016-01-29 15:45
Duplicate of gh-2824

**Closed by timmywil** 2016-01-29 15:45 UTC
