### ISSUE TITLE
Mouseover / Mousemove "e.which" does not output the correct mouse button inputs properly in Firefox

### ISSUE THREAD

**Issue by chopin2256** [jquery/jquery#5164] opened 2022-11-21 06:15 UTC
### Description ###
The e.which value does not work in Firefox when doing a mouseover. The value is a constant value of 1 for all mouse inputs. I expect to see normalized values:

No Click: 0
Left Click: 1
Middle Click: 2
Right Click: 3

Works as expected in Chrome. See test case for example.

### Link to test case ###
Instructions: Open Firefox, then hover over the red box. The value should be 0, but we get 1. Now left click and drag over the red box. Notice a value of 1. Now right click and drag over the red box, notice the value is still 1. Same goes for the middle button. Workaround is to store the "which" value on a mousedown and use that value. This is inconvenient though.

https://jsbin.com/zibalaq/edit?html,js,console,output

**Comment by dmethvin** [comment] 2022-11-21 12:51
I don't see that `event.which` is documented as being returned by a mouseover event. https://api.jquery.com/event.which/#event-which1

Is there some native property that gives you the button that's down?

**Comment by chopin2256** [comment] 2022-11-21 13:32
If you [look here](https://developer.mozilla.org/en-US/docs/Web/API/Element/mousedown_event) you can see (MouseEvent.buttons) would be the equivalent. event.buttons actually does produce the corresponding mouse click values (just different numbers from Chrome), it just doesn't appear to be mapped correctly in JQuery. JQuery is supposed to normalize these values so they are the same across the board (that's why I am using JQuery for my app).

I use the mouseover event a lot for my application, and it is crucial to capture which button is being pressed while clicking. Otherwise unpredictable things start occurring in FF while Chrome is fine. The workaround would be to create a global variable for the mousedown event, so when the mousedown is fired, you store the mousedata for later use when there is a mouseover event.

So I do think this is a bug.

**Comment by chopin2256** [comment] 2022-11-21 13:45
The problem with using the global variable trick is that it **only** works if you rely on a mouse click. There's actually an instance in my application where I rely on the "no mouse down" event while doing a mouse move (because I don't want to trigger something while there is a click), and I actually have no solution for that other than to create my own implementation to normalize the mouse events. I'm trying to avoid doing that, and I really hope a fix can be applied!

**Comment by chopin2256** [comment] 2022-11-23 21:37
### References
- First, we need to register a function in JQuery to recognize [the browser type](https://stackoverflow.com/questions/9847580/how-to-detect-safari-chrome-ie-firefox-and-opera-browsers).
- Next, we need to create an [event extension](https://learn.jquery.com/events/event-extensions/).

### Temporary Solution
I tried looking in the JQuery source code but I can't find where the "which" values are normalized. So I created an event extension for now. This should give a better idea on what the problem is. I can verify that this event extension fixes the bug. It saves my application in Firefox, and I don't have to alter any of my source code with this temporary solution.

```
jQuery.event.special.mousemove = {
    delegateType: "mousemove",
    bindType: "mousemove",
    handle: function (event) {
        var handleObj = event.handleObj;
        var ret = null;

        event.type = handleObj.origType;

        /**
         * Remap Firefox mousemove event until JQuery fix is applied (if ever)
         */
        if ($.browser == "Firefox") {
            switch (event.buttons) {
                // No click
                case 0:
                    event.which = 0
                    break

                // Left click
                case 1:
                    event.which = 1
                    break
                
                // Right click
                case 2:
                    event.which = 3
                    break

                // Middle click                    
                case 4:
                    event.which = 2
                    break
            }
        }

        ret = handleObj.handler.apply(this, arguments);
        event.type = handleObj.type;

        return ret;
    }
};
```

**Comment by wenz** [comment] 2022-11-24 13:20
I don't believe the 'which' values are normalized - converting your code to Vanilla JS produces the same behavior (the 'which' property is always 1). But might indeed be interesting to have this feature.

**Comment by chopin2256** [comment] 2022-11-24 13:42
It could be because ```$.browser``` does not exist and I didn't provide the code for it in my post for brevity purposes. This is my implementation for ```$.browser```, taken from the Stackoverflow solution. Now, mouseover should give the proper which values in Firefox:

```
jQuery.extend({
    /**
     * The detected browser (Client side only code)
     */
    get browser() {
        let firstLine = () => {
            // @ts-ignore Opera 8.0+
            var isOpera = (!!window.opr && !!opr.addons) || !!window.opera || navigator.userAgent.indexOf(' OPR/') >= 0;

            // @ts-ignore Firefox 1.0+
            var isFirefox = typeof InstallTrigger !== 'undefined';

            // @ts-ignore  Safari 3.0+ "[object HTMLElementConstructor]" 
            var isSafari = /constructor/i.test(window.HTMLElement) || (function (p) { return p.toString() === "[object SafariRemoteNotification]"; })(!window['safari'] || (typeof safari !== 'undefined' && window['safari'].pushNotification));

            // @ts-ignore  Internet Explorer 6-11
            var isIE = /*@cc_on!@*/false || !!document.documentMode;

            // @ts-ignore  Edge 20+
            var isEdge = !isIE && !!window.StyleMedia;

            // @ts-ignore  Chrome 1 - 79
            var isChrome = !!window.chrome && (!!window.chrome.webstore || !!window.chrome.runtime);

            // @ts-ignore  Edge (based on chromium) detection
            var isEdgeChromium = isChrome && (navigator.userAgent.indexOf("Edg") != -1);

            // @ts-ignore  Blink engine detection
            var isBlink = (isChrome || isOpera) && !!window.CSS;

            if (isOpera) { return "Opera" }
            if (isFirefox) { return "Firefox" }
            if (isSafari) { return "Safari" }
            if (isIE) { return "IE" }
            if (isEdge) { return "Edge" }
            if (isChrome) { return "Chrome" }
            if (isEdgeChromium) { return "EdgeChromium" }
            if (isBlink) { return "Blink" }
        }

        let secondLine = () => {
            let userAgentString = window.navigator.userAgent
            // Detect Chrome
            let isChrome = userAgentString.indexOf("Chrome") > -1;

            // Detect Internet Explorer
            let isIE = userAgentString.indexOf("MSIE") > -1 ||
                userAgentString.indexOf("rv:") > -1;

            // Detect Firefox
            let isFirefox = userAgentString.indexOf("Firefox") > -1;

            // Detect Safari
            let isSafari = userAgentString.indexOf("Safari") > -1;

            // Discard Safari since it also matches Chrome
            if ((isChrome) && (isSafari)) isSafari = false;

            // Detect Opera
            let isOpera = userAgentString.indexOf("OP") > -1;

            // Discard Chrome since it also matches Opera		
            if ((isChrome) && (isOpera)) isChrome = false;

            if (isOpera) { return "Opera" }
            if (isFirefox) { return "Firefox" }
            if (isSafari) { return "Safari" }
            if (isIE) { return "IE" }
            if (isChrome) { return "Chrome" }
        }

        /**
         * First Line of defense concat with Second Line of defense
         * Remove nulls
         * Take the first element of the array if applicable
         */
        let browserCheck: Array<Struct.Types.Browser> = [firstLine(), secondLine()]
        let b: Struct.Types.Browser = browserCheck.filter(x => x)[0]
        return b
    }
})
```

**Comment by wenz** [comment] 2022-11-24 13:49
Not using your plugin - I was just looking at the jsbin which works the same with both jQuery and without, thus I don't think normalization may be found.

**Comment by chopin2256** [comment] 2022-11-24 14:29
This is why I was confused too, I couldn't find the code where  normalization happens. But I can verify at least in Chrome, that the _buttons_ values are different from the _which_ values, which I am assuming JQuery is performing this normalization somewhere.

**No Click**
Buttons: 0, Which: 0

**Left Click**
Buttons: 1, Which: 1

**Middle Click**
Buttons: 4,  Which: 2

**Right Click**
Buttons: 2, Which: 3

**Comment by dmethvin** [comment] 2022-11-24 18:17
The `which` property is set up [here](https://github.com/jquery/jquery/blob/4c1171f2ed62584211250df0af8302d34c04621a/src/event.js#L723) which basically just lets jQuery lazy-retrieve it when needed (see [addProp](https://github.com/jquery/jquery/blob/4c1171f2ed62584211250df0af8302d34c04621a/src/event.js#L408-L434)). 

There isn't any normalization of this property because up until this report all supported browsers returned correct values. The [Mozilla docs](https://developer.mozilla.org/en-US/docs/Web/API/UIEvent/which) indicate that `event.which` is deprecated, so perhaps Mozilla no longer is returning valid data in some situations. I'd call that a bad compat choice on their part, and you could report a bug if they're the only ones that have bad values, but the property _is_ deprecated and they have documented this very bug in the "Compatibility Table" section (click the * in the Firefox cell).

For "new" code (like, written in the past 10 years or so that `event.button` and `event.buttons` have been in modern browsers) it would be best to use those instead.

**Comment by chopin2256** [comment] 2022-11-24 19:05
I just converted which -> buttons and I'm definitely having issues, so I reverted back to using "which". I don't think you should deprecate this property because not all the browsers are playing nice. One example is the middle click on a mouseup event. I did not get a value of 4, but instead a value of 2. JQuery which saves the application, but using button or buttons royally screws up my cross platform compatibility.

If you decide to not support which, I will most likely have to create my own implementation for my application [Music Jotter](https://www.musicjotter.com). My app would really put jQuery to the test because it relies heavily on mouse events and keypresses. And it would be imperative to have events all behave the same since I would be selling the product as a cross platform application on the web.

**Comment by dmethvin** [comment] 2022-11-24 19:22
> I don't think you should deprecate this property because not all the browsers are playing nice.

jQuery hasn't deprecated this property, the browsers have done it. In jQuery 3 and 4 we just pass through what the browser gives us. If the browser `which` value is wrong, we would need some other reliable source of information to be able to synthesize a correct `which` value. That would usually be `button` or `buttons` I'd think?

> One example is the middle click on a mouseup event in Chrome. I did not get a value of 4, but instead a value of 2.

That sounds like a bug in Chrome. You should report it to them and include a test case. If you can put a link to the bug report here that would be great.

**Comment by chopin2256** [comment] 2022-11-24 19:56
Ok I understand what the issues are. I don't think its a browser bug, just a nuance of the button and buttons property. _buttons_ itself does not seem to get triggered on a mouseup event, but _button_ does.

However, _button_ has different values than _buttons_, which is what confused me. I'll just have to be mindful of when to use _button_ vs _buttons_

### See this gem here

**Button values - triggered on mouseup**
left click = 0
middle click = 1
right click = 2

**Buttons values - everything else except a mouseup?**
no click = 0
left click = 1
middle click = 4
right click = 2

The reason why I can't just use _button_ for everything is because I need to know when the user _is not pressing_ a button when combining with a mouseover event. And left click = 0 in _button_ to make things even more confusing!

**Comment by mgol** [comment] 2022-11-24 20:27
@dmethvin 
> jQuery hasn't deprecated this property, the browsers have done it. In jQuery 3 and 4 we just pass through what the browser gives us.

To be precise, we used to shim in jQuery <3.6.0 before this PR landed: #4765.

However, that shim only applied when native `which` didn’t exist or was false. I’d expect jQuery 3.5.1 to behave just like 3.6.1 (or the Git version) here but feel free to check.

**Comment by mgol** [comment] 2022-12-19 22:01
We're considering re-adding the shim that we removed but without the logic falling back to the native property to make it consistent between browsers.

**Comment by mgol** [comment] 2023-02-13 14:12
I tested a slightly modified test case (to prevent default on some events that would e.g. cause the context menu to appear) and when right-clicking, I actually see `3` logged in Firefox. It's just that when no button is pressed, `1` is logged, just like with left button pressed.

JS Bin: https://jsbin.com/guzuqux/1/edit?html,js,console,output

**Comment by mgol** [comment] 2023-02-13 14:35
I tested a slightly modified test case (to prevent default on some events that would e.g. cause the context menu to appear, and also to log `button` & `buttons` values) and when right-clicking, I actually see `3` logged in Firefox. It's just that when no button is pressed, `1` is logged, just like with left button pressed.

JS Bin: https://jsbin.com/cuwaxaw/1/edit?html,js,console

You may notice `event.button` has the same problems in Firefox as `event.which`. This seems to be working as designed, though; see the note at https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/button:
> This property only guarantees to indicate which buttons are pressed during events caused by pressing or releasing one or multiple buttons. As such, it is not reliable for events such as [mouseenter](https://developer.mozilla.org/en-US/docs/Web/API/Element/mouseenter_event), [mouseleave](https://developer.mozilla.org/en-US/docs/Web/API/Element/mouseleave_event), [mouseover](https://developer.mozilla.org/en-US/docs/Web/API/Element/mouseover_event), [mouseout](https://developer.mozilla.org/en-US/docs/Web/API/Element/mouseout_event), or [mousemove](https://developer.mozilla.org/en-US/docs/Web/API/Element/mousemove_event).

If you want to have access to information about all the pressed buttons, you need to use `event.buttons`. The original `event.which` shim relied on `event.button` so it would *not* help here.

We could use `event.buttons` then, couldn't we? The problem is: what if multiple mouse buttons are pressed at the same time? We don't know which one to return then. In events like `mousedown` we should return the one that triggered the event, not the one that was already pressed before.

Therefore, it seems to me there's no way to workaround this issue in jQuery. If you need to have buttons data available in an event like `mousemove`, you need to read `event.buttons` and parse out the data for the button you're interested in.

**Comment by timmywil** [comment] 2023-02-20 17:49
We discussed in the meeting. I don't think there's anything we can do here.

**Closed by timmywil** 2023-02-20 17:49 UTC
Labels: Event
