### ISSUE TITLE
Can't use async functions in callbacks

### ISSUE THREAD

**Issue by adrian17** [jquery/jquery#3631] opened 2017-04-18 08:54 UTC
function f1(){ console.log(1); };
	async function f2(){ console.log(1); };
	typeof f2 // "function"
	$(f1); // works
	$(f2); // doesn't work
	$(() => f2()); // walkaround

According to documentation, `jQuery.ready` takes a `Function`, and according to documentation, `The type of a function is "function"`.
Since this seems to be caused by `$.isFunction` implementation, it's probably related to https://github.com/jquery/api.jquery.com/issues/1034 .

**Comment by Florian-R** [comment] 2017-04-18 09:18
@adrian17 There's already a PR for this : #3617

**Comment by adrian17** [comment] 2017-04-18 09:55
Okay.

**Comment by mgol** [comment] 2017-04-18 11:37
Closing as a duplicate of #3596.

**Closed by mgol** 2017-04-18 11:37 UTC
