### ISSUE TITLE
Firefox throws error in Sizzle due to XHTML violation in feature check

### ISSUE THREAD

**Issue by herbalite** [jquery/jquery#1969] opened 2014-12-25 05:01 UTC
Under circumstances, that I have not yet been able to reproduce as a simple test case Firefox 34 throws a system error. 

In Firebug I get the following error output. The invisible char in the output below (after select id="sizzle1419480912644-`invisible char`" is in fact a line feed shown by Firebug.

```javascript
...4'></a><select id='sizzle1419480912644-]' msallowcapture=''><option selected=''...
```
malformed input

From the popup over the error code my guestimate it is an issue of mix between XHTML and HTML tags.
As the in the popup over the error line the link reads

```javascript
<html xmlns="http://www.w3.org/1999/xhtml"><div xmlns="http://www.w3.org/1999/xhtml"><a id="sizzle1419480912644"></a><select id='sizzle1419480912644-]' msallowcapture=''><option selected=''...
```
So there's the switch from xhtml to html
The source code for 2.1.3 for this issue is found on line 1176 and has the following code

```javascript
				"<select id='" + expando + "-\f]' msallowcapture=''>" +
```

That code changed from 2.1.1. to 2.1.3 and the issue it seems to be that -\f is being interpreted by Firefox as a line feed and trips up Firefox. With other browsers I don't see this issue. The issue is also present in the minified version.

Except for the showing in the debugger however the page appears to work fine. So for me it's not a show stopper, but a step backwards from 2.1.1

**Comment by dmethvin** [comment] 2015-01-05 17:49
This will be fixed when we merge the latest sizzle.

**Comment by pmorch** [comment] 2015-12-01 13:33
I interpret the `Closed` status and Milestone 3.0.0 as: "It won't get fixed in 2.X but it'll be fixed in 3.0 when it releases" - but that there isn't a supported version with this fix in now.

For the next person to google this, I was using jqGrid when I noticed the "not well-formed" in the console after an upgrade to jQuery 2.1.4. Not to be confused with other threads of people using jqGrid with actual malformed XML. (Coincidentally(?), the OP @herbalite is a contributor to [free-jqgrid](https://github.com/free-jqgrid/jqGrid)).

Also for the next person to google this, issue #2196 has a link to a [fiddle](http://jsfiddle.net/spknpd92/) that simply reproduces the problem.

I also verifyied that https://github.com/jquery/sizzle/commit/50ebe1a43c0842f33ce363259f1a9eed236aca19 fixed the problem for me too, by applying that patch manually to 2.1.4.

**Comment by dmethvin** [comment] 2015-12-01 14:22
I'm pretty sure this will be in the 1.12.0/2.2.0 release that we plan to do later this month, since it was in the Sizzle update. @gibson042 can you confirm that's the case and update the milestone if so?

**Comment by gibson042** [comment] 2015-12-02 02:21
Confirmed.

**Closed by gibson042** 2015-12-02 02:21 UTC
Labels: Awaiting Sizzle Update, Selector

**Comment by thdoan** [comment] 2018-05-31 09:38
Hi, I arrived at this issue because I'm getting the same error in Chrome v66 on a page that uses jQuery 2.2.4 and the WYMeditor plugin. There's a way to reproduce this error almost every time in a very specific case: using a mutation observer that contains `document.querySelector('[for="' + elAdded.id + '"]')`.

I've uploaded a test page here:
http://www.tohodo.com/tests/1.html

You should see this error in the console:
![image](https://user-images.githubusercontent.com/4110567/40774349-31e95c4c-647a-11e8-99a5-4404f0091f4d.png)

The problem is, it appears, for a very brief moment a temporary element is created with an id that ends in a newline + backslash, which when used in a string concatenation operation would be malformed since the compiler thinks we're trying to escape the closing double quote.

**Comment by dmethvin** [comment] 2018-05-31 13:59
@thdoan If you can reproduce that using http://code.jquery.com/jquery-git.js then report a new issue. Otherwise it's been fixed in the past and you should upgrade.

**Comment by thdoan** [comment] 2018-06-01 03:51
WYMeditor doesn't support jQuery 3.x, but thanks I've managed to avoid this rare scenario for the time being.
