### ISSUE TITLE
upgrade from 3.4.1 to 3.5.1 html func execute different

### ISSUE THREAD

**Issue by EmiyaKiritsuguZz** [jquery/jquery#4720] opened 2020-05-25 03:02 UTC
### Description ###
When I upgrade, the div element at the same level will move to the previous div element.

![3 5 0](https://user-images.githubusercontent.com/49976248/82774358-35417300-9e77-11ea-909b-d8d3e13f60ce.png)
![3 4 1](https://user-images.githubusercontent.com/49976248/82774361-370b3680-9e77-11ea-8f66-dde21ae288f1.png)
![code](https://user-images.githubusercontent.com/49976248/82774365-383c6380-9e77-11ea-9b8d-78ab2b7d21f0.png)

**Comment by mgol** [comment] 2020-05-25 06:51
Please read the [jQuery 3.5.0 blog post](https://blog.jquery.com/2020/04/10/jquery-3-5-0-released/) & the [upgrade guide](https://jquery.com/upgrade-guide/3.5/). Also, this is a duplicate of #4681, #4693, #4709 & #4710.

**Closed by mgol** 2020-05-25 06:51 UTC

**Comment by EmiyaKiritsuguZz** [comment] 2020-05-25 11:13
Thank you for your response
