### ISSUE TITLE
Support for cross domain Patch requests using IE10 - IE11 broke between 1.10.2 and 1.11.1

### ISSUE THREAD

**Issue by vert5** [jquery/jquery#2068] opened 2015-02-06 21:19 UTC
jQuery versions 1.6.0 - 1.10.2 provided support for making cross domain Patch requests in IE10 and IE11 using the jQuery.ajax() method (assuming all client and server settings are configured correctly for CORS). 

That support broke beginning with jQuery 1.11.1-rc1. A properly configured ajax request in IE10/11 now fails with "Error: Could not complete the operation due to error 8070000c." Stepping through the relevant jQuery code shows the underlying error being thrown as -2146828218, "Permission denied".

The breaking change appears to be occurring in the newly added condition "/^(get|post|head|put|delete|options)$/i.test( this.type ) &&" where the code is determining which type of xhr object to use.

A complete description including code snippets can be found at https://forum.jquery.com/topic/workaround-for-break-in-ie10-11-cross-domain-patch-support. 

I would be happy to provide a jsFiddle link showing 1.10.2 vs 1.11.1 support if that link can be shared privately.

Regards,

John

**Comment by vert5** [comment] 2015-02-07 00:23
I've posted a fiddle at http://jsfiddle.net/g5eog7t8/3/.

The fiddle loads with jQuery 1.6.4 by default. When it runs you'll see the result "PATCH verb - Success".

If you step through the versions of jQuery from 1.6.4 to 1.11.0 using IE you'll find that it works on all versions until 1.11.0. At that point you'll see some Fail detail. The error that appears in jsFiddle is different from what's reported above, perhaps due to some jsFiddle overhead. If you copy the code into an html page and run it directly using IE10 or 11 (without running it through jsFiddle), you'll see the error that was reported.

**Comment by markelog** [comment] 2015-02-11 20:22
Thank you for detailed issue. 

Will try to make a fix for 3.0.

**Comment by mzgol** [comment] 2015-06-25 01:19
This has been fixed by 61f812b7e7b88dd6e0078c241e4c88905ea51562 & bd699cb17b6347a414c0c6d105ef80a4ea1ed678 and will be available in jQuery Compat 3.0.0.

**Comment by mzgol** [comment] 2015-06-25 01:19
In other words, this issue is a duplicate of #1684.

**Closed by mzgol** 2015-06-25 01:19 UTC
Labels: Ajax, compat-only

**Comment by mzgol** [comment] 2015-06-25 01:20
A relevant fiddle confirming that it works: http://jsfiddle.net/g5eog7t8/11/ (I just changed the jQuery version to "jQuery Compat (edge)")

**Comment by vert5** [comment] 2015-06-26 16:31
Thanks, mzgol. Just accessed the fiddle and saw it's working. Appreciate the support.

**Comment by flatman** [comment] 2015-10-14 18:22
Is there any specific reason why this won't be fixed in jQuery 1?

**Comment by mzgol** [comment] 2015-10-14 18:50
@flatman There are a lot fixes people would like to have in jQuery 1, backporting them all would really constitute a new release anyway. Also, there's always a possibility that the fix to this issue breaks something for someone else, this is a critical piece of logic.

We don't currently plan any new jQuery 1.x or 2.x releases. You can test [jQuery Compat 3.0.0 alpha1](https://code.jquery.com/jquery-compat-3.0.0-alpha1.js) if you need IE8 support.
