### ISSUE TITLE
floating point missing in width()

### ISSUE THREAD

**Issue by Tomas-M** [jquery/jquery#2593] opened 2015-09-14 09:50 UTC
Some element, lets call it EL1, may have real width as floating point number, for example if the element's width is set by CSS as 25% of parent element which is 345px - our EL1 will have 86.25px width.

When I want to set another element, lets call it EL2, to be the same width as EL1, I can use $(el2).width(el1.width());

However, jquery's width() function returns integer instead of floating point number. Jquery rounds the width. In most cases this is not any problem, but I noticed that sometimes, when the EL1 width is some particular fraction, jquery returns a number which results in EL2 rendeded one pixel off compared to  EL1.

Can be jquery made that it returns floating point widths, as like the browser internally uses, in order to get consistent results all the time? Because if browser accepts floating point widths, but jquery rounds it, it sometimes leads to wrong behavior.

**Comment by mzgol** [comment] 2015-09-14 10:42
Dupe of #1724. Please always test on the newest development copy of jQuery (https://code.jquery.com/jquery-git.js) to make sure the bug still exists.

**Closed by mzgol** 2015-09-14 10:42 UTC
