### ISSUE TITLE
jQuery 1.11.2 Sizzle generates a “not well-formed” error

### ISSUE THREAD

**Issue by AlexisWilke** [jquery/jquery#2054] opened 2015-02-02 22:06 UTC
My scripts work just fine with 1.11.0, when I upgraded to 1.11.2 I get this error which is rather cryptic to me:

    not well-formed
    ...3'></a><select id='sizzle1422660976293-]' msallowcapture=''><option selected=''...
    -------------------------------------------^

Note that I'm running with SeaMonkey 2.25 which is similar to Firefox (it uses the exact same JavaScript engine.) I'm not too sure at which version it is, but really not that far off.

It feels like the interpreter does not like the value of the identifier which ends with a ']' so definitively seem like a not so good identifier.

I'm wondering if that occurs because of something I do slightly wrong somewhere, or whether Sizzle wrongly generates an invalid identifier and I have no control over it... Thus far this does not seem to prevent my scripts from working (at least), because it happens on cleanup (variable garbage collection).

It particularly seems to be happening when dealing with an XML document, opposed to a standard HTML DOM. jsFiddle offers jQuery 1.11.0, not 1.11.2, but you can specify a JS store so I use Google's version, there is the fiddle URL:

http://jsfiddle.net/m2ewycnm/

**Comment by gibson042** [comment] 2015-02-02 22:14
This looks like a duplicate of #1969 (jquery/sizzle#304), which is harmless but already [fixed upstream](https://github.com/jquery/sizzle/commit/50ebe1a43c0842f33ce363259f1a9eed236aca19) and will be resolved with the next jQuery release.

**Closed by gibson042** 2015-02-02 22:14 UTC
