### ISSUE TITLE
isArraylike

### ISSUE THREAD

**Issue by mhbseal** [jquery/jquery#2238] opened 2015-04-28 08:16 UTC
if ( obj.nodeType === 1 && length ) {
		return true;
	}

this is not useful, because nodeList  has no nodeType.

**Comment by markelog** [comment] 2015-04-28 08:28
Indeed, removing these lines doesn't break (including FF) any tests, was added in 3c7f2af81d877b24a5e5b6488e78621fcf96b265

Issues exist in FF 19 but it's no longer reproducible in modern browsers. Would you like to sends us a PR?

/cc @rwaldron

**Comment by gibson042** [comment] 2015-04-28 14:36
The code still acts as a defense against form aliasing: http://jsfiddle.net/Lz0k4bn4/

We can either drop support or add a unit test.

**Comment by dmethvin** [comment] 2015-04-28 15:01
Is this change fixing a bug, or removing a feature? :smiling_imp:  The `length` variable in that aliased test case is an `HTMLInputElement` so you couldn't use the form element as an arraylike object to iterate over its `element` collection.

**Comment by gibson042** [comment] 2015-04-28 15:09
> The `length` variable in that aliased test case is an `HTMLInputElement` so you couldn't use the form element as an arraylike object to iterate over its `element` collection.

Nuh-uh: http://jsfiddle.net/Lz0k4bn4/1/ (check the console)

**Comment by dmethvin** [comment] 2015-04-28 15:13
I must be missing something, here are some extra console logs: http://jsfiddle.net/Lz0k4bn4/2/

**Comment by markelog** [comment] 2015-04-28 15:14
Never supported this usage, in fact, we have always closed issues like that, see the most recent <a href="http://bugs.jquery.com/ticket/10909">one</a>

**Comment by dmethvin** [comment] 2015-04-28 15:47
I agree, we have been closing them not because we are happy with having this bug, but because the aliasing problem is too hard to solve.

**Comment by timmywil** [comment] 2015-04-28 17:47
I'm fine with removing it.

**Comment by gibson042** [comment] 2015-04-29 18:04
Working around form aliasing is hard, especially in the general case, but it is possible for [`length`](https://github.com/jquery/sizzle/commit/f6e2fc59dd971910db666cbece0f743aa111c4f5#diff-7d34356c0b7229dd5da8b6c7711b32b7R1734) (and also `nodeType` and `nodeName`, for that matter). I'm fine if we don't, but it merits a [wont-fix](http://contribute.jquery.org/wont-fix/) mention analogous to `Object.prototype` manipulation.

**Closed** 2015-05-05 17:22 UTC
Labels: Core
