### ISSUE TITLE
The .html method makes the past string of html show up in the wrong order

### ISSUE THREAD

**Issue by frastlin** [jquery/jquery#3468] opened 2016-12-22 21:05 UTC
Hello,
I am passing a string to the .html function and the html that shows up on the page is not in the order that I have it in the string. On the rendered html page the button is at the very top of the page when it should be at the very bottom of the page. I had the .innerHTML equal the string and everything worked just fine.
My guess is it has something to do with es6 strings, but I have used s6 strings before and there didn't seem to be any problem. Here is the code:

	<!DOCTYPE html>
	<html><head>
	<title>file upload test</title>
	</head>
	<body>
	
	<div id="body"></div>
	
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
	<script>
	
	var page_content = `
	<h1>Please select a csv file to import</h1>
	<input id="f" type="file" multiple=false>
	<input type=text" id="bank_choice" list="bank_list">
	<datalist id="bank_list">
	</datalist>
	<button id="b1">Start Import</button>
	`
	
	//not working
	$("#body").html(page_content)
	
	//working
	//document.getElementById("body").innerHTML = page_content
	
	</script>
	</body>
	</html>

**Comment by mgol** [comment] 2016-12-23 01:18
Thanks for the report. In the future, please post test cases on jsfiddle.net or jsbin.com so we can immediately see how they work.

However, I can't reproduce the problem: https://jsfiddle.net/wqLw0knz/2/; both methods give identical results.

I'm going to close this issue then but if you can tweak that test case to show the bug you have we can reopen.

**Closed by mgol** 2016-12-23 01:18 UTC
