### ISSUE TITLE
Manipulation of handlers: jQuery vs Native

### ISSUE THREAD

**Issue by xoxulin** [jquery/jquery#2314] opened 2015-05-14 11:14 UTC
http://codepen.io/xoxulin/pen/QbNrGe?editors=101 - it's demonstration of different behaviours of on/off methods of jQuery and add/removeEventListener of Native JS.

Native way is more expectable. I think that it's jQuery bug. Isn't so?

PS: I checked it in 1.8.3 and 2.1.3 - both version with bug.

**Comment by mzgol** [comment] 2015-05-14 11:16
Dupe of #2313.

**Closed by mzgol** 2015-05-14 11:16 UTC

**Comment by xoxulin** [comment] 2015-05-14 11:29
@mzgol Ok, but `e.stopImmediatePropagation();` is not true solution. Because my click event must be handled by next listeners http://codepen.io/xoxulin/pen/xGVjzP?editors=101

**Comment by mzgol** [comment] 2015-05-14 11:33
Actually, it's a dup of #2094. Please comment there if you want it to get reopened, let's avoid spreading the same discussion accross multiple issues.
