### ISSUE TITLE
click() not return $ but Window obj

### ISSUE THREAD

**Issue by lehmannwebdev** [jquery/jquery#2896] opened 2016-02-04 09:55 UTC
In jq 2.1.4 $('a').click() returned $('a') and I can do: 

$('a')
    .click(fn1)
    .click(fn2)
;

Now in 2.2.0 $('a') return Window object and I can't do it.

Is it a bug or feature?

**Comment by mgol** [comment] 2016-02-04 10:00
This works for me on simple examples (please always provide a test case on a site where we can run it like https://jsfiddle.net or https://jsbin.com) so I'm going to assume it's a duplicate of #2812. You may check if it works for you with https://code.jquery.com/jquery-2.x-git.js (don't put this development version in production, though!) and if it doesn't, please provide a *complete* test case. If it does, just wait for jQuery 2.2.1.

**Closed by mgol** 2016-02-04 10:00 UTC

**Comment by lehmannwebdev** [comment] 2016-02-04 11:23
I found problem.

In 2.1.4 if fn1 doesn't exists jq returned $('a') but in 2.2.0 it return window obj.

**Comment by mgol** [comment] 2016-02-04 11:56
Yeah, that's definitely #2812 then. It will be fixed in jQuery 2.2.1.
