### ISSUE TITLE
position() function reports incorrect left offset under Chrome

### ISSUE THREAD

**Issue by ReimuYome** [jquery/jquery#2237] opened 2015-04-27 14:56 UTC
Test this
https://jsfiddle.net/Reimu/yu3c361g/2/
under Chrome and other browsers, you will see the <code>left</code> offset reported by <code>position()</code> method is incorrect under Chrome.

The value of  <code>left</code> offset under Chrome is the gap between &lt;html&gt; and &lt;body&gt;, not the real left offset of the horizontally centered &lt;div&gt;. 

This problem relates only with horizontally centered &lt;div&gt;s, and can be fixed by calculating manually with the <code>marginLeft</code> value of the element's computed style and the gap between &lt;html&gt; and &lt;body&gt;.

Maybe this is due to a possible bug / design choice of Chrome, as there are also some discussion about it on StackOverflow. But I think jQuery is supposed to deal with such difference between browsers.

**Comment by alburthoffman** [comment] 2015-04-28 10:31
position() does not include the margins. For me, it's kind of reasonable. Because margin is part of the element. For ur example, the victim div locates at left 8px and top 158px, but it has 160.5px left margin and 0px top margin. So the border of it has 168.5px from the left and 158px from the top.

Since you are not asking for position of the border of victim, so ......

**Comment by ReimuYome** [comment] 2015-04-28 13:59
@alburthoffman  Thank you for your explanation. Though still my concern is  the different behaviors of this method under different browser.

In my view, when using jQuery I shall be exempt of caring for what browser I am facing. As the behavior of this method shows asymmetry and it is not mentioned in the API documentation.

For this very case, I can obtain the correct result after switching to <code>offset</code> method. But that method has its own semantics and the act of switching itself shows some compatibility concern.

My suggestion is this method reporting same value under same browsers. Either subtracting margin value under Chrome, or follow the Chrome way in all cases.

**Comment by dmethvin** [comment] 2015-04-28 14:12
To report the same value though, we'd need to ignore the margin on the body in Chrome. There really is a margin on the body in Chrome: https://jsfiddle.net/yu3c361g/4/  So how do we rationalize ignoring a value set in CSS?

**Comment by alburthoffman** [comment] 2015-04-28 14:55
This depends on browsers. I tested it in chrome 41 and safari. And they are the same. But in firefox, the left value is different, because the marginLeft is set to 0 in it. 

So it will require lots of browser version checking in this function if it has to return a same value.

**Comment by dmethvin** [comment] 2015-04-28 15:12
It seems like the way most pages would fix this is through a CSS reset or normalize? It seems consistent in Firefox for me BTW.

**Comment by ReimuYome** [comment] 2015-04-28 22:50
@alburthoffman  I think this is because they are all web-kit based, so I guess checking for the phrase 'Web-Kit' in navigator.userAgent is enough ?

@dmethvin It is my honor to have an official reply from you. 
As you have mentioned, the problem is Chrome-only. But the margin to be ignored is set by Chrome, not the user.

It comes as a side effect of "margin:0 auto", which browsers like Firefox interprets as directly horizontally center the div, while Chrome by calculating the margin left. If I drop "margin:0 auto" and give a concrete left margin to the div, in both Firefox and Chrome <code>position<code> reports the same 8px left offset.

So is it possible to overload the <code>position<code> method. For example, when I call <code>position(false)</code>, it will ignore the margin totally and reports the left offset of the left border ?

After all, as you can see in this case, the left offset I want to know is definitely the gap from the left border of the div to the left boundary of page, excluding any margin.

**Comment by dmethvin** [comment] 2015-04-29 01:41
What I was suggesting is that if you set the margin to zero in all browsers it works fine: https://jsfiddle.net/yu3c361g/8/

**Comment by gibson042** [comment] 2015-04-29 02:19
@dmethvin I still see a discrepancy when the result pane is sufficiently wide, even with your latest fiddle. There is a bug here, but it's [in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=381328) and we've marked it "cantfix" on our side at least twice before: [trac-11110](http://bugs.jquery.com/ticket/11110#comment:9) and [trac-11813](http://bugs.jquery.com/ticket/11813#comment:3).

**Comment by alburthoffman** [comment] 2015-04-29 04:21
It cannot be fixed in Firefox. It was caused by window.getComputedStyle() in FF. This function doesnot return caculated margins when margins are set to auto. 

One problem is to find a way to check if margins are set to auto or not in FF. No clues right now.....

**Comment by gibson042** [comment] 2015-04-29 17:02
This _is_ fixable with another "awesome hack"-style swap, but it might be big: https://jsfiddle.net/yu3c361g/9/

...and if we do it right (with `jQuery.cssHooks` instead of in `.position`), then it may get even bigger and almost certainly slower (from multiple reflows).

**Comment by alburthoffman** [comment] 2015-04-30 04:24
Awesome!

Just curious about the swap part. why does it need to check marginTop? when marginTop is auto, then it should be 0px, right?

**Comment by gibson042** [comment] 2015-04-30 13:08
Yes, of course. I just got carried away with the copypasta.

**Comment by timmywil** [comment] 2015-04-30 14:00
I guess I'd be in favor of aligning the behavior. The swap is unfortunate, but we can limit its usage to this one case.

**Comment by alburthoffman** [comment] 2015-04-30 14:28
Also, support_marginAuto can be calculated when jQuery starts, don't need to test it every time position is called.

**Closed** 2015-10-18 21:01 UTC
Labels: Bug, Has Pull Request, Offset
