### ISSUE TITLE
Crashing when running a selector with unquoted attribute-value

### ISSUE THREAD

**Issue by SimonSimCity** [jquery/jquery#3079] opened 2016-04-26 07:52 UTC
**Description**

JavaScript crashes when running jQuery using a selector like `jQuery("a[href*=#]:not([href=#])")`.

It works when enquoting the attribute-value like `jQuery('a[href*="#"]:not([href="#"])')` or when switching back to an older minor release.

**Affected versions**

The example failed in 1.12.x and 2.2.x but works on 1.11.x or 2.1.x

Tried in Firefox 45.0.2 and Google Chrome 50.0.2661.86 (64-bit) but also other users on IRC confirmed it.

**Link to test case**

* Failing test: https://jsfiddle.net/uuf8ppob/1/
* Passing test: https://jsfiddle.net/n3a4dyrb/ (quoted attribute-value)
* Passing test: https://jsfiddle.net/uuf8ppob/ (jQuery 2.1.x)

**Comment by mgol** [comment] 2016-04-26 08:41
Please search for existing issues before reporting a new one. This is a duplicate of #2811, #2824, #2829, #2876, #2884, #2885, #3009 & #3063.

**Closed by mgol** 2016-04-26 08:41 UTC

**Comment by SimonSimCity** [comment] 2016-04-26 08:47
Thanks for the links. I should have searched before filing a new bug, true ...
