### ISSUE TITLE
Cannot create property 'guid' on string 'div'

### ISSUE THREAD

**Issue by Delucy** [jquery/jquery#4257] opened 2018-12-11 06:45 UTC
### Description ###

I have upgraded from 1.12.x to 3.x , after upgrade my application is not opening and it is giving the below error:
jQuery.Deferred exception: Cannot create property 'guid' on string 'div' TypeError: Cannot create property 'guid' on string 'div'
This is the line where it fails:
$('div.dashBoardKey').on('focus', 'div').on('keyup', 'div',function (e) {....}.find('div').first().focus();
### Link to test case ###
This Js fiddle can give better clarity:
https://jsfiddle.net/0weocdtx/

Focus is as event if i am not wrong...
Also this seems to work in other versions of Jquery, can you please suggest what needs to be used. 
You can check the console for the error am getting

**Comment by mgol** [comment] 2018-12-11 09:46
Please don’t recreate duplicate issues just because the original issue was closed. Just continue the discussion on the original issue.

This is a duplicate of #4254.

**Closed by mgol** 2018-12-11 09:46 UTC
