### ISSUE TITLE
Sending the string literal "??" in JSONified data with .ajax() results in it being replaced by garbage containing the word "jquery"

### ISSUE THREAD

**Issue by PhonicUK** [jquery/jquery#3831] opened 2017-10-29 12:09 UTC
### Description ###

When submitting a serialized object containing "??" as the value of a string inside that object, it gets replaced by different data.

I can reproduce this issue in my test case using the latest version of jQuery against the latest versions of both Firefox and Chrome with no extensions/plugins enabled.

### Link to test case ###

https://jsfiddle.net/ascfw813/

Open up the F12 developer console and open up the Network tab, and re-run the fiddle. The request shown has differing form data than in the serialized data.

https://i.imgur.com/2Rdru6t.png

**Comment by PhonicUK** [comment] 2017-10-29 13:03
The last part of the modified data after the underscore appears to be the current timestamp, suggesting this is actually part of an anti-caching mechanism (appending timestamps of course being one of the favoured techniques) gone wrong.

**Comment by dmethvin** [comment] 2017-10-29 13:42
Duplicate of #3798.

**Comment by mgol** [comment] 2017-10-29 15:10
Closing per Dave’s comment.

**Closed by mgol** 2017-10-29 15:10 UTC
