### ISSUE TITLE
addClass doesn't work on (SVG) <g> tags

### ISSUE THREAD

**Issue by warpdesign** [jquery/jquery#2241] opened 2015-04-28 14:28 UTC
Let's have the following DOM:

    <svg>
    <g id="foo">
    ...
    </g>
    </svg>

Typing `$('#foo').addClass('bar')` will do nothing. Typing `foo.classList.add('bar')`will work as expected.

This happens with:

- jQuery 2.1.3 & jQuery 2.0.3
- Chrome 42.0.2311.90 m / Windows 10 TP 10061 (64bit)

**Comment by mzgol** [comment] 2015-04-28 14:31
Duplicate of #2199

**Closed by mzgol** 2015-04-28 14:31 UTC
