### ISSUE TITLE
Unable get HTML fragment on any selector

### ISSUE THREAD

**Issue by WHK102** [jquery/jquery#4433] opened 2019-07-15 00:46 UTC
In Google Chrome (last version) and jQuery 3.4.1, using custom HTML tags, by example:

<template data-id="row"><tr><td data-text="{foo}"></td></tr></template>

I iterate all tags with data-text property for translate the data-text:

    $('[data-text]').each(function(){
        $(this).text(strings[$(this).attr('data-text')]);
    });

On all html tags works fine, but on inner custom tags is not work, but i can access to it using:

`$('template[data-id="row"]').contents().find('[data-text]')`

jQuery omit the custom tags (html fragments)?

`querySelectorAll` works fine with custom tags, but using jquery is not work:

- https://jsfiddle.net/4t4tcr3w/
- https://stackoverflow.com/questions/38159932/use-custom-tag-using-javascript-only

Tested on Firefox 68.0 and Google Chrome 75.0. The non regular tags are parts of DOM without default style and hide by default, by example:

`<x style="display: block; color:black;background-color:red;">Test</x>`

And works fine using onclick and special javascript callable events.

Its not a Javascript problem.

**Comment by dmethvin** [comment] 2019-07-15 01:47
Please provide a clear test case that shows whatever you want to do with plain js and the equivalent with jQuery. When I modify the jsfiddle it seems to work fine. https://jsfiddle.net/kwsm4g1y/

**Comment by mgol** [comment] 2019-07-23 10:07
A duplicate of #4434.

**Closed by mgol** 2019-07-23 10:07 UTC
Labels: Needs info
