### ISSUE TITLE
Run jQuery unit tests in XHTML

### ISSUE THREAD

**Issue by mgol** [jquery/jquery#1731] opened 2014-10-20 23:30 UTC
Originally reported by dmethvin at: http://bugs.jquery.com/ticket/10198
<p>
We need to run the unit tests with an XHTML doctype to ensure that everything passes.
</p><p>Issue reported for jQuery 1.6.3</p>

**Comment by anthonyryan1** [comment] 2015-07-27 22:13
With the issue of XHTML regressions coming up again, it seems like an appropriate time to revisit this.

I think the optimal course of action would be:
1. Fixing QUnit for XHTML and ensuring they start regularly testing in an XHTML mode. We can't expect to keep the XHTML tests green if our test harness keeps breaking.
2. Requiring a webserver to serve the test suite so everything can be served with appropriate headers (we can't ensure all of the various `file:///` URLs are served with the correct content-type
3. Conditionally skip based on specific criteria (in this case `if (document.contentType === 'application/xhtml+xml') { /* skip */ }`). This would be a very significant effort as each XHTML failing test would need to be manually checked to understand why it's failing. Whether it's because of how it is being used (for example, appending an unclosed tag), or because of a bug in jQuery itself.
4. Get **all** of the tests passing or skipping under XHTML. Because while people might notice the difference between 0 and 1 failure. The difference between 17 and 18 will lead to people just ignoring these failures and we'll see no fewer regressions.

**Comment by mzgol** [comment] 2015-09-14 18:39
Rescheduling to 3.0.1 as it's non-trivial and we still have a lot to do before 3.0.0.

**Comment by timmywil** [comment] 2016-01-15 17:25
Moving to [Roadmap](https://github.com/jquery/jquery/wiki/Roadmap). We're not sure when we'll get to this.

**Closed by timmywil** 2016-01-15 17:25 UTC
Labels: Build

**Comment by mgol** [comment] 2016-01-15 22:12
@timmywil When you're closing an issue while not fixing it please *always* make sure to remove a milestone, otherwise it will get picked up in a changelog totally incorrectly.

**Comment by timmywil** [comment] 2016-01-15 22:28
@mgol Good call, thanks for the reminder.
