### ISSUE TITLE
Collapse issue in 3.5.0 not in 3.4.1

### ISSUE THREAD

**Issue by MiddleSiggy** [jquery/jquery#4671] opened 2020-04-17 01:29 UTC
### Description ###

The following sample code below produces this error, which started after upgrading from jquery-3.4.1 to 3.5.0:
collapse.js:337 Uncaught TypeError: Cannot convert object to primitive value
    at RegExp.test (<anonymous>)
    at HTMLDivElement.<anonymous> (collapse.js:337)
    at Function.each (jquery-3.5.0.min.js:381)
    at jQuery.fn.init.each (jquery-3.5.0.min.js:203)
    at jQuery.fn.init._jQueryInterface [as collapse] (collapse.js:328)
    at HTMLDivElement.<anonymous> (collapse.js:374)
    at Function.each (jquery-3.5.0.min.js:381)
    at jQuery.fn.init.each (jquery-3.5.0.min.js:203)
    at HTMLButtonElement.<anonymous> (collapse.js:370)
    at HTMLDocument.dispatch (jquery-3.5.0.min.js:5431)
(anonymous) @ collapse.js:337
each @ jquery-3.5.0.min.js:381
each @ jquery-3.5.0.min.js:203
_jQueryInterface @ collapse.js:328
(anonymous) @ collapse.js:374
each @ jquery-3.5.0.min.js:381
each @ jquery-3.5.0.min.js:203
(anonymous) @ collapse.js:370
dispatch @ jquery-3.5.0.min.js:5431
elemData.handle @ jquery-3.5.0.min.js:5235

Bootstrap Version : Bootstrap v4.1.0

### Link to test case ###

`<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Untitled Document</title>
</head>
<body>
<link href="css/bootstrap.min.css" rel="stylesheet">
<script src="js/jquery-3.5.0.min.js"></script>
<script src="js/bootstrap.js"></script>
<div class='panel panel-default' style='border:1px solid black;'>
<div class='panel-heading' style=''>
<button data-toggle='collapse' data-target='#f73d0f0d78'>Show / Hide</button>&nbsp;&nbsp;&nbsp; Some Variable</div>
<div id='f73d0f0d78' class='panel-body collapse'>
<div class='row ' style='padding:0px;'>
<div class='col-xs-12'> 
<pre>'f73d0f0d78'
</pre></div>
</div> 
</div> 
</div> 
</body>
</html>`

**Comment by mgol** [comment] 2020-04-17 07:13
Thanks for the report. However, this looks like a duplicate of https://github.com/jquery/jquery/issues/4665.

**Closed by mgol** 2020-04-17 07:13 UTC
