### ISSUE TITLE
When requiring jquery from within react-native, you get an error 'document.createElement' is not defined

### ISSUE THREAD

**Issue by oveddan** [jquery/jquery#2349] opened 2015-05-26 20:04 UTC
### Problem
My use case is to use `jquery` to page scrape from within `react-native` code.   I'm using (jsdom-jscore)[https://github.com/brentvatne/jsdom-jscore] to build a document from downloaded html, then trying to pass that document to jquery to be able to parse it.

My code looks like:

```
var jquery = require('jquery');
     jsdom = require('jsdom-jscore');

var someHtmlIDownloaded = '<html><body><h1>Hello world</h1></body></html>';

jsdom.env(
    someHtmlIDownloaded,
    function (errors, window) {
      var $ = jquery(window);
      // do something with $ to parse/scrape html body.
    }
  );
```

The `require('jquery')` throws an error:
'document.createElement' is not defined

This occurs within sizzle, in the `assert(fn)` method.

### Why it happens
`react-native` creates its own global `document`, but `createElement` is not supported on this document object.   When `jquery` is loaded in this environment, because there is a global.document, it assumes document.createElement exists, and tries to attach itself to that document.  The check that passes can be found [here](https://github.com/jquery/jquery/blob/66e1b6b8d49812239b5712d65922ff94c60f7b02/src/intro.js#L25) and looks like:
```javascript
module.exports = global.document ?
			factory( global, true ) :
			function( w ) {
				if ( !w.document ) {
					throw new Error( "jQuery requires a window with a document" );
				}
				return factory( w );
			};
```
### Temp fix
I was able to fix this locally by:
Building jquery from source using command:
`grunt custom: -ajax,-ajax/jsonp,-ajax/load,-ajax/parseJSON,-ajax/parseXML,-ajax/script,-ajax/var/nonce,-ajax/var/rquery,-ajax/xhr,-manipulation/_evalUrl,-event/ajax,-css,-css/addGetHookIf,-css/curCSS,-css/defaultDisplay,-css/hiddenVisibleSelectors,-css/support,-css/swap,-css/var/cssExpand,-css/var/getStyles,-css/var/isHidden,-css/var/rmargin,-css/var/rnumnonpx,-effects,-effects/Tween,-effects/animatedSelector,-dimensions,-offset,-deprecated,-event,-event/alias,-event/support,-wrap,-deferred,-core/ready`

Altering the built jquery code to **never** assume there is a global document:
```javascript
module.exports = function( w ) {
				if ( !w.document ) {
					throw new Error( "jQuery requires a window with a document" );
				}
				return factory( w );
			};
```

And I require that custom build js in my code:
```javascript
var jquery = require('dist/jquery.js');
```

And it works!

### Actual Solution?
What is the proper way to fix this?  Should we check if the `createElement` method exists on the `document` before deciding to pass it to the factory?

**Comment by mzgol** [comment] 2015-05-26 20:13
Thanks for the report. The problem is there are many libraries shimming core APIs poorly as React Native does here. It may turn out that just checking for `document.createElement` is not enough as another library shims this one but doesn't shim some other necessary APIs... I'm not sure how to fix it properly within this factory.

Why does react-native create a **global** document that lacks such basic methods?

**Comment by vjeux** [comment] 2015-05-26 20:26
Thanks for digging through this issue. There is no good reason for react-native to have a global `document` variable with just a single key `createElement: null`. We need to remove `document` altogether, it was added as a workaround very early in the process and is not needed anymore.

**Comment by timmywil** [comment] 2015-05-26 20:28
This doesn't seem like something we can support. jQuery is a library built to work with HTML DOM and expects basic document methods to exist.

FYI, `-ajax` removes all the ajax modules in the ajax folder as well. Same goes for `-css`, `-effects`, and `-event`. That would make the custom command a lot shorter.

**Comment by timmywil** [comment] 2015-05-26 20:29
If anything, this is desired behavior. It shouldn't fail silently.

**Comment by mzgol** [comment] 2015-05-26 21:01
Ok, since @vjeux confirmed it's sth React Native should & will fix on their side, I'm going to close the issue. Thanks to everyone for input!

**Closed by mzgol** 2015-05-26 21:01 UTC

**Comment by oveddan** [comment] 2015-05-28 04:58
Thanks for the replies @mzgol @vjeux @timmywil - @vjeux are you saying that in react-native document  should no longer be needed in the global?   Is the best solution to get rid of the global document in [react-native](https://github.com/facebook/react-native)?  Should I create an issue in that repo?

**Comment by mzgol** [comment] 2015-05-28 05:58
Yes, it seems so.
