### ISSUE TITLE
jQuery 1.* IE6 XHR custom fields

### ISSUE THREAD

**Issue by Winand** [jquery/jquery#2754] opened 2015-12-04 07:12 UTC
Sorry for mentioning IE6 at all, but recently i've wanted to force ElFinder to work under IE6 (still unsuccessfully.)

The following code fails in IE6 on `xhr[ i ] = s.xhrFields[ i ]` line with something like `object doesn't support this property or method`

    // Apply custom fields if provided
    if ( s.xhrFields ) {
        for ( i in s.xhrFields ) {
            xhr[ i ] = s.xhrFields[ i ];
        }
    }

**Comment by mzgol** [comment] 2015-12-04 13:29
Could you write a little more? We run tests on IE 6 and they all pass so a basic failure would be detected pretty quickly.

We need a test case, preferably on http://jsfiddle.net/ or http://jsbin.com/

**Comment by Winand** [comment] 2015-12-04 20:56
Win10 PC with the environment set has been broken recently but i'll try to get more info ASAP

**Comment by dmethvin** [comment] 2015-12-04 21:22
We haven't seen your code, but in IE6 the XHR is an ActiveX object (not a plain JS object) and you can only set the small number of known fields the ActiveX object supports. 

We only get to the xhrFields copying code if the caller has tried to set custom fields for example for CORS or responseType, and the caller *cannot* do that for IE6. We never use xhrFields internally at least in 1.11.3, you can look at whatever version of jQuery you may be using to be sure. I do see that [ElFinder uses xhrFields](https://github.com/Studio-42/elFinder/blob/73ebcfbe891a8100c363da76c15332df3eadfa0f/js/elFinder.js#L456) for cross-domain access so you'll need to be sure that code isn't being entered. But that's outside jQuery and not in our control. Just be sure you're not passing any `xhrFields` in your `$.ajax` requests.

I'll close this since it's highly unlikely the problem is inside jQuery.

**Closed by dmethvin** 2015-12-04 21:22 UTC
Labels: Needs info

**Comment by Winand** [comment] 2015-12-05 12:04
Well, the reason why i've opened an issue is that jQuery gives exception in this case. Maybe request could fail with some clear status text? I've spent some time to understand why it fails and returns status code 0.
