### ISSUE TITLE
Workaround for animate scrollTop with overflow hidden or height set to 100vh

### ISSUE THREAD

**Issue by stevencohn** [jquery/jquery#4581] opened 2020-01-05 16:19 UTC
This is not a problem report but rather a work-around that hopefully others will find useful. There have been a couple of reports of issues animating scrollTop when either overflow is set to hidden on the html or body tags or height is set to 100hv or 100%. This was my workaround.

I have a page with background parallax effects implemented with html/body/wrapper element structure and css for the wrapper like

```css
.main-wrapper {
    height: 100vh;
    overflow-x: hidden;
    overflow-y: auto;
    perspective: 3px;
}
```

The work-around is to temporarily disable offending styles (in my case only the height style was causing problems) to enable the animation but then also explicitly setting the windows.location

```javascript
$(document).ready(function($) {

  // this is a quick hack to reset the anchor point when refreshing (F5)
  // the page, otherwise the scrolling hack below doesn't work the first time
  window.location.hash = '';

  // setting height:100vh on the main-wrapper breaks scrollTop animation
  // so this is a work-around that temporarily unsets height, animates,
  // and then resets height; but we also need to manually set the window
  // location after the animation otherwise scroll position is reset back to 0
  // when the style is reapplied
  $(".scroll").click(function(event){
  event.preventDefault();

  // clear hash otherwise clicking current #href won't work
  window.location.hash = '';
  $('#wrapper').css('height', 'auto');
  let h = this.hash;
  $('body').animate({scrollTop:$(this.hash).offset().top}, 500,
    function() {
      $('#wrapper').css('height', '100vh')
        .promise().done(() => { window.location.hash = h; })
      }
    );
  });
});
```

If there's a better solution, I would love to here it but this seems to work for me for now.

**Comment by mgol** [comment] 2020-01-27 18:41
Since - as I understand - it's not a bug report, I'm going to close it. It will still be searchable in GitHub issues.

**Closed by mgol** 2020-01-27 18:41 UTC

**Comment by raquelhortab** [comment] 2023-05-25 07:24
Could my problem be related to this?
I got this function running on an interval:

```
 function scrollContent() {
        $('body, html').animate({ scrollTop: document.documentElement.scrollHeight - window.innerHeight }, 7500).delay(5000).animate({ scrollTop:0 }, 2500);
 }

$(document).ready(function () {
  scrollContent();
  setInterval(scrollContent, 30e3);
}
```

But the first time it is called, the animation does not run. It works the second time it's called and the following. Could someone explain why is this not a bug?
