### ISSUE TITLE
i post ?? in ajax and change by the query version

### ISSUE THREAD

**Issue by kristiandamian** [jquery/jquery#2351] opened 2015-05-27 00:18 UTC
I have this simple code:
    
    Datos={}
    Datos.id=$('#cmbRegion').val();
    Datos.usr=$("#txtUsuario").val();
    Datos.psw=$("#txtPassword").val()

    var ajax = {
                type: "POST",
                async: true,
                dataType: "JSON",
                url: "/ajustes/ajax/GrabarCorreo/",
                data: JSON.stringify(Datos),
                error: function (xhr, status, error) {
                    alert("Ocurrio un error: " + error + ":" + eval(xhr).responseText);
                },
                success: function (data) {                    
                    d=eval(data);                    
                    if (d.error) {                        
                        alert(d.mensaje);                        
                    }
                    else{                        
                        alert("Datos del correo actualizados con exito");
                    }
                }
            };
            $.ajax(ajax);
            }

but if Datos.psw is equal to "??" change the value to "jQuery171033085118723101914_1432683256098"

![Image of the code](http://i58.tinypic.com/jf8emr.png)

**Comment by timmywil** [comment] 2015-05-27 13:42
Thank you for opening an issue, but I suspect this is a duplicate of #1799.

**Closed by timmywil** 2015-05-27 13:42 UTC
