### ISSUE TITLE
Ajax POST with json body bug

### ISSUE THREAD

**Issue by herberthobregon** [jquery/jquery#3838] opened 2017-11-05 05:50 UTC
when you send 

```
$.ajax({
	url: "https://api.example.com/v1/posts",
	type: 'POST',
	headers: {
		'Content-Type': 'application/json'
	},
	data: '{ "body": "some??"}',
	dataType: 'json',
	success: (result, textStatus, xhr) => {
		// Never go here
	},
	error: (xhr, status, error) => {
		// and Never go here...
	}
});
```

by some reason JQuery send 'GET' request with "body" (request params)

`{%20%22body%22:%20%22somejQuery32102992056471738016_1509859869431%22}&_=1509859869436`

en devTools shows

```
Request URL:https://api.example.com/v1/posts?{%20%22body%22:%20%22somejQuery32102992056471738016_1509859869431%22}&_=1509859869436
Request Method:GET
Status Code:401 
```

**Comment by mgol** [comment] 2017-11-05 17:53
Duplicate of #3798.

**Closed by mgol** 2017-11-05 17:53 UTC
