### ISSUE TITLE
Build fails on master in Windows

### ISSUE THREAD

**Issue by wangwanchao** [jquery/jquery#4548] opened 2019-11-22 14:53 UTC
**Env：win10 1909
Node.js：both v8.11.4 and v12.13.1
When I run 'npm run build'，there is a error as below:**

`
Running "build:all:*" (build) task                                                                                       Warning: "var/arr.js" does not exist in the hypothetical file system! Use --force to continue.                                                                                                                                                    Aborted due to warnings.                                                                                                 npm ERR! code ELIFECYCLE                                                                                                 npm ERR! errno 3                                                                                                         npm ERR! jquery@4.0.0-pre build: `npm install && grunt`                                                                  npm ERR! Exit status 3                                                                                                   npm ERR!                                                                                                                 npm ERR! Failed at the jquery@4.0.0-pre build script.                                                                    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.                                                                                                                                                npm ERR! A complete log of this run can be found in:                                                                     npm ERR!     E:\npm_modules\npm_cache\_logs\2019-11-22T14_45_16_106Z-debug.log
--
`
**then, I viewed the log**:
`13 verbose stack Error: jquery@4.0.0-pre build: `npm install && grunt`
13 verbose stack Exit status 3
13 verbose stack     at EventEmitter.<anonymous> (D:\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:210:5)
13 verbose stack     at ChildProcess.<anonymous> (D:\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:210:5)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid jquery@4.0.0-pre
15 verbose cwd E:\workspace\jquery
16 verbose Windows_NT 10.0.18363
17 verbose argv "D:\\nodejs\\node.exe" "D:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v12.13.1
19 verbose npm  v6.12.1
20 error code ELIFECYCLE
21 error errno 3
22 error jquery@4.0.0-pre build: `npm install && grunt`
22 error Exit status 3
23 error Failed at the jquery@4.0.0-pre build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 3, true ]
`
I cant got what I can do.

**Comment by mgol** [comment] 2019-11-22 20:55
I can't reproduce the issue on macOS Catalina. @dmethvin does it work OK for you on Windows?

@wangwanchao Can you try removing the `node_modules` and then running `npm run build` again? Make sure you're on the latest `master`.

**Comment by wangwanchao** [comment] 2019-11-24 06:22
> I can't reproduce the issue on macOS Catalina. @dmethvin does it work OK for you on Windows?
> 
> @wangwanchao Can you try removing the `node_modules` and then running `npm run build` again? Make sure you're on the latest `master`.

I removed the `node_modules`  under jquery and run `npm run build`, there is error like before

**Comment by mgol** [comment] 2019-11-24 11:09
Sorry, I forgot: remove both `node_modules` & `package-lock.json` & then try `npm run build`.

**Comment by dmethvin** [comment] 2019-11-24 21:33
Also getting an error here on Windows. Maybe an issue with path separators? I'm seeing a similar problem, but on `core.js` for some reason. The error message points to an issue with `rollup-plugin-hypothetical`. If I add [`leaveIdsAlone: true`](https://github.com/Permutatrix/rollup-plugin-hypothetical#optionsleaveidsalone) to the [build options](https://github.com/jquery/jquery/blob/075320149ae30a5c593c06b2fb015bdf033e0acf/build/tasks/build.js#L42-L45) it makes the problem go away and the build succeeds.

**Comment by mgol** [comment] 2019-11-25 19:02
@dmethvin I don't think that would work. The option you mentioned means the plugin doesn't resolve paths but treats them as strings. If those strings match, an override is served. The issue is our build process puts absolute paths into that plugin so they'd essentially all become unmatched - which means the default build would work but all of our include/exclude options would be ignored, breaking custom compilation.

The current configuration of our build means: if there is any override in what we pass to the plugin, use that as the source. The issue is with that second part. It looks like a bug in rollup-plugin-hypothetical, most likely https://github.com/Permutatrix/rollup-plugin-hypothetical/issues/5.

Unfortunately, the last version of that package was published 2 years ago... I'm not sure how actively it's maintained. That said, we only need a tiny part of that package functionality so I might as well go with the nuclear option & re-implement what we need in a small custom plugin lying in our repo. For what we need, it shouldn't be too hard, Rollup's plugin API surface is quite small: https://rollupjs.org/guide/en/#plugins-overview

**Comment by mgol** [comment] 2019-11-25 19:03
@timmywil I modified the milestone to `4.0.0` as this code is only on `master` and the `3.x-stable` branch builds fine.

**Comment by mgol** [comment] 2019-11-26 21:33
PR: #4549

**Comment by wangwanchao** [comment] 2019-11-27 11:22
I had removed node_modules, and run `npm run build`, but there is error like before, what somthing I can to do?

**Comment by mgol** [comment] 2019-11-27 11:24
@wangwanchao Did you try it on my branch? This is a PR, it's not merged yet.

**Comment by wangwanchao** [comment] 2019-11-27 16:02
sorry，according to what you said，I checkout branch `rollup-windows-fix`，build successfully. Thanks.

**Comment by mgol** [comment] 2019-11-27 16:07
@wangwanchao Thanks for confirming!

**Closed** 2019-12-02 18:55 UTC
Labels: Blocker, Build, Has Pull Request
