### ISSUE TITLE
Unable to subscribe on DOM node removing using API

### ISSUE THREAD

**Issue by San4es** [jquery/jquery#2088] opened 2015-02-13 13:47 UTC
Sometimes, it is necessary to know that element has been removed by jQuery API ($.remove(), $.empty(), $.html()). The use cases are to delete data associated with this element, created by another module, third party library or custom jQuery plugin. 

Now, it is unable to do this in frames current jQuery API. One of the possibly workarounds is override $.cleanData method, as jQuery UI does:

    $.cleanData = (function( orig ) {
	return function( elems ) {
		var events, elem, i;
		for ( i = 0; (elem = elems[i]) != null; i++ ) {
			try {

				// Only trigger remove when necessary to save time
				events = $._data( elem, "events" );
				if ( events && events.remove ) {
					$( elem ).triggerHandler( "remove" );
				}

			// http://bugs.jquery.com/ticket/8235
			} catch ( e ) {}
		}
		orig( elems );
	};
    })( $.cleanData );

But it is a workaround only and it looks as dirty hack.

Are there any reasons not to implement public API for this scenario out of the box?

My view, it is necessary to create 'remove' event for this case.

**Comment by scottgonzalez** [comment] 2015-02-13 14:02
Duplicate of #1736.

**Closed by scottgonzalez** 2015-02-13 14:02 UTC
