### ISSUE TITLE
CSS Display changes with :active css pseudo class not working when page uses jQuery 

### ISSUE THREAD

**Issue by ueberhammDesign** [jquery/jquery#4538] opened 2019-11-06 14:44 UTC
### Description ###
When I have an input element on my page, where the css `display` property is toggle by an `:active` pseudo class in the css file, the state will not be set at all if jQuery is integrated in the side. The input element do not have any event listeners by jQuery or any other JS. The problem only occurs in iOS 13 (tested in 13.1.2) (and the iPadOS Version) and it is tested in Safari and Chrome. The only workaround for a user is to tap quite long in the field.
 
This problem with text input fields have the effect that a user can not enter the input field. The only workaround right now is to remove the `:active` in the css. Then it works. (see test case)

(I noticed a similar behavior for links. But I can not reproduce it anymore. This could be related, but I do not think so.)   

### Link to test case ###
https://codepen.io/ueberhamm/pen/MWWVzER

(Please notice, that codepen itself integrate jQuery. This means you have to copy the code in a jQuery free environment to test this or turn of the Javascript. I tested both to make sure, it is not a general Javascript problem in iOS)

**Comment by mgol** [comment] 2019-11-06 16:41
Thanks for the report. I recreated the test case in JS Bin but I don't see the issue there even if jQuery is included. If the issue is really caused by jQuery, please adjust the JS Bin test case so that it can be reproduced there.

**Comment by mgol** [comment] 2019-11-06 16:42
Oops, the test case I mentioned: https://jsbin.com/muxuxep/1/edit?html,css,output

**Comment by ueberhammDesign** [comment] 2019-11-06 18:11
Hi, on which device/os version do you test this? I can reproduce it on my iPhone (iPhone XR/iOS 13.1.2/Safari) on the page you provided.

![ios-13-try-to-click-field-not-working](https://user-images.githubusercontent.com/13552270/68325118-1b059a80-00c9-11ea-94b3-f9a72f9ff584.gif)

**Comment by mgol** [comment] 2019-11-06 20:57
@ueberhammDesign I tested on an iPhone 11 Pro with iOS 13.2. I see where the confusion comes from: I can also reproduce this on the link I pasted; however, I cannot on the standalone test case without the JS Bin interface. If you open the link on the desktop & click the "Live preview" button - an arrow in the top-right corner, you get to a standalone page: https://output.jsbin.com/muxuxep/1. On that page on the iPhone I don't see the described issue.

Does that mean it can only be reproduced in an iframe? A few of our focus-related test cases started failing on iOS 13 when run via an iframe while they passed on iOS 12 & older, who knows if that's related?

**Comment by ueberhammDesign** [comment] 2019-11-06 21:35
I have the problem on "normal" pages also (not in iframe). But you are right. It seems that it work in jsbin. I came to the conclusion that it is jQuery related because when I tested it with real code, it disappeared when I removed jQuery. The css is untouched for this test. The test case is only a reduced version of the actual code. 
I am confused right now.

**Comment by mgol** [comment] 2020-01-02 16:43
Since we're missing a reduced test case here I'm going to close it for now. We can reopen if you manage to create a reproducible test case that won't depend on JS Bin specfics (a GitHub repository or a zip with an HTML example would do).

**Closed by mgol** 2020-01-02 16:43 UTC
Labels: Needs info
