### ISSUE TITLE
.html(htmlString) incorrectly closes self-closing tag

### ISSUE THREAD

**Issue by GaiusPious** [jquery/jquery#4721] opened 2020-05-26 09:04 UTC
### Description ###
Up to and including v3.4.1, the .html(htmlString) method would add a closing tag to self-closing tags which are not allowed. e.g. div, span, etc.

Due to a change in v3.5.0, the closing tag being added is placed at the end of the htmlString content, instead of directly after the self-closing tag.

e.g. `<div id="id1" /><div id="id2"></div>`
in 3.4.1 becomes:
`<div id="id1"></div><div id="id2"></div>`
in 3.5.0 and .1 becomes:
`<div id="id1"><div id="id2"></div></div>`

found on Chrome 81

### Link to test case ###
the way it used to work: https://jsfiddle.net/ywL7cp3h/
the current issue: https://jsfiddle.net/cgdjqbsr/

**Comment by mgol** [comment] 2020-05-26 09:36
Please read the [jQuery 3.5.0 blog post](https://blog.jquery.com/2020/04/10/jquery-3-5-0-released/) & the [upgrade guide](https://jquery.com/upgrade-guide/3.5/). Also, this is a duplicate of #4681, #4693, #4709, #4710 & #4720.

**Closed by mgol** 2020-05-26 09:36 UTC
