### ISSUE TITLE
Object doesn't support property or method 'shift' in IE

### ISSUE THREAD

**Issue by fatimaTalavera** [jquery/jquery#4368] opened 2019-04-23 18:38 UTC
When wanting to change my version of jquery from 3.0 to 3.4 I had an error with the event handler for recapcha.js
In internet explorer tells me that nop supports the 'shift' method, because the attribute is not an object.

![image](https://user-images.githubusercontent.com/11179725/56606579-84fa9e80-65d4-11e9-9043-b98a06cbfd5c.png)

**Comment by mgol** [comment] 2019-04-23 20:07
Duplicate of #4350.

**Closed by mgol** 2019-04-23 20:07 UTC
