### ISSUE TITLE
:visible/:hidden selectors unreliable

### ISSUE THREAD

**Issue by shimonenator** [jquery/jquery#2227] opened 2015-04-21 19:31 UTC
# Issue

This issue is present in both version 1 and 2 of jQuery.

It is happening on inline elements wrapping block elements, which is valid in HTML5, such as a header and an image wrapped in a single anchor.

Two issues arise:

1. Different browsers report offsetWidth/Height of the anchor differently. For example Firefox would report one visible anchor in the example below, and Chrome will report 0. This also highly depends on the CSS styles applied, as on the page where this issue was discovered missing images are not displayed at all instead of the common missing image icon.
2. While a browser may report an anchor as invisible, child elements are still visible and clickable as they inherit anchor properties.

## Example

```html
<!doctype html>
<html>
<head>
	<meta charset="utf-8">
	<script src="http://code.jquery.com/jquery-2.1.3.min.js"></script>
</head>
<body>
	<a href=#>
		<h1>Header</h1>
	</a>
	<script>
		$(function () {
			alert('Visible anchors: ' + $('a:visible').length);
		})
	</script>
</body>
</html>
```

# Solution
There are 2 potential solutions that come to mind, but each has flaws

1. Loop through child elements and check each for visibility. Potentially harmful for performance, although the selector is already marked as such in the documentation. 
2. Check parent for visibility. Probably not enough on its own, as it will report incorrectly, if anchor doesn't have visible children.

**Comment by timmywil** [comment] 2015-04-21 20:43
Thank you for opening an issue. While you are correct that the behavior may be unexpected, the selector is working as documented. While the behavior differs between Firefox and Chrome, Chrome reports zero width and zero height, which technically means it is not visible according to our docs...

> Visible elements have a width or height that is greater than zero.

The fact the hidden elements can have visible content can seem strange, but it's the way it is in Chrome. But more importantly, the cost of working around this would be far greater than we are willing to deal with. I don't think this is the only edge case where the `:visible` selector behaves in a way that can be unexpected, but I would prefer to keep the selector as simple as possible and let the edge cases be covered by other means.

**Comment by dmethvin** [comment] 2015-04-21 21:00
This seems like a Chrome bug, does Safari have it as well?

**Comment by mzgol** [comment] 2015-04-21 21:03
> This seems like a Chrome bug, does Safari have it as well?

Yes.

**Comment by dmethvin** [comment] 2015-04-21 21:03
Here's a test case: http://jsfiddle.net/2tgw2yr3/

Both jsbin.com and browserstack.com are down for me at the moment.

**Comment by shimonenator** [comment] 2015-04-22 01:20
@timmywil thank you for a quick reply. 

First of all I'd like to apologize, I did file a duplicate issue. It seems that there's at least one earlier issue #1855 reporting this problem, which includes a solution.

Also, while it doesn't seem strange to that not visible elements can bleed visible child elements. 

For the edge case degree, perhaps there should be a note in the documentation then. IMO people use jQuery to get the same results in different browsers no matter what, and they may not even realize that their selectors will sometime behave differently.

**Comment by dmethvin** [comment] 2015-04-22 04:07
Funny, I thought I remembered an issue like this where `getBoundingClientRect` came into play but I couldn't find it because I was looking in the old tracker which was down. Maybe I'm crashing all these sites, I dunno.

The `:visible` and `:hidden` selectors aren't a good idea because they can make the browser do a lot of work to determine the answer when the layout has been changed. In many cases you can track that information in other ways and it will be a lot faster.

**Comment by gibson042** [comment] 2015-04-22 13:27
@dmethvin How old was it? @shimonenator already found #1855, and the only other case that comes to my mind is the soon-to-be-merged #2043 (which [uses `getClientRects` to decide if `.offset` is meaningful](https://github.com/jquery/jquery/pull/2043/files#diff-d38379d70ee2c5c5a0acb5b0f7acef8dL96)). In fact, that work in particular leaves me open to a redefinition of `:visible` as `!!(elem.offsetWidth || elem.offsetHeight || elem.getClientRects().length)`.

**Comment by scottgonzalez** [comment] 2015-04-22 13:32
> The :visible and :hidden selectors aren't a good idea because they can make the browser do a lot of work to determine the answer when the layout has been changed. In many cases you can track that information in other ways and it will be a lot faster.

I know you love to say this as much as possible, but it's really not helpful for developers writing general purpose code, and the performance problems are irrelevant for many use cases.

**Comment by timmywil** [comment] 2015-04-22 19:09
> In fact, that work in particular leaves me open to a redefinition of `:visible` as `!!(elem.offsetWidth || elem.offsetHeight || elem.getClientRects().length)`.

If it's that simple and `getClientRects` doesn't cost too much, let's do it.

**Comment by shimonenator** [comment] 2015-04-22 21:07
@scottgonzalez 

I think you meant `:visible` as 

```javascript
return !!((elem.offsetWidth && elem.offsetHeight) || elem.getClientRects().length)
```

As such, following the current implementation where `:hidden` is the functional method, it would be:

```javascript
return (!elem.offsetWidth || !elem.offsetHeight) && !elem.getClientRects().length
```

Thus, it seems to me that `:visible` is a more performant solution, as it would only fall onto `getClientRects()` when either `offsetWidth` or `offsetHeight` is 0. In case with `:hidden`, `getClientRects()`will always be executed. That's for v2. It's a little more complicated in v1 due to an old Opera behavior.

**Comment by shimonenator** [comment] 2015-04-22 21:12
Just discovered that there's another solution #2212 with a PR that was approved. It seems that in line with current discussion about performance, there should be some additional consideration added to #2212.

**Comment by gibson042** [comment] 2015-04-23 00:24
Upon deeper analysis, this would _not_ be a behavior change if it makes it in for 3.0, which I **strongly** recommend. The git builds include 10399ddcf8a239acc27bdec9231b996b178224d3 (defining `:hidden` by `elem.offsetWidth <= 0 || elem.offsetHeight <= 0`, essentially `noWidth OR noHeight`), but that is unreleased—all releases from 1.4 forward use logic like `noWidth AND noHeight`. A fix for this issue would refine the released logic and revert 10399ddcf8a239acc27bdec9231b996b178224d3.

**Comment by timmywil** [comment] 2015-05-08 20:00
Actually, it looks like the proposed solution breaks the `width: 0; height: 0; overflow: hidden;` case.

**Comment by gibson042** [comment] 2015-05-08 20:25
Ah, a slight behavior change, then. I'm still in favor of the `getClientRects().length` approach.

**Comment by timmywil** [comment] 2015-05-08 20:57
In that case, what about dropping `offsetWidth` and `offsetHeight`?

**Comment by gibson042** [comment] 2015-05-08 21:03
I would make such a decision entirely on performance. My untested supposition is that offset properties are faster than `getClientRects`, and therefore worth including even though redundant.

**Comment by timmywil** [comment] 2015-05-08 21:43
I'll do some testing.

**Comment by timmywil** [comment] 2015-05-08 22:23
Ok, looks like performance necessitates keeping `offsetWidth` and `offsetHeight`. http://jsperf.com/visible-hidden-and-getclientrects

There's no difference for hidden elements, but it's about 2x slower in Chrome for *visible* elements to only use `.getClientRects()`.

**Comment by timmywil** [comment] 2015-05-08 22:32
[PR](https://github.com/jquery/jquery/pull/2281)

**Closed** 2015-05-12 13:15 UTC
Labels: Behavior Change, CSS, Has Pull Request

**Comment by shimonenator** [comment] 2015-05-14 05:41
Sorry for being late to the proposed and accepted PR, but it does not fix the issue. Please refer to my original issue description and a [follow up comment](https://github.com/jquery/jquery/issues/2227#issuecomment-95336488).

**Comment by timmywil** [comment] 2015-05-14 10:24
@shimonenator Had we wanted to keep the logic that was there, your suggestion would be right. However, the change was intentional.

**Comment by FesterCluck** [comment] 2015-09-20 08:55
My apologies for commenting on a closed issue, but I believe this case warrants review.

Using ClientRectList.prototype.length an anchor tag with no text is "visible", not to mention one with child elements which have no dimension either.

Please consider https://github.com/FesterCluck/jquery/blob/master/src/css/hiddenVisibleSelectors.js

If this is not part of the new intended behavior, my apologies.
