### ISSUE TITLE
Issues using ShadowDom and ShadowRoot elements

### ISSUE THREAD

**Issue by mzgol** [jquery/jquery#1784] opened 2014-10-21 00:40 UTC
Originally reported by rictic at: http://bugs.jquery.com/ticket/15201
<p>
JSBin link to reproduce: <a class="ext-link" href="http://jsbin.com/tamugo/2/edit" rel="nofollow"><span class="icon">&nbsp;</span>http://jsbin.com/tamugo/2/edit</a> (try in Chrome (or Firefox with dom.webcomponents.enabled turned on))
</p>
<p>
An element that is in the shadow dom appears in some ways to not be contained in the document. .offset() assumes that if the element isn't contained in the document then it's disconnected and returns an offset of {top: 0, left: 0}.
</p>
<p>
When .offset() checks to see if the element is disconnected it could try walking up the DOM not only by checking .parentNode as .contains() does but also by looking at .host, which is how one travels up from a shadow root into its containing element.
</p><p>Issue reported for jQuery 2.1.1</p>

**Comment by NekR** [comment] 2015-01-27 06:48
```javascript
if (elem.createShadowRoot) {
  var rect = elem.getBoundingClientRect();
  // disconnected or hidden
  if (!rect.height && !rect.width) {
    return box;
  }

  box = rect;
} else {
  // Make sure it's not a disconnected DOM node
  if ( !jQuery.contains( docElem, elem ) ) {
    return box;
  }

  box = elem.getBoundingClientRect();
}
```

This is another way to fix this issue. This method does not need traversation over tree to detect if element is disconnected. ```getBoundingClientRect()``` does nothing on disconnected nodes and returns always zeroes. It also returns zeroes on hidden elements. So if element is hidden or disconnected -- we return zeroes. If it visible and in the tree (anywhere in the tree) -- then we return real box.

One problem here is that for hidden elements, jQuery currently returns box ```{ top: 0 + pageYOffset, left: 0 + pagetXOffset }``` and for disconnected elements returns always ```{ top: 0, left: 0 }```.
I do not know if this artifact is useful or if someone uses it. Probably it might break compatibility.

Anyway, I will just leave it here as an alternative solution.

**Comment by NekR** [comment] 2015-01-27 07:00
Also, as far as I see, there is no tests for such behavior. And if you think what that method will not break compatibility, then we can even drop the condition there and execute always first part.

**Comment by dmethvin** [comment] 2015-01-27 14:12
It's possible we could use something like the solution @NekR proposes. The [docs for .offset()](http://api.jquery.com/offset/) specifically say it doesn't work for  hidden elements.

**Comment by nazar-pc** [comment] 2015-01-27 14:18
@dmethvin, in this case code above can be simplified to just `box = elem.getBoundingClientRect();`

**Comment by TeaSeaLancs** [comment] 2015-01-27 14:20
I think there's a point missing here: If it was only ever as simple as @nazar-pc indicates, why does the case to check whether it's a disconnected DOM node exist in the first place? 

Is it a workaround for browsers which is no longer needed? Or is it an optimisation step to prevent the needless call of a potentially expensive function?

If it's the former then sure, but if it's the latter do we not have to think about performance?

**Comment by nazar-pc** [comment] 2015-01-27 14:43
Thanks to PhpStorm and how it integrates git I found where that code started:
ea507b3e998126ae1f94f4fd1618994d645c9cc8
http://bugs.jquery.com/ticket/7190

**Comment by TeaSeaLancs** [comment] 2015-01-27 14:49
So the question becomes does that bug still affect any of the browsers which are supported by jQuery 2.x? If not then it seems like a fairly decent solution for .offset()

I'm not sure whether the solution would work for all of the issues reported with working with elements under a shadow DOM though (Which would ostensibly be any function which uses jQuery.contains() as a method of filtering out disconnected nodes). What do you think?

**Comment by dmethvin** [comment] 2015-01-27 14:58
Actually the ticket @nazar-pc references seems to indicate that we were trying to support a return value of top/left 0 for disconnected elements. So any change should preserve that.

**Comment by nazar-pc** [comment] 2015-01-27 15:09
Anything that uses native functions should work fine just like with `$.offset()` and without redundant check will work even faster than before.
We need to check all usages of `.contains()` and in every particular case determine whether we need it now or not, in many cases it might be replaced by native `element.matches()`.

@dmethvin, but that gives really big overhead to handle disconnected nodes especially with ShadowDOM support.

Maybe with performance consideration (number of elements in DOM tree with ShadowDOM might much bigger than before) we can drop support for this edge case? In my opinion it worth that, especially with new major version. Also, it will not break any well-written code (it should be something wrong with getting offset of disconnected node).

**Comment by dmethvin** [comment] 2015-01-27 15:17
> Also, it will not break any well-written code (it should be something wrong with getting offset of disconnected node).

I agree with that completely. The problem is, people write bad code all the time, sometimes by accident when cases like this quietly return values that make it seem like everything is okay. I would have preferred that ticket be closed with, "Why are you getting the offset of an element not in the document? We'll update the docs to state that's not valid." It's very possible though that some code now depends on the zero return values. That's what has me concerned.

Any other opinions?

**Comment by gibson042** [comment] 2015-01-27 15:56
From an API perspective, the best behavior would be to throw when offset is meaningless (i.e., truly disconnected elements). From a documentation perspective, the best behavior would be to exclude such elements from the range of valid input, in which case the return value is unspecified (and allowed to be cross-version/cross-branch inconsistent) but `{ top: 0, left: 0 }` is as good as anything else.

So I'm perfectly content with @NekR's proposal, provided it doesn't introduce an inconsistency between `master` and `compat` for handling of shadow DOM elements.

**Comment by nazar-pc** [comment] 2015-01-27 18:34
Well, guys, I have Chromium 39.0.2171.65 with native support for ShadowDOM and other stuff and guess what:
```js
var y = document.createElement('div')
y.getBoundingClientRect()
```
outputs
> ClientRect {height: 0, width: 0, left: 0, bottom: 0, right: 0…}

Now Firefox Nightly 38.0a1 (2015-01-25), guess output?
> DOMRect { x: 0, y: 0, width: 0, height: 0, top: 0, right: 0, bottom: 0, left: 0 }

So, why do we need to check for anything here, it already gives correct zeros.

Where problem comes is `var docElem = elem.ownerDocument.documentElement` which is used when returning value. It will be `undefined` on disconnected nodes only independently whether it is inside ShadowDOM or not. It will likely be the same in any browser, so we do not need to call `.contains()` or whatever else.

Finally:
```js
if (!elem.ownerDocument.documentElement) {
    return { top: 0, left: 0 };
}
box = elem.getBoundingClientRect();
```

Pretty straightforward. Not sure why it wasn't this way from the beginning. What you think?

**Comment by nazar-pc** [comment] 2015-01-27 18:38
Moreover, in `.offset()` there is a check for `elem.ownerDocument` not to be falsy, but [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Node.ownerDocument) states that it can be `null` if only called on document itself, does that makes sense to call `.offset()` on `document`?
In all other cases check is redundant.

**Comment by NekR** [comment] 2015-01-27 19:16
@dmethvin wrote:
> Actually the ticket @nazar-pc references seems to indicate that we were trying to support a return value of top/left 0 for disconnected elements. So any change should preserve that.

That ticket removes scroll positions for disconnected nodes, but not for hidden nodes. If we will use only getBoundingClientRect() then it also will remove scroll positions for hidden nodes. Seems correct to me that hidden elements always should have zeroes too.

@nazar-pc wrote:
> Well, guys, I have Chromium 39.0.2171.65 with native support for ShadowDOM and other stuff and guess what:

Did not get your comment. You mean for attached and visible nodes it always returns zeroes? If so, then very strange because for me on Chrome 40 it works correctly.

To summarize:
* ```element.contains/compareDocumentPosition``` does not work with ShadowDom as we expect -- cannot match nodes in ShadowDom
* ```element.getBoundingClientRect``` does work as expected (at least at Chrome 40) and returns zeroes (top, left, bottom, right) for hidden and disconnected element regardless of that node is in Shadow or Light dom

@nazar-pc wrote:
> Where problem comes is var docElem = elem.ownerDocument.documentElement which is used when returning value. It will be undefined on disconnected nodes only independently whether it is inside ShadowDOM or not. It will likely be the same in any browser, so we do not need to call .contains() or whatever else.
> 
> Finally:
> ...

If it works then it's very nice way, I am just not sure about IE8 because him disconnected nodes are not really disconnected. Does anyone have IE8 in shorthand to test it?

**Comment by nazar-pc** [comment] 2015-01-27 20:03
> Did not get your comment. You mean for attached and visible nodes it always returns zeroes? If so, then very strange because for me on Chrome 40 it works correctly.
No, in example next to that line you can see that it returns zeros on disconnected node.
> Does anyone have IE8 to test it?
Does jQuery 3.0 will support this very old browser? Or you meant compat version?

**Comment by NekR** [comment] 2015-01-27 21:12
> No, in example next to that line you can see that it returns zeros on disconnected node.

Oh, yes, I overlooked that, sorry. This is exactly why I proposed use of only ```getBoundingClientRect()``` without traversing dom tree -- because it works.

> Does jQuery 3.0 will support this very old browser? Or you meant compat version?

I really do not know about which version we talk here, but for me it seems like both versions are broken in ShadowDOM, so both should be fixed. If I am wrong, please correct me.

**Comment by dmethvin** [comment] 2015-01-28 00:58
API-wise, jQuery 3.0 and jQuery Compat 3.0 are the same. The only difference is the browsers they support, IE8 being the odd one of course. We'd want the API to work (have consistent results) in the latest Chrome if a site is using either branch. 

There definitely needs to be some IE8 experimenting done here, because calling `.getBoundingClientRect()` on a disconnected element throws an error. Not sure whether a tree climb is more expensive than a try/catch wrapper, I really dislike try/catch though.

![capture](https://cloud.githubusercontent.com/assets/157858/5930544/d8407d42-a65e-11e4-9333-bd040d01ca5d.PNG)

**Comment by gibson042** [comment] 2015-01-28 01:06
Honestly, I'd prefer throwing an error instead of returning inaccurate `{ top: 0, left: 0 }` results—and we could do so with abandon if disconnected elements are excluded from valid input.

**Comment by NekR** [comment] 2015-01-28 01:23
I am making now small steps to resolve this issue in branch of my fork (Github already showed it here).
I will download soon WinXP virtual machine and will test all the things on IE8 to find correct solution.
In the mean time, tests fails for me with or without my changes. Here is screenshot of these errors:
![screenshot - jquerytestcom_28012015_23016](https://cloud.githubusercontent.com/assets/1189265/5930760/b6ab4098-a69c-11e4-9861-d41613cf0edb.png)

> Honestly, I'd prefer throwing an error instead of returning inaccurate { top: 0, left: 0 } results—and we could do so with abandon if disconnected elements are excluded from valid input.

Hmm, I think this might broke compatibility since jQuery never throwed errors there.

**Comment by NekR** [comment] 2015-01-28 02:14
Unfortunately I cannot run tests on IE8, even if I checkout "compat" branch.
But I tested ```elem.ownerDocument.documentElement``` and it's not the case for IE8 because this property exists even for disconnected nodes.

As you may see here https://github.com/NekR/jquery/compare/1784-fix-offset-in-shadow-dom?expand=1 I use this condition:
```javascript
if ( !elem.createShadowRoot && !jQuery.contains( docElem, elem ) ) {
```
which uses ```contains``` only if user-agent does not have ShadowDOM. This excludes older browsers such as IE8.

Questions:
* Should I make pull request right now or we need discuss it more?
* How it will be merged with "compat" branch, should I fix it in compat branch by myself or you do it by merging?
* Of course I should write tests for it, but do we need tests only for ShadowDOM or for disconnected/hidden elements too (make sure they always return { top: 0, left: 0 } rect)?

**Comment by gibson042** [comment] 2015-01-28 14:24
> Hmm, I think this might broke compatibility since jQuery never throwed errors there.

It doesn't violate our currently-documented API;  http://api.jquery.com/offset/ already includes "jQuery does not support getting the offset coordinates of hidden elements". And even if that were not the case, backwards-incompatible changes are allowed with the upcoming major version bump.

> `if ( !elem.createShadowRoot && !jQuery.contains( docElem, elem ) ) {`

I don't like this conflation of unrelated behaviors.

> Should I make pull request right now or we need discuss it more?

Please make a pull request; further discussion can take place there.

> How it will be merged with "compat" branch, should I fix it in compat branch by myself or you do it by merging?

Our general guideline is that a separate PR is required only when the solution looks sufficiently different between the two branches that cherry-pick is impractical. For this ticket, one will be enough.

> Of course I should write tests for it, but do we need tests only for ShadowDOM or for disconnected/hidden elements too (make sure they always return { top: 0, left: 0 } rect)?

That depends on whether or not we want to guarantee such return values. For now, limit new tests to Shadow DOM.

**Comment by nazar-pc** [comment] 2015-01-28 14:47
There are tests for ShadowDOM in my fork

**Comment by NekR** [comment] 2015-01-29 01:02
> It doesn't violate our currently-documented API; http://api.jquery.com/offset/ already includes "jQuery does not support getting the offset coordinates of hidden elements". And even if that were not the case, backwards-incompatible changes are allowed with the upcoming major version bump.

Ok, I have no problem with it. Just wondered about possible problems. If you think it will not be so much problem then it's probably ok.

Other answers in PR.

**Closed** 2015-05-05 15:54 UTC
Labels: behavior-change, Dimensions
