### ISSUE TITLE
Nesting tables on 3.1.1 results in an incorrect insert.

### ISSUE THREAD

**Issue by leonardjo** [jquery/jquery#3472] opened 2016-12-24 02:59 UTC
### Description ###

Nesting tables on 3.1.1 results in an incorrect insert. It appears only to happen when the surrounding table tags are provided in static html. When inserting the table into the body dynamically the bug does not occur.

### Link to test case ###

<!DOCTYPE html>
<html>

  <head>
    <title>Test Nested Table</title>
    <style>
td {
  border: 1px solid #bbb;
}
tr {
  height: 70px;
  min-height: 70px;
}
td {
  width: 70px;
  min-width: 70px;
}
tr.nested {
  height: 70px;
  min-height: 70px;
}
    </style>
    
    <script src="../jQuery/jquery-3.1.1.js"></script>
    

    <script>
$(document).ready(function() {
  function rows() {
    var s = '';
    for (var i = 0; i < 2; i++) {
      s += '<td class="col' + i + '"><div>x</div></td>' + "\n";
    }
    return s;
  }
  var s = '';
  //s += '<table>' + "\n";
  for (var i = 0; i < 2; i++) {
    s += '<tr class="row' + i + '">' + "\n";
    s += rows();
    s += '</tr>' + "\n";
  }
  //s += '</table>' + "\n";
  $("#main").append(s);
  // Doesn't happen if we dynamically add the table to the body first.
  //$("body").append('<table id="main">' + "\n" + s + '</table>' + "\n");

  $('tr.row1 td.col1 div', '#main').html('<table id="nested">' + "\n" + s + '</table>' + "\n");

  // This row gets appended to #nested not #main...
  s = '<tr class="rown"><td><div>x</div></td><td><div>x</div></td></tr>' + "\n";
  $("#main").append(s);
});
    </script>
</head>
  <body>
    
    <table id="main"></table>
  </body>
</html>

**Comment by leonardjo** [comment] 2016-12-24 03:08
Lovely. How do I paste that html/js example?

**Comment by leonardjo** [comment] 2016-12-24 03:19
&lt;!DOCTYPE html&gt;<br />
&lt;html&gt;<br />
&lt;!--<br />
Result with 3.1.1:<br />
<br />
----------------<br />
|    |         |<br />
----------------<br />
|    |    |    |<br />
|    -----------<br />
|    |    |    |<br />
|     ----------<br />
|    |    |    |<br />
----------------<br />
<br />
Should be (1.12.4 &amp; 2.2.4):<br />
<br />
----------------<br />
|    |         |<br />
----------------<br />
|    |    |    |<br />
|    -----------<br />
|    |    |    |<br />
----------------<br />
|    |         |<br />
----------------<br />
<br />
--&gt;<br />
  &lt;head&gt;<br />
    &lt;title&gt;Test Nested Table&lt;/title&gt;<br />
    &lt;style&gt;<br />
td {<br />
  border: 1px solid #bbb;<br />
}<br />
tr {<br />
  height: 70px;<br />
  min-height: 70px;<br />
}<br />
td {<br />
  width: 70px;<br />
  min-width: 70px;<br />
}<br />
tr.nested {<br />
  height: 70px;<br />
  min-height: 70px;<br />
}<br />
    &lt;/style&gt;<br />
    &lt;!-- 3.1.1 appends the last string to the nested table, not the main table --&gt;<br />
    &lt;script src=&quot;../jQuery/jquery-3.1.1.js&quot;&gt;&lt;/script&gt;<br />
    &lt;!-- 2.2.4 and 1.12.4 add the string correctly --&gt;<br />
&lt;!--    &lt;script src=&quot;../jQuery/jquery-2.2.4.js&quot;&gt;&lt;/script&gt;--&gt;<br />
&lt;!--    &lt;script src=&quot;../jQuery/jquery-1.12.4.js&quot;&gt;&lt;/script&gt;--&gt;<br />
    &lt;script&gt;<br />
$(document).ready(function() {<br />
  function rows() {<br />
    var s = '';<br />
    for (var i = 0; i &lt; 2; i++) {<br />
      s += '&lt;td class=&quot;col' + i + '&quot;&gt;&lt;div&gt;x&lt;/div&gt;&lt;/td&gt;' + &quot;\n&quot;;<br />
    }<br />
    return s;<br />
  }<br />
  var s = '';<br />
  //s += '&lt;table&gt;' + &quot;\n&quot;;<br />
  for (var i = 0; i &lt; 2; i++) {<br />
    s += '&lt;tr class=&quot;row' + i + '&quot;&gt;' + &quot;\n&quot;;<br />
    s += rows();<br />
    s += '&lt;/tr&gt;' + &quot;\n&quot;;<br />
  }<br />
  //s += '&lt;/table&gt;' + &quot;\n&quot;;<br />
  $(&quot;#main&quot;).append(s);<br />
  // Doesn't happen if we dynamically add the table to the body first.<br />
  //$(&quot;body&quot;).append('&lt;table id=&quot;main&quot;&gt;' + &quot;\n&quot; + s + '&lt;/table&gt;' + &quot;\n&quot;);<br />
<br />
<br />
  $('tr.row1 td.col1 div', '#main').html('&lt;table id=&quot;nested&quot;&gt;' + &quot;\n&quot; + s + '&lt;/table&gt;' + &quot;\n&quot;);<br />
<br />
  // This row gets appended to #nested not #main...<br />
  s = '&lt;tr class=&quot;rown&quot;&gt;&lt;td&gt;&lt;div&gt;x&lt;/div&gt;&lt;/td&gt;&lt;td&gt;&lt;div&gt;x&lt;/div&gt;&lt;/td&gt;&lt;/tr&gt;' + &quot;\n&quot;;<br />
  $(&quot;#main&quot;).append(s);<br />
});<br />
    &lt;/script&gt;<br />
&lt;/head&gt;<br />
  &lt;body&gt;<br />
    &lt;!-- if we insert #main dynamically into body all is well.<br />
         but with this static definition of the table 3.1.1 stumbles. --&gt;<br />
    &lt;!----&gt;&lt;table id=&quot;main&quot;&gt;&lt;/table&gt;<br />
  &lt;/body&gt;<br />
&lt;/html&gt;<br />
&lt;!-- vim: set et ts=2 sw=2 : --&gt;<br />
<br />

**Comment by leonardjo** [comment] 2016-12-24 03:47
Hard to cut & paste a html/js example. This is "htmlentitied" and "nl2brd".
The example is clearer when using a fixed width font. You can still count the pipes ;-) .

&lt;!DOCTYPE html&gt;<br />
&lt;html&gt;<br />
&lt;!--<br />
Result with 3.1.1:<br />
<br />
----------------<br />
|    |         |<br />
----------------<br />
|    |    |    |<br />
|    -----------<br />
|    |    |    |<br />
|     ----------<br />
|    |    |    |<br />
----------------<br />
<br />
Should be (1.12.4 &amp; 2.2.4):<br />
<br />
----------------<br />
|    |         |<br />
----------------<br />
|    |    |    |<br />
|    -----------<br />
|    |    |    |<br />
----------------<br />
|    |         |<br />
----------------<br />
<br />
--&gt;<br />
  &lt;head&gt;<br />
    &lt;title&gt;Test Nested Table&lt;/title&gt;<br />
    &lt;style&gt;<br />
td {<br />
  border: 1px solid #bbb;<br />
}<br />
tr {<br />
  height: 70px;<br />
  min-height: 70px;<br />
}<br />
td {<br />
  width: 70px;<br />
  min-width: 70px;<br />
}<br />
tr.nested {<br />
  height: 70px;<br />
  min-height: 70px;<br />
}<br />
    &lt;/style&gt;<br />
    &lt;!-- 3.1.1 appends the last string to the nested table, not the main table --&gt;<br />
    &lt;script src=&quot;../jQuery/jquery-3.1.1.js&quot;&gt;&lt;/script&gt;<br />
    &lt;!-- 2.2.4 and 1.12.4 add the string correctly --&gt;<br />
&lt;!--    &lt;script src=&quot;../jQuery/jquery-2.2.4.js&quot;&gt;&lt;/script&gt;--&gt;<br />
&lt;!--    &lt;script src=&quot;../jQuery/jquery-1.12.4.js&quot;&gt;&lt;/script&gt;--&gt;<br />
    &lt;script&gt;<br />
$(document).ready(function() {<br />
  function rows() {<br />
    var s = '';<br />
    for (var i = 0; i &lt; 2; i++) {<br />
      s += '&lt;td class=&quot;col' + i + '&quot;&gt;&lt;div&gt;x&lt;/div&gt;&lt;/td&gt;' + &quot;\n&quot;;<br />
    }<br />
    return s;<br />
  }<br />
  var s = '';<br />
  //s += '&lt;table&gt;' + &quot;\n&quot;;<br />
  for (var i = 0; i &lt; 2; i++) {<br />
    s += '&lt;tr class=&quot;row' + i + '&quot;&gt;' + &quot;\n&quot;;<br />
    s += rows();<br />
    s += '&lt;/tr&gt;' + &quot;\n&quot;;<br />
  }<br />
  //s += '&lt;/table&gt;' + &quot;\n&quot;;<br />
  $(&quot;#main&quot;).append(s);<br />
  // Doesn't happen if we dynamically add the table to the body first.<br />
  //$(&quot;body&quot;).append('&lt;table id=&quot;main&quot;&gt;' + &quot;\n&quot; + s + '&lt;/table&gt;' + &quot;\n&quot;);<br />
<br />
<br />
  $('tr.row1 td.col1 div', '#main').html('&lt;table id=&quot;nested&quot;&gt;' + &quot;\n&quot; + s + '&lt;/table&gt;' + &quot;\n&quot;);<br />
<br />
  // This row gets appended to #nested not #main...<br />
  s = '&lt;tr class=&quot;rown&quot;&gt;&lt;td&gt;&lt;div&gt;x&lt;/div&gt;&lt;/td&gt;&lt;td&gt;&lt;div&gt;x&lt;/div&gt;&lt;/td&gt;&lt;/tr&gt;' + &quot;\n&quot;;<br />
  $(&quot;#main&quot;).append(s);<br />
});<br />
    &lt;/script&gt;<br />
&lt;/head&gt;<br />
  &lt;body&gt;<br />
    &lt;!-- if we insert #main dynamically into body all is well.<br />
         but with this static definition of the table 3.1.1 stumbles. --&gt;<br />
    &lt;!----&gt;&lt;table id=&quot;main&quot;&gt;&lt;/table&gt;<br />
  &lt;/body&gt;<br />
&lt;/html&gt;<br />
&lt;!-- vim: set et ts=2 sw=2 : --&gt;<br />
<br />

**Comment by leonardjo** [comment] 2016-12-24 05:23
It appears the incorrect reference is triggered when plain &lt;table&gt; tags are inserted into the the DOM. When filling the table with one or more rows before inserting it into the DOM the reference (still pointing to the previous table) gets correctly updated. (With a static html tag in a template no data gets provided on insertion in the DOM either.)

Adding a &lt;tbody&gt; inside the &lt;table&gt; triggers the reference update and can be used as a workaround.

**Comment by mgol** [comment] 2016-12-24 09:57
GitHub uses Markdown so just wrap code in triple backticks, you can even
specify the language:
https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by gibson042** [comment] 2016-12-24 15:14
@leonardjo Can you instead create a live example on [JS Bin](https://jsbin.com)/[JSFiddle](https://jsfiddle.net)/etc. and just post a link here? Live examples are better because we can easily explore them during our issue investigation.

**Comment by leonardjo** [comment] 2016-12-24 17:16
Splitting up above example in html, css and js parts works like a charm on JSBin. Cut and paste the whole thing, cut css and paste into its box, cut js and paste into its box, and paste the remainder into the html box. Remove the ref to jquery and add one from the drop down. Please do that yourself. Or just cut and paste into a .html file and open in your browser. How hard can it be?

I do not wish to create an account at JSBin which is required to save a bin. I do not get this to work on JSFiddle immediately (how and from where to include jQuery?), probably need an account there too. If you need this on JSBin please add it there yourself.

From testing on JSBin it appears the bug also exists in 3.1.0. It triggers on adding plain <table> tags either via static html or .append(). Appending with content (not always available) or adding <tbody> tags seem to cause the table pointer to be correctly updated.

Apparently

**Comment by leonardjo** [comment] 2016-12-24 17:23
So used to local includes that I didn't think to just copy the url JSBin provided. Example then works on JSFiddle too:

https://jsfiddle.net/v6owy6c4/2/

**Comment by gibson042** [comment] 2016-12-24 18:15
Thank you. I've [cleaned it up](https://jsfiddle.net/v6owy6c4/3/), and determined this issue to be a duplicate of #3439. Our next release should include a fix.

**Closed by gibson042** 2016-12-24 18:15 UTC
