### ISSUE TITLE
jQuery does not respond to events on shadow root

### ISSUE THREAD

**Issue by paul-f** [jquery/jquery#4418] opened 2019-06-07 22:03 UTC
### Description ###
Running Chrome 73.0.3683.86 on Windows 7 with jQuery 3.4.1.

When you use jQuery's on() function on the shadow root of a custom element, it does not receive events. Using plain JS addEventListener() works as expected.

This occurs because a shadow root is implemented as a document fragment, and jQuery specifically does not attach data to non-element nodes; see line 4047 call to acceptData().

### Link to test case ###
https://jsbin.com/ketocucaku/edit?html,js,output

**Comment by timmywil** [comment] 2019-07-01 16:34
Duplicate of #4317

**Closed by timmywil** 2019-07-01 16:34 UTC
Labels: Event, Needs review
