### ISSUE TITLE
jQuery 3.5.1 incorrectly closes tags

### ISSUE THREAD

**Issue by kenfreeman** [jquery/jquery#4710] opened 2020-05-07 17:45 UTC
### Description ###

jQuery 3.5.1 incorrectly closes self-closed tags. As you can see from the test case, the <B/> tag should not apply to the string that comes after it. And yet it is bolded.

Changing back to 3.4.1 fixes the issue.

### Link to test case ###
https://jsfiddle.net/ken_f/spmxe5d1/3

**Comment by kenfreeman** [comment] 2020-05-07 18:28
Even clearer test case in https://jsfiddle.net/ken_f/spmxe5d1/

**Comment by mgol** [comment] 2020-05-07 19:04
Please read the [jQuery 3.5.0 blog post](https://blog.jquery.com/2020/04/10/jquery-3-5-0-released/) & the [upgrade guide](https://jquery.com/upgrade-guide/3.5/). Also, this is a duplicate of #4681, #4693 & #4709.

**Closed by mgol** 2020-05-07 19:04 UTC
