### ISSUE TITLE
SCRIPT445: Object doesn't support this action error in IE11 browser after upgrading to jQuery 3.5.1

### ISSUE THREAD

**Issue by ArularasiA** [jquery/jquery#4910] opened 2021-07-26 10:58 UTC
### jQuery version ### 
3.5.1

### Browsers affected ### 
 IE11 only

### Description ###

Getting the error "SCRIPT445: Object doesn't support this action" while clicking the button in pop up (ok/cancel). 
Popup type - jQuery ui -1.12.1 dialog

The error pointing to the jQuery-3.5.1 core file on the dispatch function new array declaration 
                          **args = new Array(arguments.length)**

dispatch: function (nativeEvent) {

			var i, j, ret, matched, handleObj, handlerQueue,
				args = new Array(arguments.length), //Error Line

				// Make a writable jQuery.Event from the native event object
				event = jQuery.event.fix(nativeEvent),

				handlers = (
					dataPriv.get(this, "events") || Object.create(null)
				)[event.type] || [],
				special = jQuery.event.special[event.type] || {};

			// Use the fix-ed jQuery.Event rather than the (read-only) native event
			args[0] = event;

          		for (i = 1; i < arguments.length; i++) {
				args[i] = arguments[i];
			}

### Link to test case ###

It is an Enterprise application, we couldn't replicate it via sample project. No test case attached.

**Comment by mgol** [comment] 2021-07-26 11:09
Thanks for the report. Unfortunately, we can't do much without a test case. Nothing in the line you highlighted looks suspicious so without a way to reproduce the issue we cannot do much.

**Comment by mgol** [comment] 2021-07-26 11:11
BTW, the code snippet you posted doesn't follow the jQuery code style, did you modify it? Modifying vendor files create a risk of introducing issues, I'd recommend keeping it unchanged.

**Comment by ArularasiA** [comment] 2021-07-27 06:46
Thanks for the comments. We have used the jQuery code exactly as in https://code.jquery.com/jquery-3.5.1.js. The style changes were due to auto-formatting on visual studio while including the code.

**Comment by mgol** [comment] 2021-11-24 13:51
Closing because of the lack of necessary information. We can reopen if you provide more details.

**Closed by mgol** 2021-11-24 13:51 UTC
Labels: Needs info

**Comment by goarblt** [comment] 2022-04-11 15:01
hello
https://www.evil.com

**Comment by sean-tillotson** [comment] 2022-12-03 17:53
I am running into same issue, same line.  jQuery is invoked for me when running 

`$(window).on('storage', <func>)` and will error out on the same line during a storageEvent
