### ISSUE TITLE
$.ajax with type jsonp not excute callback in ie11 when url response status is 204

### ISSUE THREAD

**Issue by honggook** [jquery/jquery#2587] opened 2015-09-10 05:20 UTC
>```javascript
>$.ajax({
>    type: 'GET',
>    url: 'http://127.0.0.1/nocontent.php', // url need cross domain and  response status 204
>    dataType: 'jsonp',
>    success: function () {
>        alert('success');
>    },
>    error: function () {
>        alert('error');
>    },
>    complete: function () {
>        alert('complete');
>    }
>});
>```

**Comment by markelog** [comment] 2015-09-10 09:49
Well, 204 means no content, whereas for `jsonp` transport you gotta have it

**Comment by honggook** [comment] 2015-09-11 02:42
hi @markelog 

ie6~ie10, firfox, chrome excute complete but ie11 not. Not tested Edge.
Can jQuery give same Behavior?

ie11 trigger error event when 204 status.
But jquery not bind onerror event to script tag.

In my case the url response 204 or 200 and correct data.
I need do something after jsonp request finished.

**Comment by markelog** [comment] 2015-09-11 06:57
Yeah, `complete` and `error` callbacks should have fired, checked on IE 11.0.10240, can't repro it  though

**Comment by honggook** [comment] 2015-09-11 10:09
@markelog

Can you test on win7 + 64bit + sp1?

IE 11.0.9600.17691IS

Thanks

**Comment by markelog** [comment] 2015-09-11 10:49
Previously tested on Windows 10, now on Windows 7 (browserstack version), can't repro.

Reopening for conformation.

**Comment by markelog** [comment] 2015-10-12 16:37
@mzgol, @timmywil could you conform?

**Comment by timmywil** [comment] 2015-10-12 19:26
Works for me in Windows 7, IE10 and IE11.

**Comment by timmywil** [comment] 2015-10-12 19:27
This was my test case: http://jsbin.com/vomiza/edit?js,console.

**Comment by markelog** [comment] 2015-10-12 19:34
Okay, i'm gonna close this for now then, @honggook if you find consistent way of reproducing it, please ping us up!

**Closed by markelog** 2015-10-12 19:34 UTC
Labels: Ajax, Needs review

**Comment by honggook** [comment] 2015-10-14 07:56
No message printed to console when run this test case on my IE11.
