### ISSUE TITLE
offsetParent fails to recognize 3D transform context

### ISSUE THREAD

**Issue by mgol** [jquery/jquery#1765] opened 2014-10-21 00:33 UTC
Originally reported by jlukic at: http://bugs.jquery.com/ticket/14956

<p>
According to W3C spec (and browser behavior) using a 3D transformation creates a new rendering context similar to <strong>position:relative;</strong> 
</p>

<p>
jQuery however will not return this as the offset parent, it will return incorrectly the closest container with position:relative;
</p>

<p>
See this JSFiddle: <a class="ext-link" href="http://jsfiddle.net/uUJDd/1/" rel="nofollow"><span class="icon">&nbsp;</span>http://jsfiddle.net/uUJDd/1/</a>
</p>

<p>
The absolute positioned element is relative to the 3D transformed context, but reports the wrong offsetParent
</p>

<p>
This is crucial for third party libraries which use jQuery (like my library Semantic UI) which need to determine correct offsetParent when using 3D contexts. 
</p><p>Issue reported for jQuery 2.1.0</p>

**Comment by markelog** [comment] 2015-01-13 07:02
From the `jQuery#offsetParent` <a href="http://api.jquery.com/offsetParent/">documentation</a> - 

> An element is said to be positioned if it has a CSS position attribute of relative, absolute, or fixed. 

So at least `offsetParent` method behave as it should, which means that this would be a behaviour change.

> The code size/speed issue has me worried as well if we have to make .offsetParent() always climb the tree from the element and ignore the DOM .offsetParent property.

and 

> We'd need to look for the a non-none transform (and -webkit-transform?) property in the method as we climb up the tree and there are probably other special cases not anticipated.

plus 

> This appears to be an open issues with the spec
...
Looks like nobodies decided what to do.

This sounds horrible - possible dirty workaround, perf and byte size hit. And since spec is incomplete we can stuck with some code and logic that we don't want?

Whereas fix for it on the user side, sounds like a pretty easy thing to do - add `position:relative` to the transform node? Although i understand that might be not that easy, at least not always.

> This is crucial for third party libraries which use jQuery (like my library Semantic UI) which need to determine correct offsetParent when using 3D contexts.

Should this library use their own algorithm for "offsetParent" search? Although given proposed logic, it's hard to call this method as `offsetParent`, since it would deviate from spec significantly.

**Comment by jlukic** [comment] 2015-01-13 21:04
The only use I know of getting offsetParent is to calculate `top` and `left` values relative to the local coordinate system. This means anyone using `$('.foo').offsetParent();` is expecting it to return the element which these offsets should be calculated.  With a transformed parent element, `offsetParent` is currently returning a value that has no practical use for developers.

jQuery became quite ubiquitous because it was very good at returning conforming values in an era where very few browsers implemented specs the same way. Even though the spec is undecided, it is certainly already implemented, and those implementations vary by browser. Why not try to solve this?

**Comment by markelog** [comment] 2015-01-13 22:16
Not my call to make, and i'm not against here, just discussion the subject, but sure, i can reiterate my concerns:

1. Spec isn't ready, we might stack with the code we don't want, but have to support
2. <a href="http://dev.w3.org/csswg/cssom-view/#dom-htmlelement-offsetparent">Spec</a> for `offsetParent` doesn't account transformation property
3. Related to `offsetParent` properties are explicitly <a href="http://dev.w3.org/csswg/cssom-view/#dom-htmlelement-offsettop">disregard</a> transformation properties
4. "Huge" impact on performance
5. Relatively big hit on byte size
6. More or less and edge case
7. Easy to fix on user side
8. Error-prone implementation

@bzbarsky maybe you could consult us here? Do we correctly interpret the spec(s)? And if so, how would you advise us to go about this?

**Comment by jlukic** [comment] 2015-01-14 00:08
I'm not talking about any massive changes. Here's some untested pseudo-code of how I would imagine this implemented. Is traversing `parentNode` properties that much slower? 

```javascript
offsetParent: function() {
  return this.map(function() {
    var parentNode = this.parentNode;

    while ( parentNode && jQuery.css( parentNode, "position" ) === "static" && jQuery.css( parentNode, "position" ) === "none" ) {
      parentNode = parentNode.parentNode;
    }

    return parentNode || documentElement;
  });
}
```

**Comment by markelog** [comment] 2015-01-14 00:26
Well, yes of course, imagine you have the DOM tree with 1000 elements deep, they have a root element with `position: relative` for others nor `position` nor a `transform` property is set. And user would like to know "offsetParent" (if we can still called it that) of the deepest element in that tree.

Now with current code - this is one loop iteration, with your code - this is 1000 loop iteration and for every single parent we would have to access its css, twice that is. Even if this could be considered as worst case scenario, it's still pretty bad.

**Comment by bzbarsky** [comment] 2015-01-14 02:45
@markelog You're correct that the built-in offsetParent/offsetLeft/offsetRight are not affected by transforms in the spec or implementations.

That's not the only problem with them.  They're generally pretty insane in terms of what the offsetParent is (e.g. compare the interaction with <td> to the interaction with pretty much any other block container), break in the face of subpixel layout (more and more of a problem with high-DPI displays, where subpixel things happen all the time), do weird stuff for `position:fixed` elements...  The upshot is that browsers and spec writers are basically treating these as legacy properties, which is why they aren't being changed in any way in response to transforms and whatnot.  Well, that, and it's not really clear what this sort of thing would even mean in a world with transforms.

In an ideal world, people would move away from these APIs to things like getBoundingClientRect/getClientRects and some sort of API to get rects for one element relative to another element; there have been various proposals for this that I can't locate at the moment.

So I think my advice would be to expose APIs along those lines and tell people to use them.  Ideally you can just map them directly to the browser's built-in APIs in modern browsers...

**Comment by jlukic** [comment] 2015-01-14 16:59
@bzbarsky You seem [in good company](http://ejohn.org/blog/getboundingclientrect-is-awesome/) in your suggestion. 

I think what's difficult, is that, with regards to UI, everything comes down to setting two values, `top` and `left` for positioning, which can only be set correctly in the context of the browser's positioning context, most likely what is returned by `offsetParent` but sometimes, not. 

It's a pity that there isn't a better way to do this, but we're limited by the primitive positioning system that CSS has left us with, where there's no certainty of the context without a bit of digging in javascript.

**Comment by mzgol** [comment] 2015-07-02 00:05
PR that might fix it: #2439 (I haven't added tests confirming that yet).

**Comment by mzgol** [comment] 2015-07-02 00:10
...or not, my mistake.

@bzbarsky We can replace `offsetWidth` & `offsetHeight` with `getBoundingClientRect().width` etc. but what can we replace `offsetParent` with? Is there anything?

**Comment by bzbarsky** [comment] 2015-07-02 03:59
That is, for the case of an absolutely positioned thing, a way to get the CSS containing block?  There's nothing I'm aware of offhand.  I agree that this is pretty suboptimal; we should probably add something.  Suggest it for the CSSOM?

**Comment by mzgol** [comment] 2015-09-16 15:24
Moving to 3.1.0 for now.

**Comment by markelog** [comment] 2015-09-16 15:48
> Moving to 3.1.0 for now.

We don't have a solution, i would suggest to remove label for now

**Comment by mzgol** [comment] 2015-09-16 16:06
> We don't have a solution, i would suggest to remove label for now

Yeah, you're right. I moved it to "Future" for now but we should probably decide what's "Future" and what's "no milestone" as the distinction is not clear to me. :)

**Comment by markelog** [comment] 2015-09-16 16:42
@mzgol btw, how about

> Suggest it for the CSSOM?

?

**Comment by timmywil** [comment] 2015-09-16 17:34
Future means that we want to do it, but we're not sure when. No milestone means it has not been accepted for development yet, or, more likely, we've neglected to set a milestone and the status is unknown.

**Comment by mzgol** [comment] 2015-09-16 18:34
Ok, seems Future is a good fit then.

-- 
Michał Gołębiowski

**Comment by timmywil** [comment] 2017-02-13 17:24
Closing as duplicate of #3479.

**Closed by timmywil** 2017-02-13 17:24 UTC
Labels: Needs review, Offset
