### ISSUE TITLE
jsdom error when using with node and npm

### ISSUE THREAD

**Issue by constellates** [jquery/jquery#2140] opened 2015-03-11 21:16 UTC
I have a project using jQuery inside an express app running on nodeJs. It has been working fine but I just switched to a new computer and rebuilt my environment and am now getting the following jsdom error. Let me know if you have any suggestions as to what I could look into.

/web-app/node_modules/jquery/node_modules/jsdom/lib/jsdom/level1/core.js:418
  set nodeName() { throw new core.DOMException();},
               ^
SyntaxError: Unexpected token )
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/zack/Projects/openbooks/web-app/node_modules/jquery/node_modules/jsdom/lib/jsdom/level2/core.js:1:94)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

**Comment by dmethvin** [comment] 2015-03-11 21:30
Can you point to your repo? The latest jsdom doesn't work with the latest node (only the latest io.js) so you probably have an issue unrelated to jQuery. Have you tried an `npm update` on your old computer to see if it breaks as well?

**Comment by constellates** [comment] 2015-03-11 21:37
Unfortunately the repo is closed source. It could definitely be a node version issue. I'm currently looking into rolling back from the latest node release. I also don't have my old computer with me currently. When I get home (~3 hours from now) I'll check my node version on it and then try running the project after an npm update. I'll report back with whatever I find. Thanks for the tip.

**Comment by mzgol** [comment] 2015-03-11 21:52
Yep, jsdom 4 only supports io.js, you need jsdom <=3 to work in Node, be it 0.10 or 0.12.

We're currently testing on 1.5.0, I'll get that updated; there's a small chance we'd be able to drop some jsdom-only workarounds if some of them are fixed in 3.x.

**Comment by constellates** [comment] 2015-03-11 22:06
I'm getting jsdom by installing jQuery through npm so I believe I'm running jsdom version 0.2.19 unless I'm missing something. The version listed in the package.json at node_modules/jquery/node_modules/jsdom/package.json is 0.2.19.

**Comment by mzgol** [comment] 2015-03-11 22:29
@constellates Unless you're doing an `npm install` directly in the jQuery repository, you won't get jsdom. If you do get it even though the `jquery` package is just a dependency, it means you're installing an old version of the `jquery` npm package (older than `1.11`); one that wasn't published by us but by a third-party before we took ownership. We can't help you there; you need to upgrade.

**Comment by constellates** [comment] 2015-03-11 22:32
Thanks for your help. Rolling back my node version did work around the issue. And you are correct, I currently have jquery 1.8.3. I'll try updating.

**Closed** 2015-03-11 22:40 UTC

**Comment by sohanpratap** [comment] 2015-11-29 07:45
I have installed node-strophe module. where jsdom have "0.2.19" version. But when I run my file i got the error. node_modules/jsdom/lib/jsdom/level1/core.js:418
  set nodeName() { throw new core.DOMException();},
And If i upgrade the jsdom version to 7.1.0 this error resolved But got new error 
node_modules/node-strophe/strophe.js:814
               if(elem.attributes[i].nodeName.toLowerCase() != "_realname") {
                                             ^TypeError: Cannot read property 'toLowerCase' of undefined.

my index.js file code:
var strophe = require('node-strophe').Strophe;
var Strophe = strophe.Strophe;
var BOSH_SERVICE = 'http://localhost:7070/http-bind/';
connection = new Strophe.Connection(BOSH_SERVICE);
connection.connect("abhishek@localhost","111111", onConnect);

I am running my file using "node index" and as requirement i don't need to run it through browser i only need to make the connection through  node-strophe and  BOSH and send message.

when i tried running it through browser and using strophe.js javascript library and with latest jsdom it workes fine but seems some problem with node-strophe module. Please help.

**Comment by mzgol** [comment] 2015-11-29 09:23
@sohanprstap Your issue doesn't seem to have anything to do with jQuery.

Also, the problem is different than the one reported; in such cases please open new bugs, don't resurrect the old ones.
