### ISSUE TITLE
appendTo vs. self-closing tag jquery >= 3.5

### ISSUE THREAD

**Issue by santaclaus21** [jquery/jquery#4830] opened 2021-01-13 11:55 UTC
Code:
`  $('<div class="popup" data-popup="iframe-1">'
			+ '<div class="popup-flex">'			
				+ '<div class="popup-inner">'
					 + '<iframe src="'+url+'" frameborder="0" height="100%" width="100%" />'
					 + '<a class="popup-close" data-popup-close="iframe-1" href="#">&#10005;</a>'
			+ '</div></div></div>').appendTo('body').fadeIn(600);`

After this code there is nothing after appended iframe:

![image](https://user-images.githubusercontent.com/1121662/104448757-debbad00-559d-11eb-9359-bbf8b162b8b9.png)

It was working fine before JQuery 3.5. But, if I replace self-closing iframe to <iframe....></iframe>, everything is working as expected:

`  $('<div class="popup" data-popup="iframe-1">'
			+ '<div class="popup-flex">'			
				+ '<div class="popup-inner">'
					 + '<iframe src="'+url+'" frameborder="0" height="100%" width="100%"></iframe>'
					 + '<a class="popup-close" data-popup-close="iframe-1" href="#">&#10005;</a>'
			+ '</div></div></div>').appendTo('body').fadeIn(600);`

Result: 
![image](https://user-images.githubusercontent.com/1121662/104449067-5093f680-559e-11eb-87f4-c23d48768762.png)

And now, code after iframe is not lost. Why ? I couldn't find any important notice in Jquery docs / appendTo.

**Comment by mgol** [comment] 2021-01-13 13:08
Please read the issue template, it provides this issue as a frequently reported one. This is covered by the [jQuery 3.5.0 blog post](https://blog.jquery.com/2020/04/10/jquery-3-5-0-released/) & the [upgrade guide](https://jquery.com/upgrade-guide/3.5/). Also, it's a duplicate of #4681, #4693, #4709, #4710, #4720, #4721, #4780 & #4823.

**Closed by mgol** 2021-01-13 13:08 UTC
