### ISSUE TITLE
elem.find(">selector") adds id="null" to elem

### ISSUE THREAD

**Issue by evgeniymweb100** [jquery/jquery#2740] opened 2015-11-24 12:20 UTC
elem.find(">selector") adds id="null" to elem
Reproduce steps:

- open FireFox, go to http://jquery.com
- open console in developer tools
- execute: $("html").find(">.zzz")
- go to inspector, look at root "html" node. It has id="null" attribute

In chrome id="null" is absent, but in developer tools "html" node blinks to indicate changes.

**Comment by mzgol** [comment] 2015-11-24 13:01
Duplicate of #2620.

**Closed by mzgol** 2015-11-24 13:01 UTC
