### ISSUE TITLE
SyntaxError jQuery v3.1.1 "el.querySelectorAll("*,:x");" //line 1361 Edge 14.14393 / Edge 38.14393.0.0

### ISSUE THREAD

**Issue by delmarwichnieski** [jquery/jquery#3551] opened 2017-02-24 13:25 UTC
/*!
 * jQuery JavaScript Library v3.1.1

 * Date: 2016-09-22T22:30Z
 */

Edge 38.14393.0.0
Edge 14.14393 / 

SyntaxError 
el.querySelectorAll("*,:x"); //this line 1361

inside this code

		assert(function( el ) {
			el.innerHTML = "<a href='' disabled='disabled'></a>" +
				"<select disabled='disabled'><option/></select>";

			// Support: Windows 8 Native Apps
			// The type and name attributes are restricted during .innerHTML assignment
			var input = document.createElement("input");
			input.setAttribute( "type", "hidden" );
			el.appendChild( input ).setAttribute( "name", "D" );

			// Support: IE8
			// Enforce case-sensitivity of name attribute
			if ( el.querySelectorAll("[name=d]").length ) {
				rbuggyQSA.push( "name" + whitespace + "*[*^$|!~]?=" );
			}

			// FF 3.5 - :enabled/:disabled and hidden elements (hidden elements are still enabled)
			// IE8 throws error here and will not see later tests
			if ( el.querySelectorAll(":enabled").length !== 2 ) {
				rbuggyQSA.push( ":enabled", ":disabled" );
			}

			// Support: IE9-11+
			// IE's :disabled selector does not pick up the children of disabled fieldsets
			docElem.appendChild( el ).disabled = true;
			if ( el.querySelectorAll(":disabled").length !== 2 ) {
				rbuggyQSA.push( ":enabled", ":disabled" );
			}

			// Opera 10-11 does not throw on post-comma invalid pseudos
			el.querySelectorAll("*,:x"); //here 1361
			rbuggyQSA.push(",.*:");
		});
	}

**Comment by dmethvin** [comment] 2017-02-24 13:49
Duplicate of https://bugs.jquery.com/ticket/13881

**Closed by dmethvin** 2017-02-24 13:49 UTC

**Comment by delmarwichnieski** [comment] 2017-02-24 14:39
Those are closed. Was this closed without a solution?

**Comment by dmethvin** [comment] 2017-02-24 14:40
Read the tickets. The exceptions are being thrown *and caught* by jQuery. They are expected.

**Comment by delmarwichnieski** [comment] 2017-02-24 14:42
ok

**Comment by SilvaJulian** [comment] 2018-01-04 18:40
Hi delmarwichnieski , how did you solve it?
