### ISSUE TITLE
Mouseleave incorrectly triggered on select boxes in some browsers

### ISSUE THREAD

**Issue by ilyavolodin** [jquery/jquery#3558] opened 2017-03-02 03:36 UTC
### Description ###
"mouseleave" event will be triggered on a parent element when child select box is opened and user hovers over available options. Repro case is linked below. This has been tested on IE11 (Windows 10) and Firefox 51.0.1 (OSX) with failed results. Latest Chrome on both Windows and OSX, Edge and Safari 10.0.3 are working correctly and do not trigger "mouseleave" event. This is happening with latest version of jQuery, but was also happening with version 2.x as well. As "mouseleave" is simulated event, I expected it to work the same way in all browsers.

### Link to test case ###

Link to repro case: https://jsfiddle.net/wukp7vv4/

**Comment by luis140219** [comment] 2017-03-02 17:01
Have you tested 1.12.4, 2.2.4 and 3.1.1?

**Comment by ilyavolodin** [comment] 2017-03-02 17:06
Yes, I verified it with 1.12.4, 2.2.4 and 3.1.1. All of them have the same issue.

**Comment by luis140219** [comment] 2017-03-02 17:44
I've just tested 1.12.4 on Windows 8.1. It also has the bug.

**Comment by dmethvin** [comment] 2017-03-06 01:55
In Windows 10 IE11 I see the problem [in this code](https://github.com/jquery/jquery/blob/ac9e3016645078e1e42120822cfb2076151c8cbe/src/event.js#L692). IE11 says `event.relatedTarget` is `null` indicating that it's leaving the enclosing div, that would normally mean it's leaving the browser window. Most likely this is due to IE's implementation of the browser control. Although jQuery uses mouseout to simulate mouseleave, it appears that the IE11 native mouseleave suffers the same problem and fires when you move into the opened select.

I couldn't reproduce the issue on Windows 10 Firefox 51 but perhaps on iOS Firefox has the same problem.

I don't see a workaround here, do you? If not I'm inclined to close this as a cantfix.

**Comment by ilyavolodin** [comment] 2017-03-06 03:17
@dmethvin The way I worked around this issue is by adding this code:

```js
$('.mini-cart').on('mouseleave', function (event) {
  if ($('mini-cart').has(event.target).length > 0) {
    event.stopPropagation();
    return;
  }
  // process leave event here
});
```

You are correct,  `event.relatedTarget` is set to `null`. That's what I've tried first. But `event.target` is set to the select box. So verifying if current target is part of the element that has event registered on it seems to work for both IE on Windows, and Firefox on OSX.

**Comment by timmywil** [comment] 2017-03-27 16:48
We looked into this and we're not sure we can fix this from jQuery's side. If anyone comes up with a solution, please feel free to post here and we'll re-open.

**Closed by timmywil** 2017-03-27 16:48 UTC
Labels: Event, Needs review
