### ISSUE TITLE
Mouseenter and disabled elements

### ISSUE THREAD

**Issue by Ser-Gen** [jquery/jquery#2558] opened 2015-08-25 20:09 UTC
My plugin needs to handle mouseenter on elements, which can contain some disabled elements.
It can't do that because of this issue.

Test case with jQuery and pure event handlers:
http://jsfiddle.net/SerGen/unhturm4/

Find related issue: [#11382](http://bugs.jquery.com/ticket/11382), but it can't satisfy me — I need this events.

**Comment by mzgol** [comment] 2015-08-25 20:19
Confirmed: http://jsfiddle.net/unhturm4/5/. Thanks for the report.

**Comment by adityabad** [comment] 2015-08-30 17:24
I am new here .Is there any way that i can be of help to fix this issue .Can you help me understand this issue ?

**Comment by dmethvin** [comment] 2015-08-31 13:32
jQuery uses `mouseover` to implement `mouseenter` because the W3C says `mouseenter` [does not bubble](https://w3c.github.io/uievents/#event-types-list), which makes it impossible to use for delegated events. However, that test case from @mzgol seem to show Chrome is bubbling `mouseenter` even though it isn't supposed to do that. 

jQuery also used `mouseover` because originally `mouseenter` was not in the standard and only IE implemented it. I'm not sure whether all our supported browsers now have `mouseenter`, and whether they implement it "properly" whatever that means. (Should we depend on them to not follow the spec and bubble the event?)

Although that test breaks on Chrome and Firefox it works fine on IE11. There is nothing in the spec that says browsers should suppress a `mouseover` event from a disabled element, so I am not sure why they are doing so. The [spec says](http://www.w3.org/TR/html5/forms.html#enabling-and-disabling-form-controls:-the-disabled-attribute) "A form control that is disabled must prevent any click events that are queued on the user interaction task source from being dispatched on the element."

So we're in a bit of a pinch here. Chrome and Firefox should fix their implementations to not suppress `mouseover` or we should get the spec to say it *must* be suppressed (because why). We could change to use native `mouseenter` if we can get the spec changed to say that the event bubbles, or a commitment to that change.

**Comment by mzgol** [comment] 2015-08-31 14:07
> However, that test case from @mzgol seem to show Chrome is bubbling mouseenter even though it isn't supposed to do that.

It doesn't bubble. What happens here is that since you hover the div and *at the same time* hover the button, the native `mouseenter` is fired on both of them independently. Now, since the button is disabled it doesn't fire on the button but still does on the div. You can check that by hovering over the div-only part and then moving over the button - no native `mouseenter` fires then.

> I'm not sure whether all our supported browsers now have mouseenter, and whether they implement it "properly" whatever that means.

Chrome, Firefox, Edge & IE support it. Safari does in 7+ (or before, not sure, but we support 7+ anyway) but Safari 7 has a [critical bug](https://code.google.com/p/chromium/issues/detail?id=470258) so we can't use its implementation. It has been fixed in Safari 8.

We need [delegated events to work with jQuery's `mouseenter` & `mouseleave`](https://github.com/jquery/jquery/blob/9d820fbde6d89bc7a06e2704be61cf6c0b4d6e3c/src/event.js#L772-L774), though so I'm not sure if we can switch to the native implementation at all. Am I missing something? Why do we not have to do this for `focus`/`blur` in IE?

> Although that test breaks on Chrome and Firefox it works fine on IE11.

It works in Edge as well, they didn't copy Chrome here. :)

> So we're in a bit of a pinch here. Chrome and Firefox should fix their implementations to not suppress `mouseover` or we should get the spec to say it must be suppressed (because why)

Good point.

> We could change to use native mouseenter if we can get the spec changed to say that the event bubbles

Bubbles? How so? Also, please see what I wrote about event delegation above.

**Comment by dmethvin** [comment] 2015-08-31 14:25
You're right @mzgol, I misinterpreted the event as bubbling but `event.target` is definitely showing `div#a` so it's just from entering the div. I think we really need browsers to allow `mouseover` on disabled elements if we want this to work right.

For `focus` and `blur` we use `focusin` and `focusout` instead since they bubble.

**Comment by mzgol** [comment] 2015-08-31 15:27
> For `focus` and `blur` we use `focusin` and `focusout` instead since they bubble.

We rely on native `focusin`/`focusout` only in IE as Firefox doesn't have them at all and other browsers don't pass the `support.focusin`.

I've checked, we use regular `focus` but [in the capture phase](https://github.com/jquery/jquery/blob/9d820fbde6d89bc7a06e2704be61cf6c0b4d6e3c/src/event.js#L830). This would work for `mouseenter` as well: https://jsfiddle.net/unhturm4/19/ but still nothing fires when you hover over the disabled button.

The real problem here is that if you hover on the disabled button without an intermediate step in the form of hovering over just the div (i.e. the button touches the border of the div) then native `mouseenter` fires but native `mouseover` doesn't, either in bubble or capture phase: https://jsfiddle.net/unhturm4/18/.

So the only way for us to fix it would be to rely on the `mouseenter`/`mouseleave` capture phase where available, similarly to how we treat `focus`/`blur`. That might be doable. I'd still like to know first if this behavior is standards-intended, though; but even if it's not & Chrome & Firefox fixes their behavior we'll still have to patch it for Safari. Also, the workaround is to attach one handler for the capture phase & simulate the regular one so this might have performance implications; we'd need to measure it to make sure we're not regressing too much.

**Comment by dmethvin** [comment] 2015-08-31 15:57
I think it's wrong that mouse events other than click don't fire on disabled elements, so we should find out whether that can be changed because I don't think there's a way for us to work around it at all.

I assume the goal of the fix is to find out whether the mouse is over a disabled element. If so we don't have a lot of options: http://jsfiddle.net/unhturm4/20/

The `mouseenter` fires on the parent, but the `target` is *not* the button so we can't tell if it's hovering the button.

**Comment by dmethvin** [comment] 2015-08-31 17:52
In today's meeting @mzgol pointed out that there are really two issues here and the specific issue being reported could be addressed without dealing with the root cause of disabled elements not firing `mouseenter` or `mouseover` events. It's a pretty specific edge case though, and any radical change we did (for example, switching to `mouseenter` directly when possible) is likely to encounter bugs like the one mentioned for Safari.

I'm going to ping a few folks to find out if there is a reason for what we're seeing before we look at changing code. The behavior here doesn't seem to be required by the spec, and prevents useful things like info tooltips on disabled buttons.

**Comment by dmethvin** [comment] 2015-09-09 17:07
The followup here is that everyone but IE seem to be doing this wrong, and have been doing it wrong forever. We might be able to fix a few edge cases but we can't fix the general issue of disabled elements not firing mouse events. I'm not convinced fixing the edge cases is worth the risk of encountering additional bugs with mouseenter (including known Safari bugs) since we've never used it.

https://bugzilla.mozilla.org/show_bug.cgi?id=218093

**Comment by timmywil** [comment] 2015-09-21 16:10
We don't think this is worth a workaround in jQuery. We'd happily review a patch, but we predict any attempt at a fix will cause more issues that outweigh this one. Fortunately, Mozilla has agreed to fix this on their end and we will push for a fix from the other vendors.

**Closed by timmywil** 2015-09-21 16:10 UTC
Labels: Bug, Event, Needs review
