### ISSUE TITLE
Change in behaviour for .data(), hasOwnProperty no longer works.

### ISSUE THREAD

**Issue by ghedwards** [jquery/jquery#4690] opened 2020-04-27 23:25 UTC
### Description ###
Change in behaviour for .data(), the line of code below no longer works in 3.5.0

`$('<div></div>').data().hasOwnProperty('test')`

**Comment by ianva** [comment] 2020-04-28 04:06
Me too, We have a lot of legacy project errors because of the early based on bower, no freeze version.

**Comment by mgol** [comment] 2020-04-28 06:41
Duplicate of https://github.com/jquery/jquery/issues/4665. Will be fixed in 3.5.1.

**Closed by mgol** 2020-04-28 06:41 UTC
