### ISSUE TITLE
jQuery animate with radius is throwing exception in firefox

### ISSUE THREAD

**Issue by bharathirajauk** [jquery/jquery#3238] opened 2016-07-19 05:04 UTC
I am using jQuery-3.0 version animate method which throws console error on animating SVG circle element by radius in Firefox browser only. Open the below link in IE and Firefox. In IE it is animated properly. Firefox throws console error and circle was disappear. In JQuery-2.2.4 working fine in all browser.

https://jsfiddle.net/bxmgqnq3/1/

**Comment by dmethvin** [comment] 2016-07-19 16:21
In general we don't support SVG in jQuery, it may look like HTML because it uses `<tags>` but it often has a completely different set of rules for its DOM. I'm not seeing any animation happening in Chrome using jQuery 2.2 or 3.0 either so this is *not* a regression for all browsers afaict.

The fact that it works on IE or previous versions shouldn't be taken as a sign that SVG animation was supported. I haven't looked into exactly *why* it's failing so I'll leave the ticket open for others to check, maybe there is something more general wrong with it.

**Comment by mgol** [comment] 2016-07-19 17:55
According to [the docs](https://api.jquery.com/animate/#animate-properties-options) you can only animate along the CSS properties of an element. That doesn't seem to be 100% true as [we have code that animates properties if the name doesn't match a CSS property](https://github.com/jquery/jquery/blob/3.1.0/src/effects/Tween.js#L91-L93) (does anyone know what's the purpose of that? @gnarf?).

In any case, `jQuery#animate` animates CSS properties or regular properties and on a `<circle>` element the `r` property is read only in Chrome/Firefox (the only difference is that in strict mode Chrome just ignores the assignment and Firefox throw an error). In IE, apparently, the property works as a setter. It's fixed in Edge, though, where it throws as in Firefox.

In the fiddle you're animating the attribute manually via the `step` function which is the correct way. Unfortunately, there doesn't seem to be the way to just animate the attribute, it has to be based on a property; you can create a custom property, though just for animating purposes:
https://jsfiddle.net/bxmgqnq3/8/

Should we have a better way to animate attributes?

**Comment by dmethvin** [comment] 2016-07-19 21:19
On animating non-CSS, We have kinda-sorta tolerated animating properties in a plain object although it's not documented, see https://github.com/jquery/api.jquery.com/issues/600 and https://github.com/jquery/jquery/issues/1886. However, yes we assume it's a property and not some other thing to set on each step. I suppose we could have a setter hook in the options and make that set the property by default, but it could be overridden to set an attribute or write the value to a latch for an LED output or whatever.

**Comment by mgol** [comment] 2016-07-30 15:40
Let's discuss it on the next meeting.

**Comment by timmywil** [comment] 2016-08-08 16:57
Per the meeting, we decided not to support animating attributes. More attributes will be settable in CSS in the near future and then you can use CSS to animate, but for now, the work around is to override the step function (https://jsfiddle.net/bxmgqnq3/8/).

**Comment by timmywil** [comment] 2016-08-08 16:57
As far as making plain object support official, we have [this ticket](https://github.com/jquery/jquery/issues/1776).

**Closed by timmywil** 2016-08-08 16:57 UTC
Labels: Effects, Needs review
