### ISSUE TITLE
find() with pseudo selectors behaves strangely in DOM

### ISSUE THREAD

**Issue by Ceremony64** [jquery/jquery#2620] opened 2015-09-30 09:46 UTC
Take a look at the following example: http://jsfiddle.net/9sLmusLo/

In Firefox, look at the DIV within the developer tools inspector and then click on it. The attribute  `id="null"` gets added or, on a subsequent click, removed, however the css styling does not get applied. Closing and opening the dev tools again also removes the `id`.

If you do the same in Chrome and its dev tools, the DIV element just flashes, indicating some sort of change. No `id` gets set however.

IE seems to do nothing. Good.

This seems to happen when there is no `id` for the element set and whenever a pseudo selector is being used. Might also not just be restricted to the `find` method.

**Comment by Mr21** [comment] 2015-09-30 12:11
Yeah right.

You can prove it by adding this at your fiddle:

``` javascript
MutationObserver = MutationObserver || WebKitMutationObserver;
new MutationObserver( function( mutations ) {
    console.log( "change" );
}).observe( $( "div" )[ 0 ], {
    attributes: true
});
```

**Comment by dmethvin** [comment] 2015-09-30 14:21
This is a result of the current DOM methods like `querySelector` lacking a true rooted selection method. Sizzle's workaround is to temporarily apply an `id` to the root so that it can be used in the selector. The new [find/findAll](http://www.w3.org/TR/selectors-api2/#findelements-relative) methods should fix this but nobody seems to have it implemented.

**Comment by mzgol** [comment] 2015-09-30 14:22
@dmethvin The question is why it applies `id="null"` in the case presented here. Sounds like a bug.

**Comment by dmethvin** [comment] 2015-09-30 14:27
I think it's a bug, but in FF dev tools. Note that reopening the tools makes it go away, so it's just a phantom thing and not really `id="null"` on the element.

**Comment by mzgol** [comment] 2015-09-30 14:54
@dmethvin Ha, indeed! I had to recreate it on jsbin.com to escape this iframe madness, if you open http://output.jsbin.com/wuzumev in Firefox you'll see `id="null"` in Dev Tools but `document.getElementById('null')` returns `null` and `$0.hasAttribute('id')` returns `false` when you highlight the div.

@Ceremony64 Could you report it to Mozilla at https://bugzilla.mozilla.org/ and post the link here? I'll close this issue since this is not our bug.

**Closed by mzgol** 2015-09-30 14:54 UTC

**Comment by Ceremony64** [comment] 2015-09-30 15:17
Here we go: https://bugzilla.mozilla.org/show_bug.cgi?id=1209993

**Comment by Mr21** [comment] 2015-09-30 17:07
But, are you sure it's not a problem that the `MutationObserver` fired an event for that??

**Comment by dmethvin** [comment] 2015-09-30 17:11
The element *was* changed, to add and remove the `id`.

**Comment by Mr21** [comment] 2015-09-30 18:08
@dmethvin I understood sizzle doing that so. But even if the `id="null"` was removed on Firefox, I think it's also a problem.

Why Sizzle don't do a simple thing like: `domElement.__sizzle = "null";` or something else, why modifying the `id` explicitly...

**Comment by dmethvin** [comment] 2015-09-30 18:14
If the root element has an `id` already (as it sometimes does) it can be used. Otherwise one is temporarily added. 

> Why Sizzle don't do a simple thing like: domElement.__sizzle = "null"; or something else, why modifying the id explicitly...

Does modifying a property rather than an attribute prevent `MutationObserver` from firing? If not we've gone from sometimes mutating the DOM (only when an `id` isn't present) to always doing it, which probably isn't good.

I'll let @timmywil or @gibson042 weigh in on whether using a property would help, if so it should be opened as a Sizzle ticket.

**Comment by Mr21** [comment] 2015-09-30 18:19
> Does modifying a property rather than an attribute prevent MutationObserver from firing?

Yeah sure... the mutation doesn't detect the change of the `value` of an input element... there is no way to detect a change on a property sadly :/

**Comment by mzgol** [comment] 2015-09-30 18:20
@Mr21 
> Why Sizzle don't do a simple thing like: domElement.__sizzle = "null"; or something else, why modifying the id explicitly...

We need `querySelectorAll` to work so it has to be an attribute because you can't select on arbitrary properties.

@dmethvin 
> Does modifying a property rather than an attribute prevent MutationObserver from firing?

Which property? Every property change that's reflected in a property will result in a MutationObserver firing. Unless I don't understand what you propose here?

**Comment by Mr21** [comment] 2015-09-30 18:34
> Which property? Every property change that's reflected in a property will result in a MutationObserver firing. Unless I don't understand what you propose here?

I proposed something to not fired mutationObserver. MutationObserver is only for the DOM. So it can detect the attribute change in the DOM. But not a property in JS
I think `Object.observe` will be able to do that in the future ES7...

**Comment by mzgol** [comment] 2015-09-30 18:43
@Mr21 As @dmethvin said, `id` is set so that we can use it in `querySelectorAll`. What would you do with a property?

**Comment by Mr21** [comment] 2015-09-30 18:51
Yep, I didn't know that fact sorry.

I didn't understand (again) why qSA needs an `id`.
Because, as you know, we can do:
`domElement.querySelectorAll( selector );` instead of something like:
`domElement.id = "unique"; document.querySelectorAll( "#unique " + selector );`

**Comment by gibson042** [comment] 2015-09-30 20:02
`el.querySelectorAll("foo bar")` matches all `bar` elements under `el` that have a `foo` ancestor, even if that `foo` is _also_ an ancestor of `el`. In the following example, it matches both desired and undesired:
```html
<foo>
  <context>
    <foo>
      <bar class="desired"/>
    </foo>
    <bar class="undesired"/>
  </context>
</foo>
```

To remedy this, we prefix selectors to ensure descendance from the context element (e.g., `foo bar` → `#<context-id> foo bar`). But if the context doesn't already have an id, we [add one for just long enough to execute the selection](https://github.com/jquery/sizzle/blob/51f87d087ac68f897c56fe5229f56105b36ba5d0/src/sizzle.js#L279-L317). Note also that in those cases, we clean up with `removeAttribute("id")`—at no point does the attribute ever exist with a `null` value.

**Comment by markelog** [comment] 2015-09-30 21:59
Our qSA logic is explained long time ago - http://ejohn.org/blog/thoughts-on-queryselectorall/ and since this is not a support forum...

**Comment by dmethvin** [comment] 2015-09-30 22:24
It's sad that John pointed out the drawbacks of `qSA` seven years ago and the DOM API implementations still don't have [find/findAll](http://www.w3.org/TR/selectors-api2/#findelements-relative) yet despite all those years of jQuery user code proving that they're useful. #youmightnotneedjquery

**Comment by Mr21** [comment] 2015-09-30 22:42
Thanks a lot @gibson042 I didn't know that huge fact about qSA... Oo
But to be clear I know you clear the `id` but I know jQuery has to be the most quiet possible, and just 4 hours ago, I found that jQuery can make an event fired just by reading the DOM. It's sound clearly like a bug. But it's not a bug, it's a feature so... :+1:

**Comment by mgol** [comment] 2019-08-19 16:58
@Ceremony64 I just landed a PR that achieves what we need via different means for most selectors: #4454. This will land in jQuery 4.0.0 and maybe we can do it in 3.4.2 as well.
