### ISSUE TITLE
String Variable Within Script Tag Transformed for Closing Tag 

### ISSUE THREAD

**Issue by kunalkumar** [jquery/jquery#3648] opened 2017-04-27 13:46 UTC
### Description ###
Consider a simple string as 

`var simpleHTMLString = "<a> anchor content </a><script> var abc ='There is <javascript://> in plain text tag'</script> <a>test content again</a>"`

Please note that the above string consists of three node (a, script, a) which we are looking to transform using parseHTML. 

When we do 

`var htmlNodes = $.parseHTML( simpleHTMLString, true);`

as expected, we get three node. however if look at the content of second node, script, we get the following content 

```
console.log( htmlNodes[1].outerHTML );
" var abc ='There is <javascript:/></javascript:> in plain text tag'"
```

Notice that how "<javascript://>" gets transformed to "<javascript:/></javascript:>" - As far as I understand, function buildFragment tries to convert HTML into nodes and uses regex search and replace due to which closing tag is transformed again for correctness. 

However, anything within "<script>" tag should never be transformed again as it could potentially change any internal variable which may lead to incorrect behavior in application.

**Comment by gibson042** [comment] 2017-04-28 05:31
This is a duplicate of gh-2205. We opted to leave such edge cases unresolved by the standard distribution because the amount of code to fix them is rather large, but you can do so with the custom HTML prefilter from http://api.jquery.com/jQuery.htmlPrefilter/ : https://jsfiddle.net/3udaf007/

**Closed** 2017-04-28 05:31 UTC
