### ISSUE TITLE
Incorrect role as 'link' is defined for the 'Name' column header sorted table button.

### ISSUE THREAD

**Issue by msftedad** [jquery/jquery#5087] opened 2022-08-11 12:54 UTC
**Test Environment**
OS: Windows_11
Version: 21H2
OS Build: 22000.795
Browser: Version 103.0.1264.71 (Official Build) (64-bit)
URL: [eeee - Usage report - Skype Manager - Skype](https://nam06.safelinks.protection.outlook.com/?url=https:%2f%2fmanager.skype.com%2fmember%2freports%2fusage?user%3Dlive:hcltester200&data=05%7c01%7cv-knarang%40microsoft.com%7ceabcdd9a360b46141ff808da63f23a34%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c637932189379703390%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c3000%7c%7c%7c&sdata=p3oQcsdoH9r%2B9cyEYkxRiAGCsk%2f%2fj8pvYsYLrZ1JveM%3D&reserved=0)
Screen Reader: Narrator
User: hcltester200@outlook.com

**Repro Steps:**
1. Open the above-mentioned app.
2. Login with valid credentials. 
3. Turn on Narrator via 'Ctrl+Win+Enter' keys.
4. Navigate to the ‘Features’ tab and activate it.
5. Allocate the skype credit then navigate to ‘Name’ column header.
6. Observe the issue here.

**Actual Behavior:**
Incorrect role as 'link' is defined for the 'Name' column header sorted table button.

**Expected Behavior:**
Correct information for 'Name' column header sorted table button should be announced by the narrator as 'Name button column header name then row information'.

https://user-images.githubusercontent.com/93735775/184137716-018d6a40-b70f-4e96-9cf7-31e5bce719a9.mp4

<img width="956" alt="Code snippet (1)" src="https://user-images.githubusercontent.com/93735775/184137756-6d832414-5658-4993-860d-1f06206774a6.png">

**Comment by ThakurAnkur** [comment] 2022-08-11 13:11
This is not jQuery issue, I think you should reach out to site/app owners for intended behavior.

**Comment by mgol** [comment] 2022-08-11 13:17
Yes, it definitely doesn't look like a jQuery issue. Closing.

**Closed by mgol** 2022-08-11 13:17 UTC
