### ISSUE TITLE
.sort removed in jquery 4.0 what is the alternative?

### ISSUE THREAD

**Issue by BackuPs** [jquery/jquery#5539] opened 2024-08-25 14:36 UTC
I know this should probably not being asked here but.

I am testing jquery 4.0 and found that many scripts use jquery.sort method which has been stripped from jquery 4.0 resulting in a function does not exist error.

But what is the alternative?

If i have a jquery object with all elements with a certain class i could just use

f.e.

`
this.$slides = this.$ul.children().addClass(namespace + '-item');

self.$slides.sort(function() {
return (Math.round(Math.random()) - 0.5);
});
self.$ul.empty().append(self.$slides);`

Removing these functions withour deprecating messages and a alternative is not a good idea.

But in jquery 4.0  you can not use this anymore.  How to sort the elements in the jquery object without loosing the rest of the object?

Can somebody provide me a solution to this?

Thank you

**Comment by BackuPs** [comment] 2024-08-26 08:02
What i need to know is how to rewrite this .filter.sort function so it works in jquery 4.0

`  function frameAppend ($frames, $shaft, type) {
    if (!frameAppend[type]) {

      var thumbsFLAG = type === 'nav' && o_navThumbs,
          left = 0;

      $shaft.append(
        $frames
            .filter(function () {
              var actual,
                  $this = $(this),
                  frameData = $this.data();
              for (var _i = 0, _l = data.length; _i < _l; _i++) {
                if (frameData.data === data[_i]) {
                  actual = true;
                  frameData.eq = _i;
                  break;
                }
              }
              return actual || $this.remove() && false;
            })
            .sort(function (a, b) {
              return $(a).data().eq - $(b).data().eq;
            })
            .each(function () {

              if (!thumbsFLAG) return;

              var $this = $(this),
                  frameData = $this.data(),
                  thumbwidth = Math.round(o_thumbSide2 * frameData.data.thumbratio) || o_thumbSide;

              frameData.l = left;
              frameData.w = thumbwidth;

              $this.css({width: thumbwidth});

              left += thumbwidth + opts.thumbmargin;
            })
      );

      frameAppend[type] = true;
    }
  }`

**Comment by mgol** [comment] 2024-08-26 22:05
`push`, `sort` & `splice` were exposed for internal use, they were never a public API documented at https://api.jquery.com/. For us, deprecation mainly means documenting an API as deprecated - which you cannot do with an API that's not documented at all. We do plan to add warnings to jQuery Migrate, there's an open issue for that at https://github.com/jquery/jquery-migrate/issues/473.

We don't encourage using these APIs as modifying elements of a jQuery object messes up some internal structures, e.g. the [`end`](https://api.jquery.com/end/) API may not work as intended, a new jQuery object is not returned (contrary to other APIs), etc.

If you really want, you can borrow the APIs from Array prototype:
```js
Array.prototype.sort.call( $elem, sortingFunction );
```
or convert to an array first:
```js
$elem.toArray().sort( sortingFunction );
```

I'm going to close the issue for now, but feel free to continue the discussion.

P.S. Please read https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks on how to format code blocks on GitHub so that they're readable.

**Closed by mgol** 2024-08-26 22:05 UTC
