### ISSUE TITLE
$('a[title="Edit this page [alt-shift-e]"]') fails to select in Edge

### ISSUE THREAD

**Issue by brianfreud** [jquery/jquery#3652] opened 2017-05-01 02:50 UTC
Selecting the "Edit" link on a stock install of MediaWiki, using $('a[title="Edit this page [alt-shift-e]"]') works fine in Chrome and Firefox, but fails in Edge.  I'd guess perhaps due to the [] within the title?  $('a[accesskey="e"]') on the other hand works fine.

The raw HTML for the link looks like <a href="/w/index.php?title=MediaWiki:blah&amp;action=edit" title="Edit this page [alt-shift-e]" accesskey="e">Edit</a>

There's a test fiddle at https://jsfiddle.net/scn3tso0/

**Comment by mgol** [comment] 2017-05-01 11:29
I can't confirm it. Your test case works for me the same in Chrome, Firefox, Edge 15, 14 & 13. Could you make sure it's correct and/or provide more info?

**Comment by dmethvin** [comment] 2017-05-01 11:44
Works for me as well, Microsoft Edge 38.14393.1066.0

**Comment by brianfreud** [comment] 2017-05-01 20:16
I only noticed it after a beta tester reported problems under Edge.  Confirmed from my end on pages such as http://stratics.com/w/index.php?title=UO:Flame_Elemental (login required to be able to edit) running Edge latest via at browserstack.  I worked around it by switching to the accesskey selector.

**Comment by mgol** [comment] 2017-05-17 18:41
Since we have no reproducible test case I'm going to close it. If you find something that consistently breaks in stable Edge version, please post here & we'll reopne.

**Closed by mgol** 2017-05-17 18:41 UTC
Labels: Needs info
