### ISSUE TITLE
2.2.0 breaking change

### ISSUE THREAD

**Issue by Billy-** [jquery/jquery#2876] opened 2016-01-27 09:50 UTC
Not sure if this is a bug per se, as I think it's technically a syntax error, but on the release notes for jQuery 2.2.0 it say it is not expected to have any breaking changes so I thought I would report this in case.

So, I have this line:

    var a = $("a[href*=#]:not([href=#])");

This line works fine on 2.1.4, but throws this error on 2.2.0:

    Syntax error, unrecognized expression: a[href*=#]:not([href=#])

Quoting the values in the attribute selectors fixes this (i.e. `[href*='#']`). But as I said, I'm not sure if this is an intended fix or a regression.

**Comment by mgol** [comment] 2016-01-27 10:24
Thanks for the report. This is a duplicate of #2824.

Technically speaking a breaking change means that something that **was allowed by the documentation** broke in a new release. Breaking unofficial APIs, not supported edge cases etc. is not a breaking change. We've never asserted we're supporting such invalid CSS selectors, they were working by accident so we're allowed to change this behavior in a non-major release.

That said, we were aware this might break some code, that's why we put it in a minor release, not a patch - we try patch releases to not break even undocumented stuff where possible.

**Closed by mgol** 2016-01-27 10:24 UTC

**Comment by Billy-** [comment] 2016-01-27 10:33
Thanks for clearing that up, and sorry for not finding the dupe! I had a feeling that it would be the case that breaking undocumented working syntax would not be considered a breaking change, but thought it would be better to report it as I was unsure!

**Comment by mgol** [comment] 2016-01-27 10:39
Sure, nothing wrong with reporting that. :) And while it's a good idea to always search for existing bugs before reporting it's not always trivial to find them. No worries!
