### ISSUE TITLE
jquery 1.12.0 breaks jquery-ui Slider v1.9.2

### ISSUE THREAD

**Issue by metantonyb** [jquery/jquery#2817] opened 2016-01-12 01:05 UTC
I upgraded jquery from 1.8.2 to 1.12.0 and this breaks the jquery-ui Slider with the error "Uncaught TypeError: Cannot read property 'opener' of null" in Firefox (41.0.2), Chrome ( 47.0.2526.106 m) and IE (11.0.9600.18124).

I have tried upgrading to jquery 1.11.3 and the Slider still works as expected so this issue only affects 1.12.0

I have also tried upgrading the slider to jquery-ui 1.11.4 with jquery 1.12.0 and it still fails with the above error.

**Comment by scottgonzalez** [comment] 2016-01-12 02:33
Duplicate of #2814.

**Closed by scottgonzalez** 2016-01-12 02:33 UTC
