### ISSUE TITLE
jQuery 3.4 errors with src directory webpack alias

### ISSUE THREAD

**Issue by almercier** [jquery/jquery#4358] opened 2019-04-16 16:31 UTC
We've received errors going from 3.3.1 to 3.4.0 with loading jquery through webpack.
I'm noticing that the errors no longer appear after removing the alias we are using in webpack for jquery [per this user's SO suggestion #1](https://stackoverflow.com/a/28989476)

```javascript
resolve: {
    alias: {
        // Alias `import $ from 'jquery'` to resolve to the src JS file
        jquery: 'jquery/src/jquery'
    },
},
```

We are loading and using jquery per webpack's suggestion [here](https://webpack.js.org/plugins/provide-plugin/#usage-jquery)
```javascript
// Load jquery
new webpack.ProvidePlugin({
    $: 'jquery',
    jQuery: 'jquery',
}),
```

The error for me is happening when we call jquery-ui "draggable" on a jquery wrapped element.
`Cannot read property 'position' of undefined. finalPropName.js:26` which is on the following line `var final = jQuery.cssProps[ name ] || vendorProps[ name ];`. Upon debugging on that line immediately before the error is thrown, I am seeing that the variable `jQuery` is just an empty object while `window.jQuery` is the actual jQuery instance...

Is this a bug and/or undocumented breaking change in the src/jquery.js file of the new version?

**Comment by timmywil** [comment] 2019-04-16 17:56
Thanks for opening an issue, but there were no changes to the `src/jquery.js` file itself or the way it is loaded with AMD. You can see exactly what we distribute at [this repo](https://github.com/jquery/jquery-dist). This issue is pretty vague. If you're able to narrow it down and provide a small test case from https://jsbin.com that reproduces the error you're seeing in combination with draggable, feel free to post it here and we can reopen.

**Comment by dmethvin** [comment] 2019-04-17 00:25
I think the error is caused by `finalPropName.js` not referencing `jQuery` via `"../core"` in the AMD function definition. So, it ends up using the global `jQuery`. We probably don't have a test that would cause this to fail.

**Comment by timmywil** [comment] 2019-04-17 01:23
Interesting. I ran tests in AMD mode and didn't see this, but you're right.

**Comment by dmethvin** [comment] 2019-04-17 01:37
Yeah not sure why, we must have somehow polluted the global space with a jQuery in AMD mode.

**Comment by almercier** [comment] 2019-04-17 12:37
Would it be helpful if I made a super simple public repo with instructions that reproduce? It doesn't seem like it would be possible to repro on something like jsbin.

**Comment by almercier** [comment] 2019-04-17 12:52
> So, it ends up using the global jQuery. We probably don't have a test that would cause this to fail.

This would make sense as to why it might be erroring for me, as [loading jquery through webpack's providePlugin does not inject jquery to the global namespace.](https://stackoverflow.com/questions/29080148/expose-jquery-to-real-window-object-with-webpack)

**Comment by mgol** [comment] 2019-04-17 13:28
PR: #4361 

@almercier The biggest help right now would be if you applied the code from PR #4361 in your `node_modules` locally and checked if it resolves your issue. If that's the case, the fix will be included in jQuery 3.4.1.

@dmethvin Sorry, I didn't notice your assignment to this issue & I submitted a PR myself. We can still investigate why tests worked in AMD mode at all, i.e. how come the global jQuery was available.

**Comment by almercier** [comment] 2019-04-17 13:45
@mgol swapping with #4361 resolved my issue 👍

**Comment by mgol** [comment] 2019-04-17 14:08
Thanks for confirming!
-- 
Michał Gołębiowski-Owczarek

**Comment by dmethvin** [comment] 2019-04-17 15:11
No problem @mgol, any time I can get someone to clean up my mess I'm happy! I will look into why there's a global jQuery, The global `jQuery` is coming from [jQuery 1.9.1 in index.html](https://github.com/jquery/jquery/blob/master/test/index.html#L13) which we should rename to something else I think.

**Comment by dmethvin** [comment] 2019-04-17 15:17
Oh right, we needed a "jQuery not under test". So I think just renaming the test jQuery might work. We'll also need to use a somewhat fresher one once we get to 4.0 .

**Comment by timmywil** [comment] 2019-04-17 16:35
Yea, I thought we already renamed to `supportjQuery`, but I guess that's just a local var.

**Comment by lucassonsinlima** [comment] 2019-04-17 16:53
Hi! I'm facing the same issue, you guys have any idea when you'll release the update?

**Comment by timmywil** [comment] 2019-04-17 16:55
I'd say sometime next week, depending on the team's availability.

**Comment by mgol** [comment] 2019-04-17 17:07
@timmywil @dmethvin I'm not sure it's `supportjQuery`. In AMD mode `jQuery.fn.jquery` in the console evaluates to me to `"@VERSION"`, not `1.9.1`. Also, the way `supportjQuery is defined should unset the `jQuery` global:
```js
const supportjQuery = this.jQuery;

supportjQuery.noConflict( true );
window.originaljQuery = this.jQuery = undefined;
window.original$ = this.$ = "replaced";
```
So it's our current global that gets exposed.

See:
https://github.com/jquery/jquery/blob/3.4.0/src/exports/global.js#L27-L32
The global is exposed in AMD mode, it's only hidden in CommonJS and only if there's a global `document` variable, otherwise we expose it as well (that might actually be a bug?), compare:
https://github.com/jquery/jquery/blob/3.4.0/src/wrapper.js#L29
with:
https://github.com/jquery/jquery/blob/3.4.0/src/wrapper.js#L34

**Closed** 2019-04-17 17:56 UTC
Labels: Blocker, Build, Has Pull Request

**Comment by timmywil** [comment] 2019-05-01 21:40
3.4.1 has been released! https://blog.jquery.com/2019/05/01/jquery-3-4-1-triggering-focus-events-in-ie-and-finding-root-elements-in-ios-10/
