### ISSUE TITLE
JavaScript not Minify

### ISSUE THREAD

**Issue by Theolodewijk** [jquery/jquery#4611] opened 2020-02-22 20:35 UTC
it would be nice if you wait at least a moment before you close an issue on answer !!!

here my answer; yes online, but when you using composer not.

so still jquery.min.js not minified!

**Comment by mgol** [comment] 2020-02-22 21:12
Don’t report duplicate issues, closing an issue doesn’t block further discussion.

Dupe of #4610

**Closed by mgol** 2020-02-22 21:12 UTC
