### ISSUE TITLE
.position() calculated for element inside td

### ISSUE THREAD

**Issue by steck** [jquery/jquery#4367] opened 2019-04-19 15:03 UTC
### Description ###
jQuery function `position` gives incorrect result for the element inside table.

Environment:
- OS: Windows 7
- Browser: Chrome 72.0.3626.121 (64-bit)

### Link to test case ###
Link with an error:
https://codepen.io/anon/pen/QPrmoR 

Expected behavior: (changed only jQuery version)
https://codepen.io/anon/pen/wZjmbN

**Comment by mgol** [comment] 2019-05-01 17:48
Thanks for the report! For the record, the issue is that a `p` inside of `td` should report `0` top & left which it did in 3.3.1 but which no longer does in 3.4.0.

**Comment by mgol** [comment] 2019-05-01 18:03
No, wait - the result was non-zero in 3.2.1, it's zeros in 3.3.1 & 3.4.0. It looks OK to me, closing the issue.

Please post a comment if I missed anything.

**Closed by mgol** 2019-05-01 18:03 UTC
Labels: Bug, Needs review, Offset
