### ISSUE TITLE
json $.ajax post messed up post-content when ?? in content

### ISSUE THREAD

**Issue by kojicz983** [jquery/jquery#2594] opened 2015-09-14 14:48 UTC
When you post ?? as part of an ajax request, the content gets damaged.
The code below demonstrates this.

Version of jQuery used: http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
but also the 1.11.x branch has this error. The problem is browser independent.

(function() {
	var data = '{"a": "aa??bb"}';
	$.ajax({
		'beforeSend': function() {
			alert('I passed into $.ajax the data value:\n\n"' + data + '"\n\nbut it is going to send\n\n"' + this.data + '"');
		},
		'type': 'POST',
		'url': 'http://localhost',
		'data': data,
		'dataType': 'json'
		})
})()

**Comment by mzgol** [comment] 2015-09-14 14:51
Duplicate of #1791.

**Comment by kojicz983** [comment] 2015-09-14 14:52
It doesn't seem to be a duplicate because not the URL gets damaged but the actual data content.

**Comment by mzgol** [comment] 2015-09-14 14:57
Hmm, OK, I'll reopen (though most likely the cause is analogous).

Could you provide a test case on jsfiddle or jsbin?

**Comment by jaubourg** [comment] 2015-09-14 15:17
When you pass a string as the data argument, you need to encode it the body content-type is `application/x-www-form-urlencoded`. If not (in your case you seem to wanna send json), then you need to specify this content-type is JSON by setting the `content-type` option to `application/json`.

This fact jQuery modified the body is incidental. You will have troubles with backends if you don't specify a proper content-type and you have special characters in your body (in regard to the `application/x-www-form-urlencoded` encoding) because most backends will attempt to decode the body before any use code can access it.

**Comment by timmywil** [comment] 2015-09-14 16:29
@jaubourg agreed. Thanks for the explanation.

**Closed by timmywil** 2015-09-14 16:29 UTC
Labels: Ajax

**Comment by kojicz983** [comment] 2015-09-14 18:25
@jaubourg Thanks for the explanation.We have resolved issue this way.
