### ISSUE TITLE
3.0.0-alpha1 slideToggle() does not work when the elements has hidden class

### ISSUE THREAD

**Issue by running-coder** [jquery/jquery#2763] opened 2015-12-08 22:02 UTC
Hey, not sure if it's meant to be but inside version 2.x I could have a `hidden` class on an element by default and use slideToggle to make it appear. Does 3.0 requires inline styles?

2.x - Works
``` html
<div class='hidden'>hello</div>
```

3.0 - Doesn't work
``` html
<div class='hidden'>hello</div>
```

3.0 - Works
``` html
<div style="display:none;">hello</div>
```

**Comment by markelog** [comment] 2015-12-08 22:25
Duplicate of https://github.com/jquery/jquery/issues/2308

It was a deliberate change, which will be improved in final release.

Thank you for keeping an eye on it though.

**Closed by markelog** 2015-12-08 22:25 UTC
