### ISSUE TITLE
$.position in v1.12.0 gives different result for top than v1.11.3 in Chrome+Firefox

### ISSUE THREAD

**Issue by cvrebert** [jquery/jquery#2836] opened 2016-01-15 05:37 UTC
Example using v1.11.3: http://jsbin.com/dojupi/edit?html,js,output
Same example using v1.12.0: http://jsbin.com/nixide/edit?html,js,output
View the console in both and compare the results.
v1.11.3 says that `#div-100-4`'s `top` is `-100`
whereas
v1.12.0 says that `#div-100-4`'s `top` is `300`.

Both Chrome and Firefox on OS X give the same results.

This appears to have broken the scaffolding of one of Bootstrap's unit tests (X-Ref: https://github.com/twbs/bootstrap/pull/18904).

Perhaps related to #2828?

**Comment by markelog** [comment] 2016-01-15 08:27
We are planning to release 1.12.1/2.21, so fix for this one should be included as well.

**Comment by dmethvin** [comment] 2016-01-15 13:23
Pretty sure this is a dup of #2828, caused by the fix for #1708. Was that ticket invalid, or was the fix incorrect?

**Comment by timmywil** [comment] 2016-01-15 16:42
Agreed, looks like dup of #2828.

**Closed by timmywil** 2016-01-15 16:42 UTC
Labels: Offset

**Comment by Antonnz** [comment] 2016-02-23 11:00
Note that this also affects Google Chrome 47 on Ubuntu 14.04 64bit in some way, not just IE.
(https://issues.apache.org/jira/browse/WICKET-6100):

     Uncaught TypeError: Cannot read property 'opener' of null
     jquery-1.12.0-ver-1456109363000.js:6704

**Comment by mgol** [comment] 2016-02-24 11:02
@Antonnz Your problem is not this bug but #2866 and should be fixed in jQuery 1.12.1. Please try it & report a new issue if it's still broken for you, let's not clutter this one.
