### ISSUE TITLE
Mozilla WebExtension : setTimeout or setInterval must have function as 1st arg

### ISSUE THREAD

**Issue by darknoon29** [jquery/jquery#3201] opened 2016-06-26 12:09 UTC
### Description ###

Hi,
When i submit my webextension to Mozilla for Firefox (using JQUery 3.0.0), i have following messages from the Mozilla Validation tool:

setTimeout or setInterval must have function as 1st arg

jquery-3.0.0.min.js ligne 2 colonne 30109
jquery-3.0.0.min.js ligne 2 colonne 31687
jquery-3.0.0.min.js ligne 3 colonne 30564

Its not an important issue but that generates warnings from the Mozilla tool.
![warning](https://cloud.githubusercontent.com/assets/13015521/16362176/8cbd334e-3ba7-11e6-9300-245589eb1d99.PNG)

**Comment by dmethvin** [comment] 2016-06-26 13:04
This is a duplicate of #2847, the tool is giving false positives.

**Closed by dmethvin** 2016-06-26 13:04 UTC

**Comment by darknoon29** [comment] 2016-06-26 15:05
For information,
These messages were not present when using JQuery V2.

**Comment by cyberdees** [comment] 2016-06-26 17:26
CC’ing Mozilla folks: @miketaylr @digitarald @bzbarsky @annevk @kentuckyfriedtakahe @cyberdees

**Comment by tofumatt** [comment] 2016-06-27 15:43
This is indeed a Mozilla and not a jQuery bug but figured I'd update the original poster here.

Mozilla add-ons site does weekly pushes and so our tool to flag software is not always 100% up-to-date.

This has been added and should go out this week: https://github.com/mozilla/dispensary/commit/05fe3e62d5dd6aeea2e04d0a406ca06d8baea185

Your issue should be resolved Thursday by about 6pm GMT.
