### ISSUE TITLE
jQuery UI (1.11.4) position without specifying within gets error

### ISSUE THREAD

**Issue by rpfeffer** [jquery/jquery#3156] opened 2016-06-10 12:08 UTC
The jQuery UI position utility function dies with the new jQuery 3 when a wthin option is not specified.
The default for within is Window.
The position routine tries to use the offset routine of jQuery.
According to the new documentation use of  Window to query offset will throw an error:
Excerpt from blog:https://blog.jquery.com/2016/06/09/jquery-3-0-final-released/

> **_Error cases don’t silently fail
> 
> Perhaps in a profound moment you’ve wondered, “What is the offset of a window?” Then you probably realized that is a crazy question – how can a window even have an offset?
> 
> In the past, jQuery has sometimes tried to make cases like this return something rather than having them throw errors. In this particular case of asking for the offset of a window, the answer up to now has been { top: 0, left: 0 } With jQuery 3.0, such cases will throw errors so that crazy requests aren’t silently ignored. Please try out this release and see if there is any code out there depending on jQuery to mask problems with invalid inputs._**

**Comment by dmethvin** [comment] 2016-06-10 12:16
Duplicate of gh-2802.

**Closed by dmethvin** 2016-06-10 12:16 UTC
