### ISSUE TITLE
Syntax error, unrecognized expression: a[href*=#]:not([href=#]) jquery.js wordpress

### ISSUE THREAD

**Issue by geliyoo** [jquery/jquery#3063] opened 2016-04-16 12:13 UTC
I get this error from wordpress js with google inspect. Please check this error for all jquery because after new update wordpress i get this error. If i click this js i see all js file have inside this code.

Syntax error, unrecognized expression: a[href*=#]:not([href=#])

**Comment by FagnerMartinsBrack** [comment] 2016-04-16 12:17
Potential duplicate of https://github.com/jquery/jquery/issues/2824

**Comment by geliyoo** [comment] 2016-04-16 12:23
I can fixed my problem with this code from my js file but jquery can not see this setting give a error message from chrome 

a[href=#]:not([href=#])
to
a[href=\\#]:not([href=\\#])

**Comment by gibson042** [comment] 2016-04-16 18:11
As noted in #2824, `[href=#]` and `[href*=#]` are invalid selectors. Only [identifiers](http://www.w3.org/TR/CSS21/syndata.html#value-def-identifier) are allowed as unquoted values, so you need to wrap those `#`s in quotes.

**Closed by gibson042** 2016-04-16 18:11 UTC
