### ISSUE TITLE
selected option changes in IE after forward/back button

### ISSUE THREAD

**Issue by alambe** [jquery/jquery#2719] opened 2015-11-14 08:55 UTC
In IE (confirmed in 9+), after detaching a non-selected option from a select dropdown and navigating to another page and back (e.g. click forward then back buttons), the selected option changes.

In the test case below, "3 selected" should be selected.  However, in IE9+, navigate away from the page and back, then 1 will be selected instead of 3.  FF and Chrome do not have this problem.

Test case:
```html
<!DOCTYPE html><html lang="en">
<head><meta charset="UTF-8">
	<title>select-option-detach IE/jquery bug</title>
</head>
<body>
<script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
<select>
	<option value="1">1 not selected</option>
	<option value="2">2 not selected</option>
	<option value="3" selected>3 selected</option>
</select>
<script type="text/javascript">
	$(function(){
		$('option').eq(1).detach();
	})
</script>
</body></html>
```

**Comment by dmethvin** [comment] 2015-11-15 22:42
I can repro this in IE11 and Edge with a bare file that has the contents of this jsbin, although it doesn't work in jsbin: 
http://jsbin.com/gekacodole/1/edit?html,js,output

Note that there's no jQuery in use.
```js
<select>
    <option value="1">1 not selected</option>
    <option value="2">2 not selected</option>
    <option value="3" selected>3 selected</option>
</select>
<script type="text/javascript">
window.onload = function(){
	var sel = document.getElementsByTagName("select")[0];
	sel.removeChild(sel.firstElementChild.nextElementSibling);
}
</script>
```
So it's not caused by jQuery.

**Comment by timmywil** [comment] 2015-11-16 16:28
I'll close this one as patchwelcome. I don't think we can work around it, but we'd be willing to look at a pull request.

**Closed by timmywil** 2015-11-16 16:28 UTC
