### ISSUE TITLE
v2.1.4 isArrayLike empty obj error

### ISSUE THREAD

**Issue by newenegue** [jquery/jquery#2242] opened 2015-04-29 00:34 UTC
I received this error
`Uncaught TypeError: Cannot use 'in' operator to search for 'length' in `

When trying to call `$.map` like so:
`$.map("".match( /"[^"]+"|[^ ]+/g ) || "", function(word) {console.log(word);});`

It seems that `"length" in obj` returns the error when the `obj == ""`, but it works fine when `obj == [""]`

I just want to check that passing in the `obj == [""]` should be what I do moving forward.  Thanks!

```
function isArraylike( obj ) {

    // Support: iOS 8.2 (not reproducible in simulator)
    // `in` check used to prevent JIT error (gh-2145)
    // hasOwn isn't used here due to false negatives
    // regarding Nodelist length in IE
    var length = "length" in obj && obj.length,
        type = jQuery.type( obj );

    if ( type === "function" || jQuery.isWindow( obj ) ) {
        return false;
    }

    if ( obj.nodeType === 1 && length ) {
        return true;
    }

    return type === "array" || length === 0 ||
        typeof length === "number" && length > 0 && ( length - 1 ) in obj;
}
```

**Comment by dmethvin** [comment] 2015-04-29 01:39
The [documentation for jQuery.map](http://api.jquery.com/jQuery.map/) doesn't say the method takes a string, but you're passing one in the case where the `.match()` method returns `null`. if you change the `|| ""` to `|| [ "" ]` it will pass in the correct type in all cases.

**Comment by Drarok** [comment] 2015-04-29 13:00
This change also breaks [DataTables][datatables] as it has the following code:

    $.map( search.match( /"[^"]+"|[^ ]+/g ) || '', function ( word ) {

[datatables]: http://datatables.net

**Comment by dmethvin** [comment] 2015-04-29 13:07
That should be fixed in the plugin, since `$.map` never supported strings.

**Comment by Drarok** [comment] 2015-04-29 13:10
I don't disagree that the plugin should fix this usage, but should a point release of jQuery break a very popular plugin, and countless other codebases that rely on the previous bahaviour?

**Comment by mzgol** [comment] 2015-04-29 14:02
@Drarok Technically speaking, semver only describes the relation between a public API and versions and here we're talking about undocumented behavior therefore semver doesn't apply.

Unfortunately, such problems are unavoidable. People don't remember all possible method signatures and don't check the docs on every use which leads to sometimes relying on undocumented behavior. Any change we make, even in patch releases may break some of those invalid use cases, that's why we always say semver is just a hint but you should test your projects on every library upgrade, even if you just upgrade to a newer patch release.

Thus, the question is not if we broke some plugin that uses undocumented APIs incorrectly (I'd guess we almost *always* break something) but how much impact such breakage may have, e.g. how popular is a plugin etc. If anyone reported the issue with the patch in PR #2185 we'd most likely update the patch to avoid this issue but it's done, we've released `2.1.4` & `1.11.3` and they cannot be re-released. To make newest jQuery & DataTables work, there are only two options:
1. Workaround it in jQuery & release new jQuery versions, `2.1.5` & `1.11.4`.
2. Fix it in DataTables & release a new DataTables version.

Whatever happens, you'll need to update one of the libraries anyway to make it work. In this case I'd rather DataTables fixed their incorrect use of the jQuery API. Did you report this issue to them? If they have a public bug tracker, could you post a link here?

I'd say we should work around it & release a new patch update only if a lot of popular plugins relied on this behavior. So far we only know about one and they should just fix it on their side.

**Comment by timmywil** [comment] 2015-04-29 15:22
Well said, @mzgol. There would have to be quite an uproar for us to do another patch release to support undocumented behavior.

**Closed by timmywil** 2015-04-29 15:22 UTC

**Comment by mzgol** [comment] 2015-04-29 15:32
I posted about the problem on their forums:
https://www.datatables.net/forums/discussion/27524/broken-in-jquery-2-1-4-1-11-3
From what I see, this is mostly a paid product which reinforces my view that they should fix it.

**Comment by DataTables** [comment] 2015-04-29 15:41
The fix has been committed to [DataTables now](https://github.com/DataTables/DataTablesSrc/commit/485b259e5c02a) and its [nightly version](//datatables.net/download/#DataTables) is up to date with the change.

Passing a string is was a bug that I didn't pick up before as it "just worked" in jQuery so I didn't notice it!

> From what I see, this is mostly a paid product which reinforces my view that they should fix it.

DataTables is MIT licensed :-)

**Comment by mzgol** [comment] 2015-04-29 15:52
> DataTables is MIT licensed :-)

Sorry, my quick glance at the site was not enough apparently. :)

> Passing a string is was a bug that I didn't pick up before as it "just worked" in jQuery so I didn't notice it!

I fully understand, such issues are unavoidable, unfortunately.

 Thanks for a quick reaction!

**Comment by markelog** [comment] 2015-04-29 17:35
Hm, should we add this behaviour to the migrate?

**Comment by mzgol** [comment] 2015-04-29 17:39
> Hm, should we add this behaviour to the migrate?

Seems like a good idea.

**Comment by gibson042** [comment] 2015-04-29 17:39
I would say no. We only care about changes to documented behavior.

**Comment by markelog** [comment] 2015-04-29 17:45
@gibson042 we did it a lot for undocumented behaviour and undocumented methods, for example - https://github.com/jquery/jquery-migrate/blob/master/src/manipulation.js

**Comment by bitboxx** [comment] 2015-07-30 13:04
The fix for this bug causes error in Chrome, IE and Firefox. Tested with Chrome 44, 46; IE 11; and Firefox 38.

Calling the function using an empty string as argument will reproduce the error. Note that this function was not called directly from a script, but from triggering a custom event on an element using element.trigger('eventName').

```
function isArraylike( obj ) {

    // Support: iOS 8.2 (not reproducible in simulator)
    // `in` check used to prevent JIT error (gh-2145)
    // hasOwn isn't used here due to false negatives
    // regarding Nodelist length in IE
    var length = "length" in obj && obj.length,
        type = jQuery.type( obj );

    if ( type === "function" || jQuery.isWindow( obj ) ) {
        return false;
    }

    if ( obj.nodeType === 1 && length ) {
        return true;
    }

    return type === "array" || length === 0 ||
        typeof length === "number" && length > 0 && ( length - 1 ) in obj;
}

isArraylike('');
```

**Comment by Ustes** [comment] 2015-09-25 15:00
Attempting to use DataTables in a project and I am still receiving this error.  I have attached my plunker,
http://plnkr.co/edit/bJ0RQQpcnX8STsw626mX?p=preview.

When you change the jquery version to 1.8.3 in the cdn link in the html all works well, if you leave as 2.1.4 and view the developer tools you see the following:
     TypeError: Cannot use 'in' operator to search for 'length' in Category

**Comment by dmethvin** [comment] 2015-09-25 15:04
The first Google result for "jquery isarraylike datatables" is this ticket:

https://github.com/DataTables/DataTables/issues/546

Have you updated your DataTables plugin?

**Comment by Ustes** [comment] 2015-09-25 15:08
yes, I have even tried using the nightlies in the cdn.

**Comment by dmethvin** [comment] 2015-09-25 15:09
Then you should report the problem to the DataTables team.

**Comment by Ustes** [comment] 2015-09-25 15:10
Sorry, thought this was the DataTables issue. Posted in wrong tab.
