### ISSUE TITLE
Cannot use 'in' operator to search for 'length' 

### ISSUE THREAD

**Issue by migueldanto** [jquery/jquery#2579] opened 2015-09-08 13:25 UTC
in 1.11.3 this error show, but in 1.11.2 not show

**Comment by mzgol** [comment] 2015-09-08 13:36
There isn't a lot of info in this report so I'm going to assume it's a duplicate of #2267. You're most likely passing `null` or `undefined` to `jQuery.each` or `jQuery.map` which is not supported before jQuery 3.0.0.

**Closed by mzgol** 2015-09-08 13:36 UTC
