### ISSUE TITLE
Tag-like attribute values modified by .html(htmlString)

### ISSUE THREAD

**Issue by zomp** [jquery/jquery#2922] opened 2016-02-15 12:37 UTC
If you use tag-like text in attribute value via `.html(htmlString)`, it gets improperly modified.

Example:
```javascript
$element.html('<span data-text="<br />"></span>');
```
you get
```html
<span data-text="<br ></span>">a</span>
```
instead of expected
```html
<span data-text="<br />">a</span>
```
produced by `.innerHTML`.

(According to [HTML5 specification](https://html.spec.whatwg.org/multipage/syntax.html#syntax-attribute-value) tag-like values seem to be fine – only ambiguous ampersands have to be escaped.)

**Comment by yashdeeph709** [comment] 2016-02-15 15:35
that is happning due to return html.replace( rxhtmlTag, "<$1></$2>" ); I don't know why this is done the method is 
htmlPrefilter: function( html ) {
		return html.replace( rxhtmlTag, "<$1></$2>" );
	}

**Comment by gibson042** [comment] 2016-02-15 15:38
Duplicate of gh-2205. You can resolve this  by escaping `>` characters in attribute values as `&gt;` or using `jQuery.htmlPrefilter` ([documentation](https://github.com/jquery/api.jquery.com/blob/cc0604bb4d075031d083ca3fd27c0a0aac2df80f/entries/jQuery.htmlPrefilter.xml#L21-L74) not yet released).

**Closed by gibson042** 2016-02-15 15:38 UTC

**Comment by zomp** [comment] 2016-02-16 18:02
Thank you both. I would never find #2205. You are doing a fine job.
