### ISSUE TITLE
`.offset()` called on empty element doesn't account for document clientTop

### ISSUE THREAD

**Issue by rgavrilov** [jquery/jquery#3495] opened 2017-01-12 00:59 UTC
### Description ###
`.offset()` implementation (as getter) mis-identifies an element with no content, as not-rendered element, as a result `pageYOffset` and `document.clientTop` are not accounted for.

Here is code for a demo page (I couldn't figure out a way to repro the issue on jsfiddle, because jsfiddle puts result page in a scroll box, thus docElem.clientTop stays 0), to see the discrepancy you need to open the page, scroll the document then refresh. There will be to alerts showing `offset().top` for empty and populated elements. It is expected both to popups to show same number, however, it does not.

Here is relevant 3.1.1 code:

		rect = elem.getBoundingClientRect();

		// Make sure element is not hidden (display: none)
		if ( rect.width || rect.height ) {
			doc = elem.ownerDocument;
			win = getWindow( doc );
			docElem = doc.documentElement;

			return {
				top: rect.top + win.pageYOffset - docElem.clientTop,
				left: rect.left + win.pageXOffset - docElem.clientLeft
			};
		}

		// Return zeros for disconnected and hidden elements (gh-2310)
		return rect;

line 9966-9967:
// Make sure element is not hidden (display: none)
		if ( rect.width || rect.height ) {

the if-expression is true for empty elements, not just for those that are `display:none`.

this check is new to 3.x, which breaks scrollSpy if anchor tag (that page is being scrolled to) is defined as, for example as: `<a href="" id="section-foo"></a>`

**Comment by gibson042** [comment] 2017-01-13 06:23
Duplicate of gh-3167, already fixed on master by 1777899a747647f3fa839eea4b0bb695d3b60f06 and will be included in 3.2.0.

**Closed** 2017-01-13 06:23 UTC
Labels: Offset
