### ISSUE TITLE
.width() totally broken: systematically rounded, inaccurate

### ISSUE THREAD

**Issue by teo1978** [jquery/jquery#3132] opened 2016-05-29 16:09 UTC
http://output.jsbin.com/soteno

1. Look at the console output, which prints ·("#test").width()
2. Compare it with the actual value, as displayed by the browser's dev tools

Expected: the value should be 100% accurate
Observed: the value is systematically rounded to an integer (which is not as documented), and it is not even accurately to the nearest integer, nor systematically floored, nor systematically ceiled. Sometimes it is rounded to N+1 when its value is less than N<0.5, or viceversa.

Anyway, it shouldn't be rounded at all.

This renders .width() totally broken and absolutely useless.

**Comment by mgol** [comment] 2016-05-29 18:02
Thanks for the report. However, this is a duplicate of #1724 and it'll be fixed in the upcoming jQuery 3.0.0. We decided to not change that in 1.x/2.x as some code might depend on the shape of the output of this method and we wanted to avoid breaking changes.

Please test [jQuery 3.0.0-rc1](https://code.jquery.com/jquery-3.0.0-rc1.js) where this issue is resolved and report any regressions you might find there!

**Closed by mgol** 2016-05-29 18:02 UTC

**Comment by teo1978** [comment] 2016-05-29 18:23
I see.

However, for 1.x/2.x, you should consider at least doing the right rounding. Either consistently round to the nearest integer, or consistently floor (I wouldn't see a good reason for consistently ceiling). Currently, on Chrome, it unpredictably picks the next or previous integer, that is, 11.2 is sometimes rounded to 12, or 11.8 to 11.

**Comment by mgol** [comment] 2016-05-29 18:40
> it unpredictably picks the next or previous integer, that is, 11.2 might be rounded to 12, and 11.8 might be rounded to 11

jQuery 1.x/2.x just uses `offsetWidth`/`offsetHeight` to get the values; if they behave as you describe then it's a browser bug and you should report it to the relevant browser vendor.

Even if we used `getBoundingClientRect()` and rounded ourselves, it would still not be consistent across browsers as e.g. Chrome rounds in a different direction than Android 2.3.

Note that even in jQuery 3.x you won't get fractional values everywhere but only in browsers that return fractional values in `getBoundingClientRect()`. This includes virtually all modern browsers but e.g. IE 9 always rounds.

**Comment by teo1978** [comment] 2016-05-29 18:45
>jQuery 1.x/2.x just uses offsetWidth/offsetHeight to get the values; if they behave as you describe then it's a browser bug and you should report it to the relevant browser vendor.
>
> Browsers round offsetWidth in various direction, e.g. Chrome does it differently than Android 2.3.

isn't half of the point of jQuery [supposed to be] eliminating differences between browsers??

**Comment by mgol** [comment] 2016-05-29 18:52
> isn't half of the point of jQuery [supposed to be] eliminating differences between browsers??

Yes but there are always trade-offs to consider; e.g. we would reject a patch that makes a small improvement and takes a big performance hit. Sometimes it's also not possible to align the browsers or the patch doing so would be huge and we're trying to keep the size of jQuery relatively small.

In any case, we don't plan any further updates to the 1.x/2.x jQuery lines, all development is focused on jQuery 3.0. There the only issue wrt to rounding is that IE 9 & Android Browser 2.3-4.3 round values in `getBoundingClientRect()`; everywhere else you'll get fractional values.

**Comment by dmethvin** [comment] 2016-05-29 20:08
> isn't half of the point of jQuery [supposed to be] eliminating differences between browsers??

How would we eliminate this difference? The numbers we give are the ones that the browser is providing to us via its APIs, which are supposed to represent how that browser's layout engine decided to lay out the page. Note that there is no constraint for pixel-perfect layout in browsers, so differences are not necessarily bugs. Issues like this have been around for ages, see [this blog post](http://ejohn.org/blog/sub-pixel-problems-in-css/) from John Resig for some of the reasons.

In jQuery 3.0 we've done what we can by switching to `getBoundingClientRect`. Changing 1.x/2.x could introduce breaking changes to the decade worth of existing code that already exists.

> Currently, on Chrome, it unpredictably picks the next or previous integer, that is, 11.2 might be rounded to 12, and 11.8 might be rounded to 11.

If Chrome isn't giving reasonable values you should file a bug with Chrome. However, keep in mind the issues mentioned in that blog post. If you have a 100px table with 3 columns each at 33.33%, it seems perfectly reasonable for the browser to return 33,34,33 for the column widths in order for the *total* to be exactly 100px.
