### ISSUE TITLE
not well-formed error on Firefox

### ISSUE THREAD

**Issue by rostacik** [jquery/jquery#2631] opened 2015-10-06 11:33 UTC
Hello gents.
I am getting "not well-formed" errors on the Firefox Web developer tools console when using $.parseXML with latest jQuery 2.1.4. Error is logged by jQuery only on Firefox.

Tested on Developer Edition 43.0a2 build from 2015-10-05 and also on 42.0b3. 

I was able to isolate, that this error occurs and is logged when searching for nodes with .find()

I copied sample code from demo found here : https://api.jquery.com/jQuery.parseXML/ that is not throwing exception and replaced src from 1.10.2.js to 2.1.4.js and same code is now throwing error.

What I see in the console :
![not_well_formed](https://cloud.githubusercontent.com/assets/429190/10307340/64c6b598-6c2e-11e5-8c36-2cff78fc721a.png)

File not throwing error :
http://files.rostacik.net/jq1.html

File throwing error :
http://files.rostacik.net/jq2.html

My other environment : Windows 8.1 with latest updates, Firefox 43.0a2 and 42.0b3, jQuery 2.1.4.

If you need some other information, I will be more than happy to assist you.

Regards,
d

**Comment by gibson042** [comment] 2015-10-06 15:00
I'm almost certain this is a duplicate of gh-1969. Please reopen if your problem also manifests in the [git build](http://code.jquery.com/jquery-git.js) or the [3.0 alpha](https://code.jquery.com/jquery-3.0.0-alpha1.js).

**Closed by gibson042** 2015-10-06 15:00 UTC

**Comment by alawatthe** [comment] 2015-10-06 16:01
3.0 alpha is working fine: http://jsfiddle.net/xkzxwxah/
