### ISSUE TITLE
middle click delegation

### ISSUE THREAD

**Issue by zba** [jquery/jquery#2410] opened 2015-06-18 08:02 UTC
As you probably know, event delegation is working only for 1st button click, this is because of line:

https://github.com/jquery/jquery/blob/master/src/event.js#L481

> // Avoid non-left-click bubbling in Firefox (#3861)

I read the original bug request and tried to remove this "avoid" here:  http://jsfiddle.net/Lwxdhk9b/

For me I not found anything "bad" if  click delegation is allowed, but I found something very bad if they disallowed, especially in case I can't switch this behavior  without fork of almost whole jQuery. please take a look for searching better solution for this old issue.

**Comment by zba** [comment] 2015-06-18 08:53
I have workaround for this here:

    $(document)
        .on('clickReal click', 'a', function (e) {
        console.log('click', e);
    })
        .on('click', function (e) {
        if (e.button) {
            e.type = 'clickReal';
            $(this).trigger(e);
        }
    });

**Comment by dmethvin** [comment] 2015-06-19 21:22
See also #2343 which I think has the same root cause.

**Comment by dmethvin** [comment] 2015-10-20 15:59
This should have been fixed by #2617, can you verify it works for you @zba? The latest version is in http://code.jquery.com/jquery-git.js .

**Comment by dmethvin** [comment] 2015-10-23 00:16
I am pretty sure this was fixed, please let us know if you find otherwise.

**Closed by dmethvin** 2015-10-23 00:16 UTC
