### ISSUE TITLE
"not well-formed' soft error on initial access to XMLDocument object in Firefox

### ISSUE THREAD

**Issue by lanexjeff** [jquery/jquery#2196] opened 2015-04-09 20:51 UTC
JQuery 2.1.3
Firefox 36.0.4

On the initial 'find' and reference to the XMLDocument object, a soft error "not well-formed" in FireFox is thrown, captured and released with continuing execution.   Soft error is not thrown for JQuery 2.1.0

not well-formed <unknown>:1:77

On Fiddle.Net site: 
not well-formed <unknown>:1:79

Open in Firefox, F12, monitor for javascript errors.
http://jsfiddle.net/spknpd92/

===============

Javascript: 
var  xmlxmlTxt = &#39;&lt;?xml version=&quot;1.0&quot;?&gt;&lt;general&gt;&lt;temperature&gt;&lt;myTemp val = &quot;10&quot;&gt;The temp is 10&lt;/myTemp&gt;&lt;/temperature&gt;&lt;/general&gt;&#39;;

alert($($.parseXML(xmlxmlTxt)).find(&#39;myTemp&#39;).attr(&#39;val&#39;))

===============

**Comment by gibson042** [comment] 2015-04-10 01:39
This is a duplicate of #1969 (jquery/sizzle#304), which is harmless but already [fixed upstream](https://github.com/jquery/sizzle/commit/50ebe1a43c0842f33ce363259f1a9eed236aca19) and will be resolved with the next jQuery release.

**Closed by gibson042** 2015-04-10 01:39 UTC
