### ISSUE TITLE
Uncaught TypeError: e.getRootNode is not a function

### ISSUE THREAD

**Issue by Czytx** [jquery/jquery#4371] opened 2019-04-28 10:38 UTC
Hello:
We update jQuery from 3.3.1 to 3.4.0 and get some errors only on chrome 53.0.2785.101.
error information: Uncaught TypeError: e.getRootNode is not a function.

We found out that chrome 53 has completed attachShadow, but incomplete getRootNode.
Yon can see this explain:
https://developer.mozilla.org/zh-CN/docs/Web/API/Element/attachShadow
https://developer.mozilla.org/zh-CN/docs/Web/API/Node/getRootNode

**Comment by mgol** [comment] 2019-04-28 12:23
Duplicate of #4356. Please search for existing issues before reporting a new one. Thanks!

**Closed by mgol** 2019-04-28 12:23 UTC
