### ISSUE TITLE
ajax empty response required by rfc but parse attempted

### ISSUE THREAD

**Issue by lazylester** [jquery/jquery#2434] opened 2015-06-29 14:56 UTC
when ajax response status code is 205, rfc requires empty body, but jquery attempts to parse using the json converter and fails. We know that parsing an empty string as json will fail, but attempt to parse should not be made for 205 status code.

Surprisingly, for 204 status code, a parse attempt is still made, but the inevitable errors on empty content are discarded. Surely parsing should not be attempted when rfc disallows content?

**Comment by mzgol** [comment] 2015-06-29 15:22
Duplicate of #2347.

jQuery only parses the output if it's provided a `Content-Type` header or the `dataType` option is set explicitly. A `Content-Type` header is disallowed for a 205 response:

http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.2.6
```
The response MUST NOT include an entity.
```
http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.17
```
The Content-Type entity-header field...
```

**Closed by mzgol** 2015-06-29 15:22 UTC
