### ISSUE TITLE
Regression: All tests fail (timeout) on Android 4.0

### ISSUE THREAD

**Issue by Krinkle** [jquery/jquery#3743] opened 2017-07-31 21:54 UTC
| Before | After
|--|--
| Commit 36389288e8 | Commit 31783e60f5
| [swarm.jquery.org, 24 Jun 2017](http://swarm.jquery.org/job/5654) |  [swarm.jquery.org, 27 Jun 2017](http://swarm.jquery.org/job/5669)
| <img width="471" alt="screen shot" src="https://user-images.githubusercontent.com/156867/28800040-d9257d48-75ff-11e7-840b-f2991d9a27fd.png"> | <img width="466" alt="screen shot" src="https://user-images.githubusercontent.com/156867/28800043-dc2409c4-75ff-11e7-8b46-8c1b4be96880.png">

<img width="363" alt="screen shot" src="https://user-images.githubusercontent.com/156867/28800108-28608a24-7600-11e7-87fd-ef1cff23fa99.png">

Possibly relevant commits:
* 31783e60f5: `Build: update node dependencies` (gh-3669, @timmywil, @CDAGaming)

According to code review comments, this commit also affected IE8/IE9 in some way. (@mgol)

**Comment by mgol** [comment] 2017-08-01 07:32
Sometimes such breakages are caused by changes on the BrowserStack side but I've re-run tests on the commit you mentioned and the one before that and results were identical.

So we broke something, indeed.

Marking as a blocker for 3.3.0.

**Comment by mgol** [comment] 2017-08-01 07:32
Thanks, @Krinkle!

**Comment by mgol** [comment] 2017-08-16 21:34
I've created a PR fixing this butt at a significant cost: #3759.

It may be a good basis to look for the real problem.

**Closed** 2018-01-08 16:49 UTC
Labels: Blocker, Has Pull Request
