### ISSUE TITLE
Still no `passive` with `scroll` event

### ISSUE THREAD

**Issue by batata004** [jquery/jquery#4729] opened 2020-06-06 14:46 UTC
Hi,

I know that the `passive` option is default on Chrome for a while. But doesnt jquery still able users to set `passive`?

Many customers of us, when we finish developing the website, they give it a try to their website on GOOGLE PAGESPEED INSIGHTS and if you dont set `passive` explicitly in the `scroll` event, then Google will tell your customers that you did a lame job and you should fix it.

Every week we receive complains of users saying "GoOgLe FoUnD ErRoRs On My WeBsIte". I know that if I go native I can fix this easily but we have tons of `scroll` event attached to our platform, it would require lots of changes to go native.

**Comment by dmethvin** [comment] 2020-06-06 18:18
Duplicate of #2871, which has a simple workaround and loads of discussion about why this is a breaking change that can't land until jQuery 4.

**Closed by dmethvin** 2020-06-06 18:18 UTC
