### ISSUE TITLE
jQuery 1.12.0 now requires quotes around anchors

### ISSUE THREAD

**Issue by joszz** [jquery/jquery#2829] opened 2016-01-14 13:47 UTC
After upgrading from 1.11.3 to 1.12.0 I had to rewrite some selectors to keep them working.
In 1.11.3 I could write this;
$("a[href=#some-anchor")

in 1.12.0 I need to write it like this (single quotes around the href value)
$("a[href='#some-anchor'")

**Comment by dmethvin** [comment] 2016-01-14 13:49
Duplicate of gh-2824.

**Closed by dmethvin** 2016-01-14 13:49 UTC
