### ISSUE TITLE
Upgrading from 3.4.1 to 3.5.0 broke Bootstrap collapse/expand function

### ISSUE THREAD

**Issue by D-R-J** [jquery/jquery#4680] opened 2020-04-22 06:39 UTC
When I upgraded jQuery from 3.4.1 to 3.5.0 it broke Bootstrap accordion and collapse/expand function. I'm using Bootstrap 4.4.1.
Error messages:
Uncaught TypeError: Cannot convert object to primitive value
    at RegExp.test (<anonymous>)
    at HTMLDivElement.<anonymous> (bootstrap-4.4.1.min.js:6)
    at Function.each (jquery-3.5.0.min.js:2)
    at S.fn.init.each (jquery-3.5.0.min.js:2)
    at S.fn.init.a._jQueryInterface [as collapse] (bootstrap-4.4.1.min.js:6)
    at HTMLDivElement.<anonymous> (bootstrap-4.4.1.min.js:6)
    at Function.each (jquery-3.5.0.min.js:2)
    at S.fn.init.each (jquery-3.5.0.min.js:2)
    at HTMLAnchorElement.<anonymous> (bootstrap-4.4.1.min.js:6)
    at HTMLDocument.dispatch (jquery-3.5.0.min.js:2)

**Comment by mgol** [comment] 2020-04-22 07:14
Thanks for the report. This is a duplicate of #4665.

**Closed by mgol** 2020-04-22 07:14 UTC
