### ISSUE TITLE
jQuery 3.2.1: IE11: Exception in method offset for window object - getClientRects not supported

### ISSUE THREAD

**Issue by Jochen-Scharr** [jquery/jquery#3847] opened 2017-11-16 12:10 UTC
Hi,

when you call 

$(window).offset(); 

in IE11 you get an exception saying that the object does not support method getClientRects (sorry, it's in German):

![image](https://user-images.githubusercontent.com/6214342/32890483-3a607508-cacf-11e7-96e2-6172c5e9c0dd.png)

![image](https://user-images.githubusercontent.com/6214342/32890056-8b2d7e42-cacd-11e7-936b-e9296f9452d5.png)

I'm using jQuery 3.2.1 and the following IE11 version:

![image](https://user-images.githubusercontent.com/6214342/32890162-e860dc6c-cacd-11e7-8fbc-d48306923eea.png)

**Comment by mgol** [comment] 2017-11-16 12:28
Duplicate of #3249.

Now that I think about it, though, maybe we should make that more obvious both in the upgrade guide and in the `offset` [API page](https://api.jquery.com/offset/)?

**Comment by Jochen-Scharr** [comment] 2017-11-16 15:07
It was not me calling the method this way, but jQueryUi. So I have no influence on that (reading the manual does not help in this case).

I'd change the method like following: 

```
if ( !elem ) {
     return;
}

// Elements outside the body and the body itself have no offset.
if ( this.parents("body").length == 0 ) {
     return { top: 0, left: 0 };
}

// Return zeros for disconnected and hidden (display: none) elements (gh-2310)
// Support: IE <=11 only
// Running getBoundingClientRect on a
// disconnected node in IE throws an error
if ( elem.getClientRects && !elem.getClientRects().length ) {
	return { top: 0, left: 0 };
}

```
That should avoid unnecessary errors.

**Comment by mgol** [comment] 2017-11-16 15:11
Which version of jQuery UI? Older jQuery UI version won't work with newest jQuery.

Silencing errors is often a bad idea as it just masks errors that can hit you another way.

**Comment by Jochen-Scharr** [comment] 2017-11-16 15:35
Yep, you're right in both. Was jQueryUi 1.11.4. Maybe, I should update both at once ... 
Though ... for window, document and body I would expect the result my change would produce. Best is, of course, not to call the method on these objects at all, since the result is rather n/a. From that perspective and to avoid silencing errors, an exception like "Do not call method 'offset' on this kind of object" may be helpful to explicitly point out what went wrong.

**Comment by dmethvin** [comment] 2017-11-16 15:47
The upgrade guide and jQuery Migrate already cover this case, it's just that neither were used here. The only reason this has come up is because an older version of UI tried to do `$(window).offset()` which is not valid but used to do nothing. As long as you're using the most recent version of UI (or jQuery Migrate with the old version) the problem goes away. 

Error handling is hard. Yes, everyone would love very specific error messages for every case, so for this case we could could have something right inside jQuery that says*"We noticed that the code tried to call `$(window).offset()` which is not valid. If you're using jQuery UI please make sure you're using the most recent version of jQuery UI 1.12 where this has been fixed"*. Now we just have the problem that the library would be about 5 times larger if we had error messages like that sprinkled around the code. And if we don't put those in the minified version to save space then people will still run into mysterious problems if they upgrade. Plus we **already** have something very similar in Migrate but it wasn't used.

**Closed by dmethvin** 2017-11-16 15:47 UTC
Labels: Needs review

**Comment by mgol** [comment] 2017-11-16 16:47
@dmethvin I wasn't thinking about error messages embedded into jQuery but rather mentioning this in the upgrade guide (there's entry about offset but it's far from obvious it makes `$(window).offset()` invalid) or/and in the API page.
