### ISSUE TITLE
Chrome 59: focusin triggert at input field with autocomplete

### ISSUE THREAD

**Issue by rogervanwile** [jquery/jquery#3689] opened 2017-06-08 12:00 UTC
### Description ###

If a user has login credentials stored in Chrome 59 and the browser autofills the form, the on focusin eventhandler is triggered. 

Without jQuery the event is not triggert.

The issue exists since the last version of chrome. 

### Link to test case ###

https://jsfiddle.net/fp4cyghh/3/

1. Open the link above.
2. Fill the form with credentials and save the credentials in your chrome
3. Open the show-Iframe so that chrome fills the form: http://fiddle.jshell.net/fp4cyghh/3/show/

Below the Iframe is a log where you can see that jQuery is triggerin a focusin event. With a native event listener this event is not triggered.

**Comment by dmethvin** [comment] 2017-06-10 16:20
I can't reproduce this. Are you running in incognito to ensure that there are no plugins interfering? Also I added the focus event: https://jsfiddle.net/fp4cyghh/4/

**Comment by rogervanwile** [comment] 2017-06-12 07:02
In the incognito mode the browser doesn't autofill the form. 

Here are screenshots from Chrome 58 and 59 from your page https://jsfiddle.net/fp4cyghh/4/

![chrome-59](https://user-images.githubusercontent.com/11217061/27022285-86b92c5e-4f4d-11e7-8a4e-35d492f89abc.png)
![chrome-58](https://user-images.githubusercontent.com/11217061/27022286-86ba06ec-4f4d-11e7-9fd3-6da7823cb324.png)

As you can see, in Chrome 59 jquery triggers the focusin event and for this reason the focus event is triggert. without jquery i cant reproduce that issue.

**Comment by dmethvin** [comment] 2017-06-12 13:29
Strange, I still can't reproduce the extra event on Chrome 59 Windows 10. Anyone else?

**Comment by timmywil** [comment] 2017-06-12 15:20
I followed the steps and also cannot reproduce on Chrome 59 Mac OS 10.12.5. Closing as worksforme.

**Closed by timmywil** 2017-06-12 15:20 UTC
Labels: Works For Me

**Comment by rogervanwile** [comment] 2017-06-13 08:21
How can I reopen the bug? 

@timmywil , @dmethvin : Does Chrome autofill the form at step 3? If not the password isn't stored correctly.

**Comment by rogervanwile** [comment] 2017-06-13 08:26
I just tested the bug in a completly new installation of Chrome 59.0.3071.86 and I can reproduce the issue. There are no external plugins installed.
