### ISSUE TITLE
:not selector not working

### ISSUE THREAD

**Issue by cyberer** [jquery/jquery#3017] opened 2016-03-24 15:22 UTC
jquery 2.2
using the :not selector in .find() will thow an error. In older jQuery as 1.10 it works well.
here is my fiddle: https://jsfiddle.net/nptsc20q/

**Comment by dmethvin** [comment] 2016-03-24 15:25
Duplicate of #2885

**Closed by dmethvin** 2016-03-24 15:25 UTC

**Comment by timmywil** [comment] 2016-03-24 15:30
Note that quotes fix it. https://jsfiddle.net/timmywil/nptsc20q/1/
