### ISSUE TITLE
doc.head is returning null in the DOMEval of jquery.js 3.0

### ISSUE THREAD

**Issue by ilapavuluri** [jquery/jquery#5254] opened 2023-05-17 10:15 UTC
### Description ###
I am loading html into an iframe component via below statement, this was working fine till jQuery 2.4 and failing from jQuery 3.0
jQuery('#reportDataFrame').contents().find('html').html(result.html); //this line is erroring out in the jQuery DOMEval "doc.head.appendChild( script ).parentNode.removeChild( script );" saying doc.head is null.

Actually my result.html has head element as well, but jQuery is not considering it. Did not find anything related to this in the release notes of jQuery 3.0

Complete code:
function getResults(event){

      if (document.getElementById('reportDataFrame') == null) {
        var frame = document.createElement('iframe');
        frame.setAttribute('id', 'reportDataFrame');
        frame.setAttribute('title', "<xsl:value-of select="$sharedxml/reportDataFrame"/>");
        frame.setAttribute('name', "<xsl:value-of select="$sharedxml/reportDataFrame"/>");
        frame.setAttribute('onload', 'loadResults()');
        frame.setAttribute('style', 'display:none;');
        
        
        document.body.appendChild(frame);
      }
      
      jQuery("#showReportResults").get(0).style.display="";
      
      var url = '<xsl:value-of select="concat($baseURL, icservletname)"/>';
      url += '?Node=<xsl:value-of select="concat('icguinode.',util:getNodeWithHandle('reportviewforselect',icuser/securityhandle))"/>';
      url += '&amp;Args=<xsl:value-of select="$html_DataID"></xsl:value-of>';
      url += '&amp;Args=&amp;Args=&amp;Args=25&amp;Args=1&amp;Args=&amp;Args=&amp;Args=&amp;Args=&amp;Args=&amp;Args=&amp;Args=&amp;Args='
      
      url = url + '&amp;b2b=json-html';
    
      jQuery.ajax({
        url : url,
        dataType : 'jsonp',
        error : onerror,
        success : function(result) { 
          jQuery('#reportDataFrame').contents().find('html').html(result.html); //here getting error 
          loadResults();
        }
      });
	  
    }

**Comment by dmethvin** [comment] 2023-05-17 12:15
To investigate we really need a minimal runnable test case that demonstrates the problem, including whatever markup is involved. I would guess, for example, that the ajax call isn't necessary to reproduce the problem and just makes diagnosis harder.

**Comment by mgol** [comment] 2023-06-30 16:04
Closing due to insufficient information. We can reopen if we get more data.

**Closed by mgol** 2023-06-30 16:04 UTC
Labels: Needs info
