### ISSUE TITLE
Set width issue if value in percentage, and the element uses box-sizing:border-box and has border set in pixels

### ISSUE THREAD

**Issue by gsouquet** [jquery/jquery#2429] opened 2015-06-25 11:32 UTC
Hi, 

Sorry if the issue name is a bit long and obscure but it didn't manage to describe that bug properly.
I could reproduce this issue with the following jQuery versions: 
* 1.11.3
* 1.10.2

For the demo purpose I use JSFiddle that uses `jQuery 1.11.0` .

Let's imagine this HTML structure: 

```html
<div class="parent">
  <div class="child"></div>
</div>
```

```css
.child {
  box-sizing: border-box;
  width: 50%;
  border-right: 15px solid #ff0000;
}
```

```js
$('.child').width('50%');
alert(document.querySelector('.child').style.width);
```

The `alert` will output `65%`, this 65%, is an addition of `50 + 15`.
You can see a working demo of this issue on this [JSFiddle](http://jsfiddle.net/ned1xcze/)

I dug a little more and could determined that the problem comes from `setPositiveNumber` and `augmentWidthOrHeight` method.

It seems that augmentWidthOrHeight doesn't take in account that the border/padding can have different unit compared to the content width.

I'm not sure what's the best way to fix that issue so that is why I create that issue instead of doing a pull request. 

Feel free to ask questions.
Thanks for your hard work.

**Comment by mzgol** [comment] 2015-06-25 13:22
Thanks for the report. This seems to be a duplicate of #1712.

**Closed by mzgol** 2015-06-25 13:22 UTC
