### ISSUE TITLE
You cannot programmatically focus an element after removing its focus handler

### ISSUE THREAD

**Issue by JoolsCaesar** [jquery/jquery#4867] opened 2021-03-29 14:07 UTC
### Description ###
I'm seeing this in the latest chromium browsers Windows Chrome & Edge 89, using jquery 3.6.

If you add and remove an element's focus handler, subsequent calls to $element.focus(), will do nothing.
HTML:
```html
<div tabindex="-1" class="fdiv"></div>
```
CSS:
```css
.fdiv{
  height:100px;
  width:100px;
  border:1px solid black;
}
.fdiv:focus{
  background-color:green;
}
```
See the linked to test case below. I have a simple div that turns green when you focus it and some js that will focus said div after 2 seconds.
Before setting this timeout I add and then immediately remove an empty focus handler:
```js
//Using https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js

const $origDiv = $('.fdiv');

// Comment out the following line to fix
$origDiv.on('focus',function(){}).off('focus');

setTimeout(function(){
	$origDiv.focus();
},2000)
```

If you run the fiddle, the div should turn green (gain focus) after 2 seconds, but it doesn't!
If you comment out the focus handler line, all works as expected.

### Link to test case ###
https://jsfiddle.net/JoolsCaesar/ut371acd/

---- 

<sup>EDIT by @mgol: I fixed syntax highlighting in code blocks.</sup>

**Comment by JoolsCaesar** [comment] 2021-03-29 14:12
FWIW I tracked this down to the bit in jquery:
```
function leverageNative( el, type, expectSync ) {

	// Missing expectSync indicates a trigger call, which must force setup through jQuery.event.add
	if ( !expectSync ) {
		if ( dataPriv.get( el, type ) === undefined ) {
			jQuery.event.add( el, type, returnTrue );
		}
		return;
	}
```
`dataPriv.get( el, type )` where `el` is the element we're attempting to focus and type is `'focus'` returns `false`, so we just drop out without doing anything.

**Comment by mgol** [comment] 2021-03-29 14:54
Thanks for the report! The code you mentioned exists since jQuery 3.4.0, I suspect it only became a problem after #4813 landed.

**Comment by JoolsCaesar** [comment] 2021-03-29 15:21
Makes sense. I spotted this after upgrading from 3.0.0 to 3.6.0, so couldn't narrow it down much.

**Comment by mgol** [comment] 2021-03-29 15:31
I meant the bug is only reproducible in jQuery 3.6.0, it works fine in 3.5.1 despite 3.5.1 contains the code you linked to. Hence, most likely it only causes the issue in connection with #4813 (although I haven't verified it yet).

**Comment by mgol** [comment] 2021-05-07 22:10
PR: #4885

**Closed** 2021-05-10 16:59 UTC
Labels: Bug, Event, Has Pull Request
