### ISSUE TITLE
Flask app: Valid json, but jQuery not called in Win 7  (Unexpected Token : ) ?

### ISSUE THREAD

**Issue by scheung38** [jquery/jquery#3783] opened 2017-09-13 00:44 UTC
I have  valid json as checked with JSONLINT, in flask application with end point

```
def support_jsonp(f):
    """Wraps JSONified output for JSONP"""

    @wraps(f)
    def decorated_function(*args, **kwargs):
        callback = request.args.get('callback', False)
        if callback:
            content = str(callback) + '(' + str(f().data) + ')'
            return current_app.response_class(content, mimetype='application/json')
        else:
            return f(*args, **kwargs)

    return decorated_function


@support_jsonp
@api.route('/release-data')
    def api_data():
    return json.dumps(data, sort_keys=True, indent=4, default=json_util.default)
```

Mongo server is with these settings:

$mongod.exe --rest --jsonp

in chrome browser:

http://localhost:50000/api/release-data

{ "columns": [ 0, 1, 2, 3, 4, 5, 6, 7, 8 ], "data": [  etc

and validated in JSONLINT, but when inside $.ajax

    var settings = {
            async: true,
            method: "GET",
            headers: {
                "cache-control": "no-cache"
            },
            contentType: "application/json",
            dataType: 'jsonp',
            callback: "logResults",
            crossDomain: true,
     
            success: function (data) {
                console.log("Success" + data);
            },

            error: function (XMLHttpRequest, textStatus, errorThrown) {
                console.log("Status " + textStatus + " LogError: " + errorThrown);
            },
        };
        $(document).ready(function () {
            $.ajax(settings);
        });

But when parsing in jQuery, I get 

jQuery334534643646345345346436_345345346436346 was not called?

 
![capture_jquery_token_issue](https://user-images.githubusercontent.com/1273014/30354541-6fd46930-982d-11e7-92c1-06935b440120.PNG)

**Comment by dmethvin** [comment] 2017-09-13 03:08
Your ajax request is Jsonp but your Json does not have any padding. At least I think it does not have padding since i can't reach your localhost to check. Your server would need to send the Json out with padding. Is there a flask mailing list or help forum where you could ask these questions rather than the bug tracker?

**Comment by mgol** [comment] 2017-09-13 08:50
Not a bug in jQuery, closing.

**Closed by mgol** 2017-09-13 08:50 UTC
