### ISSUE TITLE
$.each fails with undefined

### ISSUE THREAD

**Issue by minmur** [jquery/jquery#2395] opened 2015-06-15 06:59 UTC
Passing `undefined` to `$.each()` throws `Uncaught TypeError: Cannot read property 'length' of undefined` instead of silently skipping the iteration.
Tried with versions 1.11.0 and 1.11.3.

**Comment by Mr21** [comment] 2015-06-15 08:05
It's will be fixed #2363 soon

**Comment by timmywil** [comment] 2015-06-15 13:36
Duplicate of #2267.

**Closed by timmywil** 2015-06-15 13:36 UTC
