### ISSUE TITLE
jQuery 2.1.4 Bug in my web page

### ISSUE THREAD

**Issue by webmailer** [jquery/jquery#2383] opened 2015-06-08 23:15 UTC
![snip20150609_1](https://cloud.githubusercontent.com/assets/3146654/8047390/4db37676-0e77-11e5-9653-3fd094659dcc.png)

**Comment by AurelioDeRosa** [comment] 2015-06-08 23:18
Hi.

Can you please provide us more details about the code that is causing the issue? For example, can you reproduce it using [JSFiddle](http://jsfiddle.net/) or [JS Bin](http://jsbin.com/?html,css,output)?

**Comment by webmailer** [comment] 2015-06-08 23:40
Here is my source code.

**Comment by webmailer** [comment] 2015-06-08 23:41
I cannot attach a source code ZIP file here .  May I have your email address?

**Comment by AurelioDeRosa** [comment] 2015-06-08 23:52
You don't need to send me the code. Please use one of the two services that I suggest you in my previous comment.

**Comment by webmailer** [comment] 2015-06-08 23:59
I use jQuery 2.1.4 in my web applications. Many JS files are required. So I downloaded my source code with IE 11 by "save as" and also a Safari WebArchive .  

http://pan.baidu.com/s/1c0yHsMc
http://pan.baidu.com/s/1bndKDSb

Please download them from my sharings.

**Comment by Mr21** [comment] 2015-06-09 07:47
@webmailer, normally you have to provide a minimal JSFiddle who showing the bug.
But here I think it's the bug I repare two days ago #2382. About doing `$.each(undefined, ...)` (or `.map`).

**Comment by timmywil** [comment] 2015-06-09 15:20
Thank you for opening an issue, but issues need to be fleshed out more before they are opened on the repo. That said, @Mr21's assessment is most likely correct. Closing as duplicate of #2382.

**Closed by timmywil** 2015-06-09 15:20 UTC

**Comment by timmywil** [comment] 2015-06-09 15:22
Sorry, that should be #2267.

**Comment by webmailer** [comment] 2015-06-09 22:49
Thanks!  I found  a jQuery plugin causes this error (jQuery 2.1.4) .  I think $.each(...) 2.1.4/1.11.3 needs to be more stable if I have to write codes like that.
if (obj)
    $.each(obj, function() { ... })

My codes are right , but jQuery Plugins failed and causes this error. It means that some plugins written by others  will cause this error while jQuery updated to 2.1.4/1.11.3 . 
Will someone fix this in 2.1.5/1.11.4?

**Comment by Mr21** [comment] 2015-06-10 19:55
@webmailer I had the opportunity to fix it, already, but I don't know exactly how they choose what is going on the next version.

**Comment by timmywil** [comment] 2015-06-10 20:07
It will be in 3.0.
