### ISSUE TITLE
Shape of $.getJSON deferred changes depending on how it's used

### ISSUE THREAD

**Issue by ctheiss** [jquery/jquery#3031] opened 2016-04-01 16:05 UTC
Let's say I have a deferred `json = $.getJSON('//someplace')`.

If I call `json.done` or `$.when(json).done`, I get just the data per http://api.jquery.com/jquery.getjson/.

If I call `$.when(json, $.Deferred().resolve()).done`, I get an array, of which the data is the first element per https://api.jquery.com/jquery.when/ (see the last example).

I don't think the shape should change depending on how it's used.  Please see http://jsbin.com/tewusix/1/edit?js,output for a clear example of how the shape changes.

**Comment by dmethvin** [comment] 2016-04-04 23:04
This seems like the other side of the #3029 coin, which is arguing for the 3.0 regression to be fixed since we changed it to behave the way you are asking for here. @gibson042 I think this already in your I-told-you-so file. :smile_cat: What do you think would be best here?

**Comment by gibson042** [comment] 2016-04-05 14:24
https://github.com/jquery/jquery/issues/2018#issuecomment-70524248 (updated post-ES6, and emphasis added):
> Let's stop mixing that ~~[cast](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-promise.resolve)~~ [resolve](http://www.ecma-international.org/ecma-262/6.0/#sec-promise.resolve) operation with an "[all](http://www.ecma-international.org/ecma-262/6.0/#sec-promise.all)" operation. I don't even know which is the primary function of `$.when`, though this ticket implicitly assumes the latter and your suggestion ("have another utility that would be used for arrays _explicitly_") implicitly assumes the former. Maybe we can't even stop now, but we could certainly pave the way by **providing distinct functions (e.g., ~~`jQuery.Deferred.cast`~~ `jQuery.Deferred.resolve` and `jQuery.Deferred.all`**).

In short, I think the split personality of `jQuery.when` makes it a lost cause. And when fixing gh-3029, I plan to make the two signatures very distinct in source.

**Comment by dmethvin** [comment] 2016-04-05 15:12
Yeah, I'm only now starting to understand the mess here.

So, your recommendation is to "fix" the gh-3029 regression in 3.0 which brings back the `$.when` behavior that @ctheiss doesn't like. However, if you refactor we could get two newly named methods with more consistent semantics that match `Promise`. Those could go in with 3.0 or any following minor-version release.

@ctheiss it's important to note that **calling `$.when` with a single known `Deferred` is unnecessary and wasteful**. Unfortunately there is a lot of code out there that does it, led by our own [bad example](https://api.jquery.com/jquery.when/).

**Comment by ctheiss** [comment] 2016-04-05 15:14
I'm not sure if I'm reading this right, so I thought I might try wording the original ask in a different way.

`$.when(jsonDeferred).done(function(json) { console.log(json) });` writes an object to the console (whatever was parsed from the JSON).

`$.when(jsonDeferred, jsonDeferred).done(function(json) { console.log(json) });` writes an array to the log, the first element being the object from the first example, then a string, then a jqXHR.  The only difference is the number of arguments passed to `$.when`.

_This only happens with Ajax Deferreds, as far as I know._

If, instead of `jsonDeferred = $.getJSON(...)`, I write `jsonDeferred = $.Deferred(); jsonDeferred.resolve({ name:'Moop' });`, then all three examples look the same.

**Comment by dmethvin** [comment] 2016-04-05 16:36
@ctheiss `$.getJSON` returns a `jQXHR` which is a `Deferred` with some extra properties and methods. So in **jQuery <3.x only**:

* `$.when( jQXHR )` returns the exact same `jQXHR` object passed in.
* `$.when( deferred )` returns the exact same `deferred` object passed in.
* `$.when( deferred-or-jQXHR, deferred-or-jQXHR )` returns a *new* `Deferred` tied to the two incoming ones, lacking all the extra properties and methods of any incoming jQXHR.

For the 2-arg case `$.when` needs to figure out how to get the *entire* list of results to you from each of the two args. To do that it passes an array back to you, with each element in the array representing the resolved results. The jsbin you gave only looks at the first arg, but here is one showing the entire arg list that may be clearer: 

http://jsbin.com/taxubaxifi/edit?html,js,output

**Comment by ctheiss** [comment] 2016-04-05 20:26
@dmethvin Thanks for your response!  I think I understand:
- when `.done` is called directly on the `jQXHR`, the arguments are automatically unpacked to `function(obj, status, jQXHR)`, whereas
- when `$.when` is called, the arguments are not unpacked and you get `function([obj, status, jQXHR], ...)`.

In my mind, the args should be packed or unpacked consistently in both cases, since it seems strange to me to have to change the `.done` code depending on whether the Deferred is wrapped in a `$.when`.  But I understand the dilemma.

In either case, the 1-arg `$.when` is different between `https://code.jquery.com/jquery-git.js` and `https://code.jquery.com/jquery-2.2.3.js`.  Is this the result of #3029?

**Comment by dmethvin** [comment] 2016-04-06 12:21
> In my mind, the args should be packed or unpacked consistently in both cases, since it seems strange to me to have to change the .done code depending on whether the Deferred is wrapped in a $.when.

I agree and that's what @gibson042 is referring to above. `$.when` is actually serving two disjoint purposes. One is similar to `Promise.resolve` and converts its argument to a promise if it isn't one already. The other is `Promise.all` which waits until multiple promises resolve and returns a single promise representing the results. The single-arg case is where trying to do both starts to get really silly. 

> In either case, the 1-arg $.when is different between https://code.jquery.com/jquery-git.js and https://code.jquery.com/jquery-2.2.3.js. Is this the result of #3029?

It's a long story and we tried to clean it up in 3.0. For `$.Deferred` you can resolve with multiple values so the multi-input `$.when` has to pass those along in a sane way that allows you to sort them out. If you pass in 3 args to `$.when` the resolved values of the last promise will be an array element in the third arg, no matter how many values the first two resolved with.

With the new standard ES6 `Promise` you can only resolve with a single value so this problem with needing to pass an array never occurs.

**Comment by timmywil** [comment] 2016-06-30 17:04
Since the change of behavior is intentional in 3.0, I'm inclined to leave this as-is.

**Closed by timmywil** 2016-06-30 17:04 UTC
Labels: Deferred
