### ISSUE TITLE
Distorted UI after migrating jquery 3.5.1 from 3.4.1

### ISSUE THREAD

**Issue by Komal1223** [jquery/jquery#4823] opened 2021-01-04 06:31 UTC
### After updating 3.5.1 version my tiles are collapsed and has distorted UI ###
3.5.1:
![image](https://user-images.githubusercontent.com/54171181/103507011-23e82c80-4e84-11eb-982f-2ccec71ef4fb.png)

**Comment by mgol** [comment] 2021-01-04 07:01
Please read the issue template, it provides this issue as a frequently reported one. This is covered by the [jQuery 3.5.0 blog post](https://blog.jquery.com/2020/04/10/jquery-3-5-0-released/) & the [upgrade guide](https://jquery.com/upgrade-guide/3.5/). Also, it's a duplicate of #4681, #4693, #4709, #4710, #4720 & #4721.

**Closed by mgol** 2021-01-04 07:01 UTC
