### ISSUE TITLE
Focus in hidden element only work in second attempt

### ISSUE THREAD

**Issue by eduardo-mior** [jquery/jquery#5104] opened 2022-09-03 02:58 UTC
### Description ###
I have element (specifically in my case a `<select>`) that is hidden (`display: none`).

When trying to focus the field, the first time it fails, but the second time it works. Why?

I would understand if this never worked. The first time it doesn't work but the second time it works. Why?

Perhaps this is linked to:
https://github.com/jquery/jquery/issues/5015
https://github.com/jquery/jquery/issues/4950

### Link to test case
https://codepen.io/rushyoutuber/pen/PoeodNX

### Other informations
My jQuery version is **3.6.1**.
I tested this issue on Windows and MacOs, GoogleChrome and Firefox and Safari. The problem always happens.

**Comment by mgol** [comment] 2022-09-05 16:12
Thanks for the report. In versions before 3.4.0, you wouldn't get the handled invoked even once. And it makes sense - you can't really focus an item with `display: none`. It might be worth to investigate why there's an inconsistency between the first & second clicks, though.

**Comment by fecore1** [comment] 2022-10-14 14:31
I think the problem is with the block of [code](https://github.com/jquery/jquery/blob/main/src/event.js#L532-L600)

By the example above: 
> https://codepen.io/rushyoutuber/pen/PoeodNX

_Screenshot of function **dispatch**_
![image](https://user-images.githubusercontent.com/89127124/195867531-348da47c-9274-447e-9754-ece0bc821862.png)

First click:
in function `leverageNative`, `( event.isTrigger & 1 ) && this[ type ]` return true , `!saved.length` return true and saved is false. `this[ 'focus' ]()` can not trigger callback because of `display:none`, and dataPriv is not change, so `dataPriv.set(this, type, false);` is not invoked

saved is `[ event ]` after first click because the code `saved = dataPriv.get(this, type)`

But `event.stopImmediatePropagation();` is invoked in first click call process, so while loop in screenshot will be interrupted

Second click:
`( event.isTrigger & 1 ) && this[ type ]` return true , `!saved.length` return false because saved is `[event]`. And `event.stopImmediatePropagation();` can not be invoked. And while loop in screenshot will not be interrupted and focus callback will be invoked.

---

So should we  call `dataPriv.set(this, type, false);` anyway?

**Comment by mgol** [comment] 2023-04-18 09:14
This works with jQuery 3.x-git so it should work fine with the upcoming jQuery 3.7.0: https://codepen.io/mgol/pen/NWOrVNP

Closing as fixed by #5223 & #5224.

**Closed by mgol** 2023-04-18 09:14 UTC
Labels: Event
