### ISSUE TITLE
find() returns two dom object of same dom element for safari only

### ISSUE THREAD

**Issue by kumarrajudt** [jquery/jquery#2130] opened 2015-03-09 07:22 UTC
I am using jquery 1.10.2 and my problem is jquery returns the two dom elements for safari.

$("select").find("option:selected") ---- it return two dom objects of single element in safari browser for some options

**Comment by gibson042** [comment] 2015-03-09 11:59
Please link to a live demonstration on [JSFiddle](http://jsfiddle.net/)/[JS Bin](http://jsbin.com/)/etc. showing the behavior and how it deviates from your expectations.

**Comment by kumarrajudt** [comment] 2015-03-10 05:15
Thanks for your reply gibson...Here is the link for live demonstration....
Please open the link in safari browser and run the sample program and select the "Cycle" as the option and jquery returns the same DOM elements for two times
http://jsfiddle.net/x6edp7gj/

**Comment by gibson042** [comment] 2015-03-11 14:10
This is caused by use of numeric values for the `id` attribute. It is a duplicate of [http://bugs.jquery.com/ticket/14142](http://bugs.jquery.com/ticket/14142), which was fixed in jQuery 1.11: http://jsfiddle.net/x6edp7gj/1/

**Closed by gibson042** 2015-03-11 14:10 UTC
Labels: Needs info

**Comment by kumarrajudt** [comment] 2015-03-11 14:22
Thanks a lot to you for taking the  time to see this ticket and give a response for me......
