### ISSUE TITLE
TypeError: can't convert i to string

### ISSUE THREAD

**Issue by aydinantmen** [jquery/jquery#4668] opened 2020-04-14 09:57 UTC
I'm getting this error on console when I upgraded from 3.4.1 to 3.5.0 on bootstrap 4 navbar toggle. It's came from jquery's core. So I can't handle it.

**Comment by mgol** [comment] 2020-04-14 10:14
This bug report is missing way too many details for us to act on but I suspect this is a duplicate of #4665.

**Closed by mgol** 2020-04-14 10:14 UTC
