### ISSUE TITLE
Table with tfoot inside plain table results in weird DOM

### ISSUE THREAD

**Issue by ShyLionTjmn** [jquery/jquery#3439] opened 2016-12-08 09:38 UTC
Create simple table with THEAD,TFOOT and TBODY tags and insert it into plain table with just TR and TD.
You will get broken table.

Here is an example:
https://jsfiddle.net/5kbwkzq8/5/

**Comment by timmywil** [comment] 2016-12-19 17:38
It seems like the same thing would happen without jQuery. We can't stop you from building invalid html. However, the test case is pretty large. Would it be possible to reduce this even further? There's a lot going there.

**Comment by gibson042** [comment] 2016-12-19 18:36
Ok, this one is kind of cool. A \<tr> is being appended to a table that has no \<tbody>, but contains an inner table that _does_ have one. And when we try to find a \<tbody> to contain the incoming row, [we mistakenly use the one from the inner table](https://github.com/jquery/jquery/blob/2d4f53416e5f74fa98e0c1d66b6f3c285a12f0ce/src/manipulation.js#L54). This should be a straightforward fix.

**Comment by timmywil** [comment] 2016-12-19 23:02
Thanks for digging into that!

**Comment by ShyLionTjmn** [comment] 2016-12-20 04:00
Why is it invalid? TBODY is not required when <tr> comes after <table>.

**Comment by timmywil** [comment] 2016-12-20 16:45
@ShyLionTjmn at first glance, it looked like an unclosed tag or something, but @gibson042 dug further and it is a jQuery bug.

**Comment by ShyLionTjmn** [comment] 2016-12-21 04:06
Ok. Thanks.

**Comment by leonardjo** [comment] 2016-12-24 20:01
Seems indeed to be a duplicate of the issue I'm having. Commit 1f614ed fixes the issue I see. Thank you.

**Closed** 2017-01-09 19:37 UTC
Labels: Bug, Manipulation
