### ISSUE TITLE
The height of the element with the scroll bar is different. IE 11 & jQuery 3.2.0 or later

### ISSUE THREAD

**Issue by uk-taniyama** [jquery/jquery#3775] opened 2017-09-07 04:40 UTC
###  The height of the element with the scroll bar is different. 

Sample code.

```
$("<div style='width:100px; height:100px; overflow:scroll;'></div>").appendTo("body").height();
```

The result is as follows.....
- Chrome : 100
- IE 11 & jQuery 3.1.2 : 100
- IE 11 & jQuery 3.2.0 or later : 83

After reverting the following code, the expected value(100) is returned.

https://github.com/jquery/jquery/commit/c920ff6e322baddbb2bd04125c5577244dcb0320#diff-414c8f59bff0d1b63680b64763d8c529
```
	// Running getBoundingClientRect on a disconnected node
	// in IE throws an error.
	if ( elem.getClientRects().length ) {
		val = elem.getBoundingClientRect()[ name ];
```

**Comment by gibson042** [comment] 2017-09-08 05:52
This appears to be a duplicate of https://github.com/jquery/jquery/issues/3589 .

**Closed by gibson042** 2017-09-08 05:52 UTC

**Comment by uk-taniyama** [comment] 2017-09-08 06:49
Thanx. 
I understand. 
But, the height of the element with the scroll bar is different from older version.
So, sad......

**Comment by gibson042** [comment] 2017-09-08 15:03
#3589 has already been fixed in 80f1c8239e9d5f793f3e54e0cb8d7bd0747e4856. Our next release will restore correct behavior.

**Comment by uk-taniyama** [comment] 2017-09-11 03:50
i tried to build master and  do sample code as follows.

```
$("<div style='width:100px; height:100px; overflow:scroll;'></div>").appendTo("body").height();
````

then result is 79(by chrome).
BUT jQuery 3.1.1 is 100.

Current version height is exclude the scrollbar's height. so this is same as clientHeight.
BUT jQuery height is not equals clientHeight.
jQuery height is sum of padding and content height.

![sample](https://user-images.githubusercontent.com/24251242/30257818-9d152072-96ef-11e7-99d6-22ccdcf203d7.png)

**Comment by gibson042** [comment] 2017-09-11 04:37
http://api.jquery.com/height/ :
> Note that <code>.height()</code> will always return the content height, regardless of the value of the CSS <code>box-sizing</code> property.

("content height" being the height of the CSS [content box](https://drafts.csswg.org/css-box/#content-box), from which [scrollbars are subtracted](https://drafts.csswg.org/css-box/#ref-for-propdef-overflow-1))

Use `.innerHeight()` to include padding, and `.outerHeight()` to additionally include borders. And if you need anything further, please post a live example on [JSFiddle](https://jsfiddle.net/)/[JS Bin](https://jsbin.com/)/etc. so we can investigate.

**Comment by uk-taniyama** [comment] 2017-09-11 13:47
jquery-3.1.1
https://embed.plnkr.co/5qkyeYKgPkTYRazuYfqK/

jquery-3.2.2-pre
https://embed.plnkr.co/fdOrj9HyJsDyWVZ1lH4f/

**Comment by gibson042** [comment] 2017-09-11 18:05
Thanks. The git build looks correct to me: https://embed.plnkr.co/CSMSz4QDtTdQ8RT3X7UR/

**Comment by uk-taniyama** [comment] 2017-09-12 00:29
Thanks a lot.
jquery-3.1.1.
https://embed.plnkr.co/5qkyeYKgPkTYRazuYfqK/

result is follows at Windows 10, Chrome 61.
![result](https://user-images.githubusercontent.com/24251242/30302379-95fd4f24-979b-11e7-9d8c-ceb770c0be1f.png)

this is correct spec. and good bug fix. but different with jquery-3.1.1.
